### PR TITLE
valgrind

### PR DESCRIPTION
**Pull request by juj**
Add support for running tests with valgrind.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm

**Comment by juj** [comment]
Had to make a small build fix after @kripken's comment above to fix the torture+waterfall build. Not sure how the waterfall builds work btw, since I'm unable to get them running, the download step always fails for me.

**Comment by kripken** [comment]
What was the build fix? (I just see one commit here, so I can't tell the diff directly.)

**Comment by juj** [comment]
The fix was to add these two lines: https://github.com/WebAssembly/binaryen/pull/785/files#diff-80ee07c6b10902b1bae15660a736de65R108 and https://github.com/WebAssembly/binaryen/pull/785/files#diff-80ee07c6b10902b1bae15660a736de65R630 and the one line below. Those calls run without valgrind, I don't know how to integrate with them, or if that makes sense even, since they call a script ` link_assembly_files` outside this repository.

**Comment by juj** [comment]
For curiosity, timings to run the suite with and without Valgrind:

    Without Valgrind:
    real    10m26.104s
    user    13m16.888s
    sys	    1m31.612s

    With Valgrind:
    real    39m9.835s
    user    41m17.384s
    sys	    2m28.404s

so Valgrind will be about 4x perf cost to run the suite.

**Comment by kripken** [comment]
Thanks, interesting.

We have AddressSanitizer coverage on travis, so it doesn't seem high priority to get valgrind up, but it might be useful. In particular it could be useful to run locally when an issue seems like the kind valgrind can catch.

**Comment by juj** [comment]
Set up the OS X bot to run with Valgrind, so if there's something that might pop up, the bot should report now. Ran the suite through Valgrind locally, it came out clean.

**Comment by dschuff** [comment]
One thing valgrind does do is catch uses of uninitialized values, which
ASan does not. MSan does, but you have to have the C++ stdlib built with
MSan too, which makes it harder.
Valgrind is a lot slower but in general easier. So as long as the support
isn't too onerous I'm happy to have it.

On Mon, Oct 17, 2016 at 6:27 PM Alon Zakai <notifications@github.com> wrote:

Thanks, interesting.

We have AddressSanitizer coverage on travis, so it doesn't seem high
priority to get valgrind up, but it might be useful. In particular it could
be useful to run locally when an issue seems like the kind valgrind can
catch.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/WebAssembly/binaryen/pull/785#issuecomment-254381391>,
or mute the thread

**Pull request merged**
