### PR TITLE
[LegalizeJSInterface] Use explicit names for stub functions

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
I wonder if there is a better way to handle fallout from making names not explicit by default?

**Comment by kripken** [comment]
What is the specific fallout here? That is, why is this necessary - does it fix something?

**Comment by sbc100** [comment]
> What is the specific fallout here? That is, why is this necessary - does it fix something?

No expected fallout, just improved debugging experience since these functions now have meaningful debug names.

This change allows us to re-enable the test_no_legalize_js_ffi test which is checking explicitly for imports that start with `$legalimport`.  

See https://github.com/WebAssembly/binaryen/pull/6428#issuecomment-2263958858

**Comment by sbc100** [comment]
> > What is the specific fallout here? That is, why is this necessary - does it fix something?
> 
> No expected fallout, just improved debugging experience since these functions now have meaningful debug names.
> 
> This change allows us to re-enable the test_no_legalize_js_ffi test which is checking explicitly for imports that start with `$legalimport`.
> 
> See [#6428 (comment)](https://github.com/WebAssembly/binaryen/pull/6428#issuecomment-2263958858)

I think whenever we give something a useful name like this in binaryen it should be preserved in the debug name section.. just dropping the name completely (which is what happens without the ExplicitName flag set) seems like the wrong default.   This was changed at some point which has had a fair amount of fallout.

**Comment by kripken** [comment]
Oh, I see, thanks. Yes, this makes sense: we do want explicit names here for debugging, and that test is looking at such internals.

**Review by kripken — APPROVED** [review]

**Comment by kripken** [comment]
> This was changed at some point which has had a fair amount of fallout.

Yeah, maybe the other default would be better, since the harm would only be some meaningless names in the name section.

Do you think there are more cases left to handle for it? If so I'm not opposed to changing the default.

**Comment by sbc100** [comment]
> > This was changed at some point which has had a fair amount of fallout.
> 
> Yeah, maybe the other default would be better, since the harm would only be some meaningless names in the name section.
> 
> Do you think there are more cases left to handle for it? If so I'm not opposed to changing the default.

I think we would want to draw is clear distinction between names that were explicitly given like this ones and names that binaryen makes upon the fly simply because it needs everything to be named (e.g. `function42`).   The former we always want in the name section and the later we never want (I think).

**Comment by sbc100** [comment]
See #6496.

I think the original issue is from #6466

**Pull request merged**
