### PR TITLE
Expose asyncify state via a getter

### PR DESCRIPTION
**Pull request by RReverser**
Normally, a wrapper has to track state separately to know when to unwind/rewind and when to actually call import functions.

Exposing Asyncify state can help avoid this duplication and avoid subtle bugs when internal and wrapper state get out of sync.

Since this is a tiny function and it's useful for any Asyncify embedder, I've decided to expose it by default rather than hide behind an option.

### CODE REVIEW

**Comment by RReverser** [comment]
> Adds a little code but in tools that can be optimized out if not used (like metadce in emscripten).

I think it will also help remove some code on the JS side and might even result in a net negative. But even if not, it's a negligible difference compared to general Asyncify overhead anyway :)

> Lines 130-150 have some doc description of the exported functions, please add to there.

Will do!

**Comment by RReverser** [comment]
> Lines 130-150 have some doc description of the exported functions, please add to there.

Done.

**Comment by kripken** [comment]
> I think it will also help remove some code on the JS side

True, but it would mean a JS=>wasm call instead of a JS property lookup, which would be slower. In emscripten I think probably we wouldn't use it (but definitely sounds useful for other places!).

**Comment by kripken** [comment]
Oh, looks like line 130 has "four" which is no longer true after this change ;) please update that (can commit with `[ci skip]` to not wait, and avoid CI time.

**Comment by RReverser** [comment]
Thanks, updated. Looks like CI is still waiting at least to get started though.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
