### PR TITLE
Test s2wasm using buildbot's last known good .s files

### PR DESCRIPTION
**Pull request by jfbastien**

### CODE REVIEW

**Comment by jfbastien** [comment]
@kripken I don't think this is quite ready to merge, but I'd appreciate your input (I'm heading out the door now, will get back to this later today).

**Comment by jfbastien** [comment]
@kripken I think this is now good to go, the tests all run and pass locally.

**Comment by kripken** [comment]
I think I'd prefer to check in the files, so that bisection can work without depending on a remote server. What do you think?

**Comment by kripken** [comment]
For that we still need this code, just the fetch part would be in a separate file, that we'd run manually. Similar to updating a git submodule. In fact maybe the tests could be in their own git repo, and this would be a submodule, come to thin of it?

**Comment by jfbastien** [comment]
That sounds fine. I'm not sure how to do the git repo thought: the build server would require some credentials to upload its results. Or did you have something else in mind?

**Comment by jfbastien** [comment]
@kripken: LMK if #57 is what you were thinking about. If so, this PR will be rebased to just add the testing (since the update part should be done separately). I can also update README.md.

**Comment by kripken** [comment]
Yeah, #57 is great, thanks. Next steps sound good.

**Comment by jfbastien** [comment]
README updated, and everything but the testing remove. @kripken good to go?

**Comment by kripken** [comment]
lgtm. Maybe squash it all to one commit when rebasing?

**Comment by jfbastien** [comment]
Merged as one commit in c7e7a9215e4c833653549b806a29b02399320bd6, I wasn't sure how to update this PR with the squashed commits.

**Comment by kripken** [comment]
(a `push -f` should work, for any update, including of squashed commits)

**Pull request closed without merging**
