### PR TITLE
Investigate GitHub deprecation of artifact uploading v1

### PR DESCRIPTION
**Pull request by kripken**
We started to error on this, e.g.

https://github.com/WebAssembly/binaryen/actions/runs/10705658056/job/29681561108?pr=6899

### CODE REVIEW

**Comment by kripken** [comment]
@sbc100 you added this usage of upload-artifact in https://github.com/WebAssembly/binaryen/pull/2826 Do you know what it is doing? I can't figure out if we need it or not.

**Comment by sbc100** [comment]
> @sbc100 you added this usage of upload-artifact in #2826 Do you know what it is doing? I can't figure out if we need it or not.

It looks like we use it to upload the release binaries to github.

**Comment by sbc100** [comment]
> > @sbc100 you added this usage of upload-artifact in #2826 Do you know what it is doing? I can't figure out if we need it or not.
> 
> It looks like we use it to upload the release binaries to github.

Actually it looks like `.github/workflows/create_release.yml` takes care of this. 

I guess this action is just so that its possible to download the results of CI.  Seem fairly useful.

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
Oh, I didn't know downloading them was possible. I wonder if any of us use that? Anyhow, let's land this for now to fix the breakage.

**Pull request merged**
