### PR TITLE
Add a superclass typedef to WalkerPass to simplify overrides

### PR DESCRIPTION
**Pull request by jgravelle-google**

### CODE REVIEW

**Comment by jgravelle-google** [comment]
Not possible to do in `Walker` because that tosses out the `WalkerType`, so `super::scan` just calls `Walker::scan` which just aborts.

Alternatively, we could redeclare the typedef in each derived walker, which would keep the WalkerType information, but duplicate the typedef and add something to remember to do in the future when we derive Walkers probably. I like the small-change part of just having one typedef, but I'm not married to that per se.

Historical funsies, C++ almost had a `super` keyword that did basically this, but the committee decided that typedeffing everywhere was better https://stackoverflow.com/a/180633 .

**Comment by binji** [comment]
There is a (small) potential danger defining it in the base class, in that if you add an intermediary class you'll need to define `super` there as well, or it will silently do the wrong thing. Not sure if that's common in Binaryen though.

**Comment by kripken** [comment]
I don't think we do that now, but I'm not sure we won't want to later, hmm.

**Comment by kripken** [comment]
Anyhow, I think this is good to land. Not too worried about silent weirdness, we should get a noticeable error if we get that wrong, the logic should be different enough.

**Pull request merged**
