### PR TITLE
Fix binary parser of declarative element segments

### PR DESCRIPTION
**Pull request by tanishiking**
The parser was incorrectly handling the parsing of declarative element segments (those with the `elemkind` of `declarative`).
According to the spec, the `init` of the declarative element should be a `vec(expr)` if the prefix is 7.
https://webassembly.github.io/spec/core/binary/modules.html#element-section
However, binaryen was simply reading a single `u32LEB` value for each
expression instead of parsing a expression regardless `usesExpressions = true`.

This commit updates the `WasmBinaryReader::readElementSegments` function
to correctly parse the expressions for declarative element segments by
calling `readExpression` instead of `getU32LEB` if `usesExpressions = true`.

Resolves the parsing exception:
"[parse exception: bad section size, started at ... not being equal to new position ...]"

Related discussion: https://github.com/tanishiking/scala-wasm/issues/136

### CODE REVIEW

**Comment by kripken** [comment]
I'm not very familiar with this part of the spec, but it looks like there are broken tests on CI here so perhaps additional changes are needed?

**Comment by tanishiking** [comment]
Thanks! Indeed, it seems like the problem is, we have to switch the `init` is `vec(expr)` or `vec(funcidx)` based on the the prefix is 3 or 7 (and we didn't).

Screenshot 2024-05-23 at 10 33 54

https://webassembly.github.io/spec/core/binary/modules.html#element-section

I'll fix it

**Comment by tanishiking** [comment]
I think I could fix the issue, but in my local environment, some tests fail because of the following 

```
/Users/tanishiking/ghq/github.com/tanishiking/binaryen/test/lit/fuzz-types.test:31:15: error: found empty check string with prefix 'CHECK:'
;; CHECK-NEXT:
              ^

error: command failed with exit status: 2
```

which seems some kind of problem in my local setup(?) and unrelated to the change (actually it fails even in `main` branch)

**Comment by kripken** [comment]
Maybe the local error is due to the `lit` version? Installing it this way may help:

https://github.com/WebAssembly/binaryen/blob/06cbe01f2774955ed3f23994b3ea1db58e43a4d8/requirements-dev.txt#L4

The code here looks right to me. Please add a test for this so we don't regress it. The test could be under `test/lit/` if there isn't a specific obvious file to add to.

**Comment by tlively** [comment]
Note that the SExpressionWasmBuilder is deprecated and about to be removed in #6607. The parser your tests are using is implemented in the src/parser directory. It still doesn't preserve declarative segments in the IR, though.

This is a case where checking in a binary test would be appropriate. Other such tests live in the test/lit/binary directory.

**Comment by tanishiking** [comment]
Thanks, I added a test for `wasm-dis` that verifies the binary parser parses the declarative element segment that uses expression.
 https://github.com/WebAssembly/binaryen/pull/6618/commits/36bb145c5f50d0b39453f4297a1ac80bedac5a91

**Comment by tlively** [comment]
Can you move the test to `test/lit/binary` and follow the pattern used by other tests there? We're generally trying to move tests to `lit` over time because it is faster and requires less maintenance than our bespoke test runners.

**Comment by tanishiking** [comment]
Sure, moved the test to `test/lit/binary` https://github.com/WebAssembly/binaryen/pull/6618/commits/02efecd94395e94e7d28a097397ab590a3b8ba21

**Pull request merged**
