### PR TITLE
Added memory utility to binaryen-c/.js

### PR DESCRIPTION
**Pull request by dcodeIO**
Adds the following functions to the C-API:

* **BinaryenGetMemoryInitial**
  Gets the initial size of the memory, in pages.

* **BinaryenSetMemoryInitial**
  Sets the initial size of the memory, in pages.

* **BinaryenGetMemoryMax**
  Gets the maximum size of the memory, in pages.

* **BinaryenSetMemoryMax**
  Sets the maximum size of the memory, in pages.

* **BinaryenRemoveMemory**
  Removes the module's memory.

* **BinaryenHasMemory**
  Tests if the module has an existing memory.

* **BinaryenHasMemoryExport**
  Tests if the module's memory is exported.

* **BinaryenSetMemoryExport**
  Sets if the module's memory is exported. Must have a memory. Providing `NULL` as the name removes the export.

* **BinaryenHasMemoryImport**
  Tests if the module's memory is imported.

* **BinaryenSetMemoryImport**
  Sets if the module's memory is imported. Must have a memory. Providing `NULL` for both names removes the import.

Likewise, these methods are present on `Module` instances in binaryen.js. Its kitchen sink test has been updated accordingly and the recompiled binaries are included.

This is part of multiple PRs as previously tracked in #1261. Might be necessary to rebase (or just recompile the JS binaries) if #1269 lands earlier.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Note that `BinaryenSetMemoryExport` isn't ultimately necessary because there is `BinaryenAddExport` / `BinaryenRemoveExport`. However, there is no `BinaryenHasExport` yet, or any other way to determine the export name of the memory in order to check for a memory export, so I decided to include it for convenience.

**Comment by kripken** [comment]
This mostly looks good, but the export parts and the issues you mentioned in the last comment made me read the existing code more carefully, and we have a pre-existing problem, where `BinaryenAddExport` doesn't receive the kind, and doesn't set a kind on the export it creates. I think that might be because we added it before the `ExternalKind` stuff was added...

Anyhow, instead of adding new export code here, could we add a kind to the current export, which would allow exporting the memory?

**Comment by dcodeIO** [comment]
Sure, could also update `BinaryenAddExport` / `BinaryenRemoveExport` / `BinaryenAddImport` / `BinaryenRemoveImport` accordingly. Depending on the external kind provided, these would then perform additional steps (i.e. updating `wasm->memory` for memories).

**Comment by dcodeIO** [comment]
One issue I see is that different `ExternalKind`s currently require a different set of arguments. There is just one memory, for example, so there is not really an `internalName`, while there is one for functions. That could be circumvented by creating one `SetExport` etc. for each `ExternalKind`, including their respective additional steps.

**Comment by dcodeIO** [comment]
While introducing `ExternalKind` to the C-API with the intent to unify AddImport/AddExport, I noticed that `BinaryenAddImport` currently has the following signature:

```
BinaryenImportRef BinaryenAddImport(
  BinaryenModuleRef module,
  const char* internalName,
  const char* externalModuleName,
  const char *externalBaseName,
  BinaryenFunctionTypeRef type <---
)
```

The last parameter is used for function types exclusively. Globals would need a different type parameter, namely their WasmType. Hence wondering if unifying, with some kind-dependent and otherwise irrelevant parameters (i.e. `functionTypeIfApplicable`, `globalTypeIfApplicable`), is really what we want. I'd still prefer one AddImport/AddExport function for each kind.

How would you design it?

**Comment by kripken** [comment]
Yeah, I see what you mean. So maybe `AddFunctionImport`, `AddGlobalImport` etc. is indeed nicer.

**Comment by dcodeIO** [comment]
Closing in favor of #1292. Might come back to the respective getters and setters later.

**Pull request closed without merging**
