### PR TITLE
Update check.py and documentation to match emscripen PR4135

### PR DESCRIPTION
**Pull request by dschuff**
Matches the new argument and config in  https://github.com/kripken/emscripten/pull/4135/

### CODE REVIEW

**Comment by kripken** [comment]
This will break tests unless we also update the emscripten submodule. I can do that here.

**Comment by kripken** [comment]
That push should do it. Note I returned BINARYEN to pointing to the root, not the `/bin` dir, as it was before, I didn't catch that in review.

**Comment by dschuff** [comment]
No problem; any particular reason why? I don't have strong feelings about it but I switched it for consistency with `LLVM_ROOT` and `EMSCRIPTEN_ROOT` and because I didn't see any particular reason to require that the the binaries live in a directory with a specific name.

**Comment by kripken** [comment]
It's likely we'll need additional non-binary tools from binaryen, like script wrappers for JS engines and so forth. And it's consistent with `EMSCRIPTEN_ROOT`. It's true that `LLVM_ROOT` is a little different, perhaps that should have been renamed way back.

**Pull request merged**
