### PR TITLE
use fastMath condition for rules in #3289

### PR DESCRIPTION
**Pull request by MaxGraey**
cc @kripken

### CODE REVIEW

**Comment by kripken** [comment]
I'm not sure we need fastMath here - this may be something to fix in the interpreter. That is, I think the optimization is fine, while the interpreter is behaving nondeterministically.

The testcase in #3289 does `div(nan1, neg(nan2))`. According to [the rules](https://webassembly.github.io/spec/core/exec/numerics.html#nan-propagation) the negation just flips the sign deterministically, so that must be equal to `div(nan1, -nan2)`. And then the division then returns a nan, which must be canonical if the inputs are, or otherwise must be arithmetic, but in both cases is otherwise unspecified. In particular, it can pick the sign as positive or negative, which is what it looks like is the difference in that output. So IIUC, if we make the interpreter pick a positive NaN when it has the choice, it would fix that testcase.

Specifically, all floating-point operations on Literal could call a `standardizeNaN` function which would do that.

But it's possible I've misunderstood something there. If we are not sure, a simpler/safer option is to put those behind fastMath, and to add a TODO to look into it more.

**Comment by MaxGraey** [comment]
I agree. Better if interpreter deterministically produce canonical result for two non-canonical or canonical NaNs based on NaN propagation rules in wasm spec:  https://webassembly.github.io/spec/core/bikeshed/index.html#nan-propagation%E2%91%A0

**Comment by kripken** [comment]
Sounds good. Do you want to do it in this PR @MaxGraey ? Or if you prefer I can.

**Comment by MaxGraey** [comment]
It will be great if you do this with proper descriptions. Also I'm not deep dive in interpreter part yet so you might do this much faster than me)

**Comment by MaxGraey** [comment]
Сlosing in favour #3298

**Pull request closed without merging**
