### PR TITLE
Don't simplify using de-morgan's rules on floats, because of nans

### PR DESCRIPTION
**Pull request by kripken**
My bad.

### CODE REVIEW

**Comment by sunfishcode** [comment]
This is actually safe for eq and ne, though not for lt/le/gt/ge.

**Comment by kripken** [comment]
Oh, am I wrong in believing that all operations on a NaN return false? So `NaN == NaN` is false while `NaN != NaN` is true?

**Comment by binji** [comment]
Yes, AIUI `x != x` is true if and only if x is NaN. (Actually, I rely on this when generating the `assert_return_nan` checks for the spec tests.)

**Comment by kripken** [comment]
Ok, thanks. Maybe some day I'll really understand NaNs ;) I'll prepare a PR to return the eq/ne stuff.

**Pull request merged**
