### PR TITLE
s2wasm: Export all address-taken functions

### PR DESCRIPTION
**Pull request by dschuff**
I'm proposing a dyncall implmentation (https://github.com/kripken/emscripten/pull/4236) for wasm that looks up the
function by name and calls it. This means that address-taken functions
need to be exported.

### CODE REVIEW

**Comment by jfbastien** [comment]
Sounds fine as a short-term fix, probably worth opening an issue to undo this later?

**Comment by kripken** [comment]
The reason I'd prefer the alternative mentioned in kripken/emscripten#4236 is that the total code would be less, and it would be only in one repo. That is, adding dynCall in s2wasm should be pretty simple, and then things would just work. We can even write that s2wasm code using the [new builder interface](https://github.com/WebAssembly/binaryen/blob/master/src/wasm-builder.h).

**Comment by dschuff** [comment]
Funny you should mention that, i was just exploring that as we speak. I'm not convinced yet that there will be no need for any changes to emscripten but we'll see. We may consider even doing this in the LLVM wasm backend in the future (perhaps a post-s2wasm future?), or a least some well-defined mechanism for accomplishing the same goal as dyncall.

Speaking of wasm builder and Binaryen's IR, it seems suboptimal to require that all locals be named, and GetLocal/SetLocal always use the name of that local. Especially if we want to make the IR and the traversal mechanisms be part of some generic library.

**Comment by dschuff** [comment]
Btw we may very well have to revisit the details of this mechanism, when we consider linking, and dynamic linking.

**Comment by kripken** [comment]
Suboptimal in what sense? Compilation speed? Or convenience of use of API?

**Comment by dschuff** [comment]
In the sense that it can't represent a lot of valid wasm AST (namely, AST with unnamed locals), that users may not want to make up variable names just to use the API, and that variable names take up space in binaries.

**Comment by kripken** [comment]
Got it. Yeah, fair point. I've been thinking we should move Names to be just indices at some point, I just didn't want to do it too early when the compiler was in bad shape (much easier to debug stuff with normal names). But maybe now or soon is a good time. Of course names would still be optional, kept on the side in the module. The one risk factor is keeping that side data thread-safe (so passes can be parallalized).

**Comment by dschuff** [comment]
Probably the IR should reflect the AST semantics, which is that the index is the canonical identifier, but locals can optionally have names as well. E.g. maybe the IR node for a function has a list of names of locals, any of which can be empty. Names only get updated on function creation. The IR node for get_local just has an index. And maybe there are 2 builder methods for get_local, which take an index or a name. Or something like that.

**Comment by dschuff** [comment]
https://github.com/WebAssembly/binaryen/pull/337 is partway toward making s2wasm generate dyncall thunks. Mostly it adds some stuff to wasm::Builder and makes S2wasmBuilder use it.

**Comment by dschuff** [comment]
Closing in favor of #342

**Pull request closed without merging**
