### PR TITLE
Add a tracing option to the c api

### PR DESCRIPTION
**Pull request by kripken**
This  logs out c api calls, in the form of a runnable program, so it makes creating testcases easy.

### CODE REVIEW

**Comment by kripken** [comment]
Ok, I ran into some testing issues but now everything should be good, if someone wants to take a look.

@lqd, this implements the tracing stuff we were discussing, let me know what you think. If you want to try it some docs are in [the .h c api file](https://github.com/WebAssembly/binaryen/pull/627/files#diff-995571cd6e443e92b160c006c8baa753R420).

**Comment by kripken** [comment]
Great, looking forward to hearing how it works for you :)

**Comment by kripken** [comment]
Side note, I also added some docs on the [wiki](https://github.com/WebAssembly/binaryen/wiki/Compiling-to-WebAssembly-with-Binaryen#debugging-c-api-usage-using-tracing) for this.

**Comment by lqd** [comment]
@kripken I was able to get a trace without problems. I didn't try it under osx clang/gcc but getting the trace to compile with VS2015 was harder.
It seems it doesn't like empty arrays such as: BinaryenIndex paramTypes[] = {  };
which fails with: "error C2466: cannot allocate an array of constant size 0"
(after making it compile, I still have issues linking, but that's more indicative of my level of experience with VS2015, ie none whatsoever, vs gcc, than because of the trace output per se)

**Comment by kripken** [comment]
Thanks, a fix for the empty array issue is in #631.

**Pull request merged**
