### PR TITLE
Compiles on Windows

### PR DESCRIPTION
**Pull request by griffin2000**
Compiles on Windows, works for me but not necessarily best code

### CODE REVIEW

**Comment by kripken** [comment]
Looks like this broke building on linux on travis.

**Comment by kripken** [comment]
We've had other changes to those lines, perhaps one of them fixed this?

**Comment by jfbastien** [comment]
Right, I thought that was already fixed with the right type?

**Comment by dschuff** [comment]
I tested yesterday and the current master branch compiles for me with VS2015. Good enough to close this?

**Comment by kripken** [comment]
I think these windows issues have been fixed, we test windows on the bots now too.

**Pull request closed without merging**
