### PR TITLE
Inline many

### PR DESCRIPTION
**Pull request by kripken**
While before we inline only when there is just 1 use (so that we can remove the function afterwards, and are at little risk of increasing code size), this PR makes us inline multiple times in -O3, i.e., when we want max perf and don't care much about size.

On the testcase from https://github.com/WebAssembly/binaryen/issues/1110#issuecomment-320005775 I see (on sm)

Allow traps: **168ms**
Clamp before: **340ms (103% slower)**
Clamp with this PR, which inlines many of the clamp methods: **238ms (41% slower)**

So there is a large speedup, due to inlining all the calls to f64-to-int etc., but it doesn't get us all the way - clamping still takes work, we just got rid of the call overhead. There is also a code size downside of 4.5%.

Thoughts?

### CODE REVIEW

**Comment by kripken** [comment]
Looks like something bad happens in `binaryen3.test_printf`, noting to investigate that further.

**Comment by sunfishcode** [comment]
An alternative for implementing clamping float-to-int conversion is `fabs(x) < 0x1p31 ? (int)x : slowpath(x)`, which handles both positive and negative out-of-range as well as NaN in a single comparison, so it's smaller code and likely faster than doing multiple comparisons.

**Comment by kripken** [comment]
If I understand that, it would be slower in some corner cases (values around the absolute size of 1^31, 1^32, due to asymmetry around 0, etc.)?

**Comment by sunfishcode** [comment]
Right. The fabs trick is for signed conversions. If you're concerned about being slow in the corner cases, you can either do two branches, one for min and one for max, or, since the current code returns INT_MIN on error, you could make the "slow path" just be to return INT_MIN, since that's also the result value in the corner cases.

For unsigned, I think you need to do two branches, one for `> -1` and one for `< 0x1p32`.

**Comment by kripken** [comment]
I see. Well, this seems a little tricky, let's leave it for future careful investigation. I think this PR is orthogonal to that, even if it was motivated by it, as there are other use cases for inlining.

**Comment by kripken** [comment]
Gathering some more data, this actually shrinks code size in most cases, since it just inlines small things without calls or loops etc, and they tend to get optimized well. The one outlier in the benchmark suite is lua, where it increases code size by 1.5%, as it manages to successfully inline many of the little lua helper functions.

Speed-wise, no noticeable differences on the benchark suite. This probably is only noticeable in cases where the call overhead is really large, and many apps avoid such things or the LLVM optimizer helps them avoid them.

Still, I think this is useful to merge, as it does help significantly on the benchmark at the top of this issue as one example. It basically makes our inlining pass more line a normal inlining pass.

**Pull request merged**
