### PR TITLE
Refactor optimization defaults

### PR DESCRIPTION
**Pull request by kripken**
Followup to #1357. This moves the optimization settings into `pass.h`, and uses it from there in the various places.

This also splits up huge lines from the tracing code, which put all block children (whose number can be arbitrarily large) on one line. This seems to have caused random errors on the bots, I suspect from overflowing a buffer. Anyhow, it's much more clear to split the lines at a reasonable length.

cc @dcodeIO , this is the refactoring I mentioned I was planning to do for #1357. The other followup we discussed was to use the new MODULARIZE_INSTANCE option, which landed in emscripten earlier today, were you going to do that?

### CODE REVIEW

**Comment by dcodeIO** [comment]
> The other followup we discussed was to use the new MODULARIZE_INSTANCE option, which landed in emscripten earlier today, were you going to do that?

That's great, going to take a look now :)

**Comment by dcodeIO** [comment]
Currently testing with version 42. When I set optimizeLevel=2, shrinkLevel=2 and debugInfo=0, inlining should be performed [as of this](https://github.com/WebAssembly/binaryen/blob/0a9ddae715b2cff23a86cf14bbf6a4b870511395/src/passes/pass.cpp#L185), but it isn't. Not sure if that's a general issue or if I missed something when I initially added the options. Putting this here in case you have an idea.

**Comment by kripken** [comment]
Just `inlining-optimizing` should be enough. But the conditions in the inlining pass check for code size, existence of loops, and some other heuristics, so even if the pass runs it may not inline what you want, maybe that's the issue? If not, do you have a testcase showing the issue?

(We should also improve those heuristics :) )

**Comment by dcodeIO** [comment]
I think I might actually be wrong. While I was preparing an example, I noticed that a couple of functions are indeed inlined with the $__inlined_something block removed.

For what it's worth, the examples I initially prepared were:

[tlsf.ts](https://github.com/AssemblyScript/assemblyscript/blob/binaryen-inlining/examples/tlsf/assembly/tlsf.ts) -> [tlsf.untouched.wast](https://github.com/AssemblyScript/assemblyscript/blob/binaryen-inlining/examples/tlsf/tlsf.untouched.wast) -> [tlsf.optimized.wast](https://github.com/AssemblyScript/assemblyscript/blob/binaryen-inlining/examples/tlsf/tlsf.optimized.wast) using `-O3 --noDebug` (3, 0, false).
[ugc.ts](https://github.com/AssemblyScript/assemblyscript/blob/binaryen-inlining/examples/ugc/assembly/ugc.ts) -> [ugc.untouched.wast](https://github.com/AssemblyScript/assemblyscript/blob/binaryen-inlining/examples/ugc/ugc.untouched.wast) -> [ugc.optimized.wast](https://github.com/AssemblyScript/assemblyscript/blob/binaryen-inlining/examples/ugc/ugc.optimized.wast) again using `-O3 --noDebug` (3, 0, false).

**Pull request merged**
