### PR TITLE
[Strings] Emit unreachable when a string instruction cannot be emitted properly

### PR DESCRIPTION
**Pull request by kripken**
See https://github.com/WebAssembly/stringref/issues/66

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Possibly worth doing this in the printer as well for consistency. WDYT?

**Comment by kripken** [comment]
Hmm, I think it might be best not to. We print an unreachable for text when we have to, like `struct.get` of a bottom type, because we have no way to print the immediate in a valid way. But here we can emit the instruction, which means it will round-trip, and more closely reflects the IR, which seems useful?

**Comment by tlively** [comment]
I guess so, but we'd have to fix it anyway if not for the spec bug that there is no annotation. I'm half tempted to say we should just add the annotation and pretend the spec bug has already been fixed, but that sounds like more trouble than it's worth.

Anyway, I don't feel too strongly about it.

**Comment by kripken** [comment]
I see. Yeah, if the spec gets changed we'd need to do this. Anyhow, for now this is just more convenient (both less work and more roundtripping).

**Pull request merged**
