### PR TITLE
[Experiment] Try to fix ExpressionAnalyser for AS

### PR DESCRIPTION
**Pull request by MaxGraey**
See: https://github.com/WebAssembly/binaryen/pull/3332/files#r521353910

### CODE REVIEW

**Comment by MaxGraey** [comment]
@aheejin unfortunately this doesn't help. Or I miss something?

**Comment by aheejin** [comment]
Oh no, I was just guessing in the first place, because this was one thing I know that changed in that PR. Nevermind.

**Comment by MaxGraey** [comment]
> Oh no, I was just guessing in the first place, because this was one thing I know that changed in that PR. Nevermind and sorry!

Do not need to apologizes! I'm glad for any clue now) Perhaps you have any other ideas what could have changed since that refactoring?

**Comment by aheejin** [comment]
I have no idea, sorry. A reduced (or even unreduced) test case and the command line that reproduces the bug would be helpful. Or you can maybe read hashing code before and after #3332 for those expressions that occur in your problematic test cases, if your test case functions are small enough...

**Comment by kripken** [comment]
Another option is to add logging to print out the functions duplicate function elimination removes, and their contents. Comparing that output between a build before and after could narrow it down, assuming that pass is where the difference is.

**Pull request closed without merging**
