### PR TITLE
finalize: remove initializers from metadata output

### PR DESCRIPTION
**Pull request by sbc100**
See https://github.com/emscripten-core/emscripten/pull/13213

### CODE REVIEW

**Comment by kripken** [comment]
Don't we want to know if there is the initializer function, or not, or does LLVM always emit it, even when not needed?

(linked PR number looks wrong in the first comment?)

**Comment by sbc100** [comment]
Fixed linked PR: https://github.com/emscripten-core/emscripten/pull/13213

As you can see emscripten no longer reads this key in the output metadata.

**Comment by sbc100** [comment]
The code both here an emscripten treats the export as optional.   I'm can't remember if the linker ever actually removes it, but this code and the code in emscripten treat it as optional.

**Review by kripken — APPROVED** [review]
I see, sgtm.

We may want to add an optimization to remove the call from JS to an empty initializer, at some point.

**Comment by sbc100** [comment]
> I see, sgtm.
> 
> We may want to add an optimization to remove the call from JS to an empty initializer, at some point.

It looks like this is already the case.  Testing locally shows that Oz and O3 both completely remove this function from the JS and from the wasm.

**Pull request merged**
