### PR TITLE
Fix interpretation of `return_call*`

### PR DESCRIPTION
**Pull request by tlively**
We previously interpreted return calls as calls followed by returns, but that is
not correct both because it grows the size of the execution stack and because it
runs the called functions in the wrong context, which can be observable in the
case of exception handling.

Update the interpreter to handle return calls correctly by adding a new
`RETURN_CALL_FLOW` that behaves like a return, but carries the arguments and
reference to the return-callee rather than normal return values.
`callFunctionInternal` is updated to intercept this flow and call return-called
functions in a loop until a function returns with some other kind of flow.

Pull in the upstream spec tests return_call.wast, return_call_indirect.wast, and
return_call_ref.wast with light editing so that we parse and validate them
successfully.

### CODE REVIEW

**Comment by tlively** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/6451?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#6451** <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/6451?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#6448** <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/6448?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tlively and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by kripken** [comment]
I'll try to find time to review this later today, but I suggest that we merge this PR with the Inlining PR. Landing them as a single commit will avoid future bisection problems. (Otherwise, imagine someone bisects a testcase that involves `return_call` and inlining as incidental details, then when bisection includes only the inlining fix the testcase could break because of the inlining/interpreter discrepancy.)

**Comment by tlively** [comment]
Sounds good. We can merge this PR into the previous PR first once they're both ready to go.

**Review by kripken — COMMENTED** [review]
Code lgtm, but where in the tests is the difference noticeable? I was expecting to see a thrown exception somewhere.

**Comment by tlively** [comment]
The only noticeable difference in the tests is that we can recursively tail-call functions like `even` and `count` without encountering the function depth limit.

I can add an explicit test for the EH case if you want.

**Comment by kripken** [comment]
Yes, I think an explicit test is worth it here.

**Comment by tlively** [comment]
Done, PTAL.

**Review by kripken — APPROVED** [review]

**Comment by tlively** [comment]
Heh, looks like that test uncovered a bug in the optimizer. Will investigate.

**Comment by tlively** [comment]
It turns out I was wrong about that cast to block, so I replaced that with a `blockify()` in the last commit. Meanwhile the fuzzer has found that wasm-ctor-eval needs updating to handling the new `RETURN_CALL_FLOW` correctly, so I'm taking a look at adding proper support for tail calls there.

**Pull request merged**
