### PR TITLE
[NFC] Rename GlobalSubtyping => HeapRefining

### PR DESCRIPTION
**Pull request by kripken**
This pass specializes fields in heap types, so "heap subtyping" seems better.
Especially since I just realized we actually need a pass that does subtyping
on globals, which would rightly deserve the name "global subtyping" to
parallel "local subtyping" etc.

### CODE REVIEW

**Review by tlively — APPROVED** [review]
While we're considering a name change, what do you think of `HeapTypeRefining`?

**Comment by kripken** [comment]
I don't feel strongly. Why do you prefer that?

From my side, "HeapSubtyping" seems reasonable as applying subtypes to heap type fields is literally what it does. I agree HeapType could be more explicit than Heap, but I don't think there's ambiguity personally.

**Comment by tlively** [comment]
I'm more interested in the "refining" part, since that seems like a more descriptive verb than "subtyping." I usually don't use "subtyping" as a verb, but if I do, it's to point out a relationship between two types, e.g. "A subtypes B". In contrast, "refining" describes the transformation that pass is doing, i.e. making the types more specific.

**Comment by kripken** [comment]
I see. To me the difference isn't obvious but I'm not a native speaker so HeapRefining sgtm.

**Comment by tlively** [comment]
I would prefer `TypeRefining` or `HeapTypeRefining` over `HeapRefining`, since it's the types that get refined rather than the heap.

**Comment by kripken** [comment]
Oh sorry, I thought we'd agreed on the final name so I did automerge... will open another PR.

**Pull request merged**
