### PR TITLE
Use standard GC encodings by default

### PR DESCRIPTION
**Pull request by tlively**
The legacy encodings remain available for now by defining
USE_LEGACY_GC_ENCODINGS at build time.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5873** <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/5873" target="_blank">Graphite</a>  👈
    * **PR #5874** <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/5874" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/WebAssembly/binaryen/5873?utm_source=stack-comment).

**Comment by tlively** [comment]
This is meant to be landed immediately after the GC proposal goes to phase 4. A vote to promote it to phase 4 is currently scheduled for September 12.

**Review by kripken — APPROVED** [review]

**Comment by bashor** [comment]
Please also make a new release after the merge.

**Comment by tlively** [comment]
@bashor, we will make a release by the end of the week, if that's ok for you. It would be good to get as many text format cleanups into the release as possible.

**Comment by bashor** [comment]
@tlively, it would be nice to have a release as soon as possible since binaryen is one of the dependencies we need to update. We don't use binaryen's text format support.

**Comment by bashor** [comment]
@tlively any news?

**Comment by tlively** [comment]
I've just created the release now. CI is currently working on producing the build artifacts for it.

**Comment by bashor** [comment]
Great! Thanks a lot!

**Pull request merged**
