### PR TITLE
Update tests for upstream changes.

### PR DESCRIPTION
**Pull request by sunfishcode**
This updates the tests according to the changes in http://reviews.llvm.org/D16105 .

### CODE REVIEW

**Comment by kripken** [comment]
Also need to update the `.s` files in `tests/dot_s`.

**Comment by kripken** [comment]
I pushed a commit that updates s2wasm. It also updates the `llvm_autogenerated` tests, and the output looks correct to me, so I think this implements what we need here.

Still to do: update `dot_s/` (which I'd rather not do as I'm sure i'll make mistakes) and the torture tests (not sure how we coordinate that).

**Comment by sunfishcode** [comment]
dot_s tests are now updated. The guidance I got from JF for these kinds of changes is to just check them in and let the tests fail, and then run update.py once new generated tests are available.

**Comment by jfbastien** [comment]
Yes, this should all be simpler once I move all the file updates to the same waterfall-based `update.py` mechanism. As long as we're all OK with temporary breakage while @sunfishcode juggle knives then we're fine, the breakage should be very short lived and nobody should lose fingers.

**Comment by kripken** [comment]
Sounds good. I added an option to run check.py without the torture tests, which is useful locally to see nothing else is broken.

Perhaps we should actually default to disabling torture, until they are fixed? Then travis will pass.

Otherwise this looks good to land to me. Unless someone wants to look over my commits here first.

**Comment by sunfishcode** [comment]
I briefly looked at the changes; getNextLabel is pretty much what I was imagining binaryen would want to do. Note that this should fix issues that have popped up in a few places where a loop and a block end at the same place and previously would share a label.

**Comment by kripken** [comment]
Yeah, there was a hack for shared labels, it's removed in that commit.

**Pull request merged**
