### PR TITLE
#582 + additions

### PR DESCRIPTION
**Pull request by kripken**
Since #582 seems important to merge, I made this branch which contains your changes @juj, plus

1. Removing the c++ example test, which as discussed in that PR we don't really need,
2. Fix memory leak of the registered passes
3. Remove the `wasm::` prefix stuff that I asked about in that PR and seems irrelevant. Was it there by mistake? If not, let's do it in a followup.

### CODE REVIEW

**Comment by kripken** [comment]
Also 4) remove the linking hacks we don't need anymore now that passes are registered explicitly

**Comment by juj** [comment]
The `wasm::` namespace is not there by mistake, the project fails to compile in VS2015 without it in a VS error that `make_shared` is ambiguous and don't know how to resolve to either `std::make_shared` or `wasm::make_shared`.

**Comment by kripken** [comment]
`make_shared` is a c++14 feature - does VS enable it by default? Maybe the fix could be to set c++11 for VS like we do for unix (with `-std=c++11`) - looks like we don't tell VS the C++ version currently?

**Comment by juj** [comment]
err, meant `make_unique` above and not `make_shared`. VS2015 does have `std::make_unique`, but it finds it conflicting with `wasm::make_unique`. The exact error is

	1>C:\code\binaryen\src\tools\binaryen-shell.cpp(204): error C2668: 'wasm::make_unique': ambiguous call to overloaded function
	1>  c:\code\binaryen\src\support/utilities.h(56): note: could be 'std::unique_ptr<wasm::Output,std::default_delete<_Ty>> wasm::make_unique<wasm::Output,std::basic_string<char,std::char_traits<char>,std::allocator<char>>&,wasm::Flags::BinaryOption,wasm::Flags::DebugOption>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &,wasm::Flags::BinaryOption &&,wasm::Flags::DebugOption &&)'
	1>          with
	1>          [
	1>              _Ty=wasm::Output
	1>          ]
	1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1628): note: or       'std::unique_ptr<wasm::Output,std::default_delete<_Ty>> std::make_unique<wasm::Output,std::basic_string<char,std::char_traits<char>,std::allocator<char>>&,wasm::Flags::BinaryOption,wasm::Flags::DebugOption>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &,wasm::Flags::BinaryOption &&,wasm::Flags::DebugOption &&)' [found using argument-dependent lookup]
	1>          with
	1>          [
	1>              _Ty=wasm::Output
	1>          ]
	1>  C:\code\binaryen\src\tools\binaryen-shell.cpp(204): note: while trying to match the argument list '(std::basic_string<char,std::char_traits<char>,std::allocator<char>>, wasm::Flags::BinaryOption, wasm::Flags::DebugOption)'

**Comment by juj** [comment]
In above, VS2015 does say "[found using argument-dependent lookup]". I'm not sure if there is an explicit ambiguity clause saying if ADL lookup vs non-ADL lookup are treated the same, or if one should be ignored if the other one is matched, but to me VS2015 is correct here, the first param is a `std::map`, so it'd look in `std::make_unique`, and there's `using namespace wasm;` in the file, which would bring `wasm::make_unique` in as well.

**Comment by kripken** [comment]
Sure, but as I said above, `make_unique` is c++14 and we are a c++11 project. Can we tell VS to do only c++11, as we do for unix?

**Comment by jasonwilliams200OK** [comment]
> using namespace

There is an excellent thread about this being a bad practice: http://stackoverflow.com/q/1452721.

> Can we tell VS to do only c++11, as we do for unix?

Old way: https://msdn.microsoft.com/en-us/library/ff770576.aspx (requires older VS toolset to be installed)

New feature introduced in VS2015 Update 3: https://blogs.msdn.microsoft.com/vcblog/2016/06/07/standards-version-switches-in-the-compiler/ (which only supports /std:c++14 and /std:c++latest but not the down-versions.

---

My opinion is to get rid of "using namespace".

**Comment by kripken** [comment]
I agree limiting `use namespace` is good. We avoid it entirely for `std` for that reason (which is one reason I'm surprised this problem happens on VS), and really just use it for our own namespace `wasm`.

Thanks for those flags. @juj, what do you think, can we use those, should fix this problem?

**Comment by juj** [comment]
Those flags don't fix the issue, as there is no /std:c++11. I think the simplest fix would be to just add the `wasm::` in the few places like I did in my PR, or alternatively rename `wasm::make_unique` to something else. 

Alternatively, I could remove `using namespace wasm;` just in `binaryen-shell.cpp`, but that will result in 143 added explicit `wasm::` qualifications in `binaryen-shell.cpp`, as opposed to the four cases that #582 adds. (actually the build issue occurs on only one of those four lines, but added them all for consistency)

**Comment by kripken** [comment]
Well, first I'd like to understand the issue. It seems like the ambiguity requires VS to do two things:

1. Enable c++14
2. Do the equivalent of `using namespace std`

Without 1, there is no `make_unique` in `std`, and without 2 it isn't in the global namespace. Does VS just have two bugs here?

If yes, then we should work around it. Options are

1. Your `wasm::` additions
2. Add a `namespace wasm { .. }` scope around all the code in that file (might need to keep just a stub `main()` outside).

The latter seems simpler to me.

**Comment by juj** [comment]
Yes, VS2013 and VS2015 both unconditionally compile code with the `std::make_unique` function enabled, i.e. in C++14 mode with this respect. That function is not in global namespace, but due to argument-dependent lookup (ADL or Koenig lookup), it pulls it from within `std::` since a parameter to that function is in the `std::` namespace (`std::map` in this case).

Wrapping the code inside `namespace wasm` does not fix the issue, since the root problem for that code remains, that an unqualified `make_unique` can either mean `wasm::make_unique` (since we're inside the namespace), or `std::make_unique` (due to ADL). I think the options are either to explicitly qualify with `wasm::` or rename.

**Comment by kripken** [comment]
Ok, thanks. Let's qualify with `wasm::make_unique` then.

Unless there's a way for our header (`src/support/utilities.h`) to detect `std::make_unique` exists and use that, and only declare ours if necessary? Probably not though.

**Pull request merged**
