### PR TITLE
Fix table exporting

### PR DESCRIPTION
**Pull request by kripken**
This code was apparently not updated when we added multi-table support,
and still had the old hardcoded index 0.

Fixes https://github.com/WebAssembly/binaryen/issues/4711

### CODE REVIEW

**Review by tlively — APPROVED** [review]
How did you find this?

**Comment by kripken** [comment]
> How did you find this?

I reduced the testcase in the linked issue until it was obvious from reading the diff after roundtripping. And since the bug only happens in the binary format, and just during writing, I read that code and got a surprise :smile:

**Comment by torokati44** [comment]
Are there any estimates for the date of the next release, with this fix in it?

**Comment by kripken** [comment]
@torokati44 I released version 110 now, https://github.com/WebAssembly/binaryen/releases/tag/version_110 (builds still running)

**Comment by torokati44** [comment]
Wow, that was quick! Thank you so much! We won't have to build for ourselves in CI now.

**Pull request merged**
