### PR TITLE
Rename $discard to $drop in the .s syntax.

### PR DESCRIPTION
**Pull request by sunfishcode**
This is shorter and is more consistent with terminology being used to discuss WebAssembly.

If this is ok, I have a corresponding patch to LLVM which I can land when this lands.

### CODE REVIEW

**Comment by sunfishcode** [comment]
I should also add, this didn't require any actual s2wasm change because s2wasm just accepts anything beginning with 'd', so it accepts either "discard" or "drop". The patch here just updates the tests.

**Comment by jfbastien** [comment]
lgtm

**Comment by kripken** [comment]
> this didn't require any actual s2wasm change because s2wasm just accepts anything beginning with 'd', so it accepts either "discard" or "drop".

The very definition of "feature, not a bug".

**Comment by jfbastien** [comment]
>> this didn't require any actual s2wasm change because s2wasm just accepts anything beginning with 'd', so it accepts either "discard" or "drop".

> The very definition of "feature, not a bug".

I think your account has been hacked by 🐎.wasm

:stuck_out_tongue:

**Comment by sunfishcode** [comment]
Ok, let's do this.

**Comment by kripken** [comment]
The tests failed, though? Or was that expected?

**Comment by sunfishcode** [comment]
We have to update everything to match.

**Comment by kripken** [comment]
1. Didn't you just explain that things would still pass here as we accept both drop and discard?
2. The errors don't look like drop/discard errors, they look like something else? Namely they look like a bad line at the end, maybe the build you made the update with was before the recent whitespace change we made at your suggestion?

**Comment by sunfishcode** [comment]
Oh, oops. I misread what was going on there.

I've now created https://github.com/WebAssembly/binaryen/pull/521 to fix this.

**Pull request merged**
