### PR TITLE
More tests for wasm backend

### PR DESCRIPTION
**Pull request by kripken**
We should be able to do some full tests now, no limitations like just `-O1` or `ONLY_MY_CODE`.

### CODE REVIEW

**Comment by dschuff** [comment]
This looks fine. Slightly unrelated but when I try to do builds with my vanilla LLVM, I'm getting errors at wasm instantiation time that a couple of functions (specifically pthread_self and friends) are undefined. They are in the JS module but with the leading underscores. Which part is supposed to fix that up?

**Comment by kripken** [comment]
`fixImports` in `integrateWasmJS` in `src/js/wasm.js-post.js` should do that, I think.

**Comment by kripken** [comment]
Hmm, still seeing a local error when I enable the new tests in this pull. Investigating.

**Comment by kripken** [comment]
Ok, this should be good now, if travis passes.

This now adds a bunch of wasm backend tests using full libc normally, in `-O0` and `-O2`. It still keeps the old `-O1 -s ONLY_MY_CODE=1` hack that was useful when we couldn't build libc. The existing tests are pretty slim (intentionally, since we couldn't do much more) so I also added a full hello world with printf, that now passes.

At this point, it might be useful to start running parts of the emscripten test suite directly, which we can do since it's a submodule here, to avoid duplication. Perhaps a whitelist of what is known to pass there?

**Pull request merged**
