### PR TITLE
Fix CMake on CI (see #4575, #4576)

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Comment by kripken** [comment]
Does not seem to help to build with gcc...

**Comment by kripken** [comment]
Well, I have no idea what's going on here, but through a "clever" method of just bisecting on differences between working and failing builds, apparently we need some extra incantation in the cmake now, which we did not need just a day ago. cmake update perhaps?

The magic:
```
-DCMAKE_INSTALL_PREFIX=out/install
``` 
Note that we don't even do `make install` in these jobs, so it's quite bizarre. But the jobs seem to start passing now..

download

**Review by tlively — APPROVED** [review]
Well that's a strange one! Thanks for tracking it down.

**Comment by dschuff** [comment]
Interesting. what specifically was the error you saw that was fixed by this (or a link to the relevant build? I i clicked a few above but there were several different kinds of errors)

**Comment by kripken** [comment]
error was
```
/home/runner/work/binaryen/binaryen/out/bin/wasm-as: error while loading shared libraries: libbinaryen.so: cannot open shared object file: No such file or directory
```

**Comment by kripken** [comment]
https://github.com/WebAssembly/binaryen/runs/5825162539?check_suite_focus=true

**Pull request merged**
