### PR TITLE
Fix typo in --finalize-table-base short name to -ftb

### PR DESCRIPTION
**Pull request by winksaville**

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, looks good. Have you joined the [community group](https://www.w3.org/community/webassembly/participants)?

**Comment by winksaville** [comment]
I've created an account, https://www.w3.org/users/99047

**Comment by kripken** [comment]
Thanks! Ok, last issue is the failure on travis. I think that's just old breakage we had. If you merge current master in to this branch, it should fix it.

**Comment by winksaville** [comment]
I'll rebase, do you want me to push the rebased version?

**Comment by winksaville** [comment]
I rebased locally and ran ./check.py and it appeared to work, there was a `[ success! ]` although some tests didn't run:
```
binaryen method succeeded.
..../home/wink/foss/emscripten/emcc -o a.wasm.js -s BINARYEN=1 /home/wink/prgs/binaryen/test/printf.c -Oz -s BINARYEN_METHOD="interpret-binary" -s BINARYEN_TRAP_MODE="js"
     (no post)
...... wasm
     (no args)
executing:  /usr/bin/node a.wasm.js
trying binaryen method: interpret-binary
binaryen method succeeded.

[ success! ]

could not run vanilla LLVM from waterfall: Command '['/home/wink/prgs/binaryen/test/wasm-install/wasm-install/bin/clang', '-v']' returned non-zero exit status 127, looked for clang at /home/wink/prgs/binaryen/test/wasm-install/wasm-install/bin/clang
no mozjs found (did not check native wasm support nor asm.js validation)
no interpreter provided (did not test spec interpreter validation)
````
I then forced push to my fork:
```
git push --force origin fix-typo-in--finalize-table-base-short-name-to-ftb
```

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
