### PR TITLE
Initial start on CMakeLists.txt.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is not yet complete as it doesn't perform the emscripten
build stage, nor does it attempt to run tests.

This is work in progress on issue #2.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
If this lands, then we can improve it further ... like cleaning up the source directory structure and having multiple `CMakeLists.txt` files as is more typical.

I've built with this on Mac OS X with Ninja, but haven't done anything really with the build products.

**Comment by kripken** [comment]
Nice to see this start :)

Latest Ubuntu LTS has cmake 2.8.12.2, but this file requires 3.0. Could we support that lower version?

**Comment by waywardmonkeys** [comment]
It would probably work with 2.8.12 and if not, can be made to do so. I just have 3.4 handy here so was conservative.

Try it out!

**Comment by kripken** [comment]
Ok, cmake runs properly. Running make, it fails on not having `-std=c++11` in the command args, I'm not familiar enough with cmake to know where to add that.

Should we merge this in and iterate, or keep working on this pull? I'm fine either way (if we merge, I'll add a note to the readme that cmake is wip).

**Comment by waywardmonkeys** [comment]
merge and iterate ... It worked for me having ``-std=c++11`` in the args ... so that must be a later feature that I was using.

I'm going to be traveling for about 30 hours, starting in about 5 hours.

**Comment by kripken** [comment]
Cool, merging.

**Pull request merged**
