### PR TITLE
Fix AngryBots parsing

### PR DESCRIPTION
**Pull request by kripken**
I noticed we can't parse the latest AngryBots, I guess due to it being old-style in various ways and updated for each version in a special way, instead of emitted they way we expect. This fixes that, it was two tiny issues.

### CODE REVIEW

**Comment by kripken** [comment]
Turns out there is stacky/non-ast code in there, so I added support for that too.

**Comment by dschuff** [comment]
Can we split out the break-to-return and global stuff from the stacky-code stuff? They seem unrelated, and the stacky-code seems like it should get its own PR with a noticeable title, at least.

**Comment by kripken** [comment]
Sure, I opened #868. This is now rebased on that (so it must land later).

**Comment by kripken** [comment]
Rebased after the PR we depend on landed.

**Comment by kripken** [comment]
This should be good to land if there are no comments.

**Comment by dschuff** [comment]
I thought we already had an implicit block on the function? so does that mean we create another (explicit) one for this case? Is there some way we can break to that instead?

**Comment by kripken** [comment]
We don't create an unnecessary block in that case: `blockifyWithName` is smart enough to just add a name if the input is already a block without a name (and that would be the case here, as the function body is generated by `getMaybeBlock` which creates a block if there are multiple statements, but does not name it). So if we already created an explicit block, we reuse it, and if not, then we create one.

**Comment by kripken** [comment]
If there are no more concerns, I can land this?

**Comment by dschuff** [comment]
Sure, go ahead.

**Pull request merged**
