### PR TITLE
[C API] Add BinaryenGetGlobalIndex method

### PR DESCRIPTION
**Pull request by ApsarasX**

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
Comparing to functions, we have `GetFunction` for the name and `GetFunctionByIndex` for the index. So I think we don't need `ByName` here, that is the default.

**Comment by kripken** [comment]
Also this should add some testing (probably in `test/example/kitchen-sink` alongside similar methods.

**Comment by dcodeIO** [comment]
I also think that `BinaryenGetGlobalIndexByName` might not be necessary. There are both `BinaryenGetGlobal` (by name) and `BinaryenGetGlobalByIndex` already, where the latter is typically used along `BinaryenGetNumGlobals` to iterate. Seems risky to depend on the index otherwise?

**Comment by kripken** [comment]
@dcodeIO Good point, yes, it does seem like GetGlobalIndex could be implemented using the existing APIs (do a loop on the number of globals, get name by index, return if it's that one). I tend to agree that we don't need a new API, then. @ApsarasX does that make sense, or are we missing something?

**Comment by ApsarasX** [comment]
@kripken You are right, I will close this PR.

**Pull request closed without merging**
