### PR TITLE
s2wasm: support aliased functions

### PR DESCRIPTION
**Pull request by jfbastien**

### CODE REVIEW

**Comment by kripken** [comment]
Do we need this? Shouldn't aliases be resolved by the backend already?

**Comment by jfbastien** [comment]
I'm doing bitcode linking of multiple files, which doesn't resolve the aliases. Maybe in the long-term we won't want them, but I definitely need it now and it's valid .s syntax so it seems useful.

**Comment by kripken** [comment]
I guess I'm not clear on if this is something we intend to have forever in the `.s` format? cc @sunfishcode

**Comment by jfbastien** [comment]
Ugh, I inadvertently merged this while trying to get #149 in... Sorry about that we can revert and / or fix separately.

**Comment by kripken** [comment]
I guess that's ok. Still waiting on @sunfishcode to hear what the plan for aliases in the `.s` format is.

**Comment by jfbastien** [comment]
Closing for now since it's in. We can discuss further and I'll fix things as a follow up.

**Comment by sunfishcode** [comment]
It's a standard feature of .s syntaxes in general, so my default assumption is we should support it too. Ordinarily aliases would be resolved by linking, and since s2wasm is effectively performing a linking function, there is some logic of having it support them. Does this cause any trouble?

**Comment by kripken** [comment]
No problem, just wanted to hear what you just said.

**Comment by jfbastien** [comment]
OK so we're good with the change as is? Seems to do the right thing :-)

**Comment by kripken** [comment]
Yes, patch looks good.

**Pull request closed without merging**
