### PR TITLE
feat!: add support for BinaryenArrayNewData

### PR DESCRIPTION
**Pull request by ericvergnaud**

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Fixes #5270

**Review by kripken — COMMENTED** [review]
Looks like we test this in `test/example/c-api-kitchen-sink.c` (I grepped for `BinaryenArrayNewFixed` under `test/`), please add a case with this there.

**Comment by ericvergnaud** [comment]
Done, but the workflow is blocked, so not sure if the test succeeds

**Comment by kripken** [comment]
I ran the workflow here. But it will be faster to debug locally, which you can do with `./check.py example`.

**Comment by ericvergnaud** [comment]
@kripken done, hopefully my last push will fix all failures

**Comment by ericvergnaud** [comment]
btw is there a way to build the binaryen wasm module with dwarf attached such that I can understand the failing assertions (when using validate on a "manually" built module) ?

**Comment by kripken** [comment]
I think making a debug build should be enough. So something like `emcmake cmake -DCMAKE_BUILD_TYPE=Debug [..]`

**Review by kripken — APPROVED** [review]

**Comment by ericvergnaud** [comment]
A debug build definitely provides a lot more info. Looks like dwarf is embedded, but unfortunately it's not used by my debugger (it works with map files)...

**Pull request merged**
