### PR TITLE
De-inline signed wrapper templates for bit manipulation functions

### PR DESCRIPTION
**Pull request by dschuff**
This fixes the clang build.

### CODE REVIEW

**Comment by dschuff** [comment]
Merging based on IRC lgtm

**Comment by kripken** [comment]
lgtm to merge this for now. but i have no idea what's going on here :)

**Comment by dschuff** [comment]
Yeah, I'm a little fuzzy myself. I can't see offhand any reason why inlining it should make any difference.

**Comment by kripken** [comment]
cc @jfbastien and @sunfishcode who maybe can figure this 1337 c++ stuff out out

**Comment by jfbastien** [comment]
What was the failure? You technically can't put non-inline functions in a header file.

**Comment by binji** [comment]
From the IRC log:
```
15:54 < binji_> dschuff: weird, what was the error?
...
15:56 < dschuff> binji_: miscompile of the clz/ctz imlementation
15:57 < dschuff> that returned 0 instead of 32 when given an input of 0
16:00 < binji_> strange
```

**Comment by dschuff** [comment]
@jfbastien If they are templates, don't they just get put into a comdat?

**Pull request merged**
