### PR TITLE
Tables and memories

### PR DESCRIPTION
**Pull request by kripken**
For https://github.com/WebAssembly/spec/pull/316/

This is the best I can do for now, as we are skipping ahead to the `stack` branch (as I was convinced not to try to model the `drop` type system changes), so this adds parsing and support but still runs the old spec tests, i.e., it should work on both old and new syntax, but is untested on the new (as those tests contain `drop` etc.). I did have to temporarily disable one spec test.

### CODE REVIEW

**Comment by qwertie** [comment]
Er... what's that about not modelling the `drop` type system changes?

**Comment by kripken** [comment]
See https://github.com/WebAssembly/design/issues/736 and in particular https://github.com/WebAssembly/design/issues/736#issuecomment-236727305 and https://github.com/WebAssembly/design/issues/736#issuecomment-236964205

**Comment by kripken** [comment]
This is now good to go if anyone wants to review, I added table element offset support too.

**Comment by rossberg-chromium** [comment]
Sorry about that. I'm actually in the midst of a merge fest with rebasing the spec's `stack` branch onto the landed table changes. Should be complete soon.

**Comment by rossberg-chromium** [comment]
Okay, everything is merged into the `stack` branch now.

**Comment by kripken** [comment]
Thanks @rossberg-chromium.

**Pull request merged**
