### PR TITLE
feat(release): add OSX binary to CI GitHub releases

### LINKED ISSUE #1695: Windows and OSX binary releases
Hi! I work on [`wasm-pack`](https://github.com/rustwasm/wasm-pack), an integrated build tool for rust->wasm projects and we are currently looking to integrate `wasm-opt` into the tool. Based on the current status of the APIs here, I think we'd like to download a binary of the tool and run it in a child process. I see that you have a bunch of release binaries on GitHub, but notably don't have ones for MacOS or Windows, which are 2 of `wasm-pack`s most heavily used OSes. Would you be willing to produce those as well? Let me know if you have any questions or if there's any way I can help!

cc @fitzgen

### PR DESCRIPTION
**Pull request by ashleygwilliams**
🙅‍♂️ do not merge 🙅‍♂️ 

fixes #1695

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hrm. travis isn't running on this so this isn't gonna get tested. lemme look and see why- if you have any thoughts @kripken ... feel free to chime in!

**Comment by fitzgen** [comment]
@ashleygwilliams is this generally good to merge? Does it still need to be "WIP"? Did you see @kripken's question about determining whether we are expecting to see differences in the travis build now (or only once there is a new tagged release?)

Thanks!

**Comment by alexcrichton** [comment]
A bit of a delayed response, but FWIW this looks good to go to me!

**Comment by ashleygwilliams** [comment]
whoops! sorry for the delay, i forgot that this had a WIP on it. i think it should be ready to go. 

@kripken - i don't *expect* that this *should* do anything beyond adding an OSX release.

**Comment by kripken** [comment]
Cool, thanks @ashleygwilliams! Let's land this then.

**Comment by kripken** [comment]
This [broke our CI](https://travis-ci.org/WebAssembly/binaryen/jobs/508031084):

```
-- Generating done
-- Build files have been written to: /Users/travis/build/WebAssembly/binaryen
Scanning dependencies of target wasm
[  1%] Building CXX object src/wasm/CMakeFiles/wasm.dir/literal.cpp.o
In file included from /Users/travis/build/WebAssembly/binaryen/src/wasm/literal.cpp:17:
/Users/travis/build/WebAssembly/binaryen/src/literal.h:21:10: fatal error: 'array' file not found
#include <array>
         ^~~~~~~
1 error generated.
make[2]: *** [src/wasm/CMakeFiles/wasm.dir/literal.cpp.o] Error 1
make[1]: *** [src/wasm/CMakeFiles/wasm.dir/all] Error 2
make: *** [all] Error 2
```

I don't know much about MacOS - does the C++ STL need some special handling on MacOS?

**Comment by alexcrichton** [comment]
That may have to do with the macosx_deployment_target I think? I can send a pr tmw to try to debug

**Pull request merged**
