### PR TITLE
document that binaryen text is not valid wasm text, but stack IR is [ci skip]

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Btw, is it possible to emit stack IR with the current C-/ JS-API?

**Comment by kripken** [comment]
I think so, using `BinaryenModuleRunPasses`, can give it those passes (and capture stdout).

**Comment by dcodeIO** [comment]
Hmm, looks like it isn't as easy anymore to intercept stdout. What do you think about adding an option, for example on `Module#emitText` or alternatively something like `Module#preferStackIR(bool)`, that indicates whether to output stack ir?

**Comment by kripken** [comment]
A JS API option sounds good. How about a new function, `emitStackIR`? Internally in `src/js/binaryen.js-post.js` it can intercept `out` like `emitText` and `emitAsmjs` do.

**Comment by dcodeIO** [comment]
Yeah, sounds good!

**Pull request merged**
