### PR TITLE
Fixes typo in hex number parsing in asm2wasm.

### LINKED ISSUE #352: HEX number conversion is wrong asm2wasm
```js
function asmFunc(global, env, buffer) {
  'use asm';
  function test () {
    var res = 0;
    res = (127 + 0x7F) | 0;
    return res;
  }
}
```
```
asm2wasm test.js > test.wast
```
```lisp
(module
  (memory 256 256)
  (export "memory" memory)
  (func $test (result i32)
    (return
      (i32.add
        (i32.const 127)
        (i32.const 122)   <= ???
      )
    )
  )
)
```

Looks like:
`0x7F` -> 122
`0x7f` -> 127

### PR DESCRIPTION
**Pull request by yurydelendik**
Fixes #352 ?

### CODE REVIEW

**Comment by kripken** [comment]
Heh, nice, funny this wasn't noticed before!

Can you please add a little testing, maybe just modify a single number in one of `test/*.asm.js` to use capital hex format?

**Comment by drom** [comment]
Test would be good. It took me some time fixing my code and then unfixing it ;)

**Comment by yurydelendik** [comment]
test was added to test/unit.asm.js

**Comment by kripken** [comment]
Great, thanks!

**Pull request merged**
