### PR TITLE
Factor out mergeblocks optimization from select

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
@kripken  Can you try this patch? does it behave badly for you? For me it seems to send MergeBlocks into an infinite loop, but it looks really benign. So I'm probably just missing something stupid.

**Comment by kripken** [comment]
I think the issue is that `optimize()`'s second param is by reference, which is changed by the patch. Changing the `first, second, third` params to be `*&` makes it work.

**Comment by dschuff** [comment]
Gah, i knew it would be something dumb like that. I guess that's pretty much exactly why Google's style conventions all prefer passing by pointer instead of using non-const references.

**Comment by dschuff** [comment]
Closing this, I'll roll it into the atomic PR.

**Pull request closed without merging**
