### PR TITLE
Add TAGS to .gitignore

### PR DESCRIPTION
**Pull request by tlively**

### CODE REVIEW

**Comment by aheejin** [comment]
Is this tags file generated by ctags? Isn't that lowercase?

**Comment by tlively** [comment]
Yes, but mine is all uppercase. Perhaps it's different for emacs and vim modes?

**Comment by aheejin** [comment]
They maybe add both? 😂

**Comment by tlively** [comment]
Works for me!

**Comment by sbc100** [comment]
I think a better way to do this kind of thing, rather than make this change to *every* project that you  work on is to add this to a your user-global git ignore file which will then be honored by all projects:  http://egorsmirnov.me/2015/05/04/global-gitignore-file.html

**Pull request merged**
