### PR TITLE
Stack machine + 0xc update

### PR DESCRIPTION
**Pull request by kripken**
This brings in all the 0xc and stack machine stuff that are on the spec repo's `stack` branch. At this point this

 * passes the spec tests except for the new overly-stacky stuff
 * lets asm2wasm pass the emscripten test suite

So it's basically done from my point of view, and if anyone wants to review this now is a good time. However, disabled are

 * those overly-stacky tests, which I think should stay disabled as discussed in #663 
 * wasm-backend and s2wasm tests and functionality are all disabled, as the wasm backend and .s format need to be updated for all these changes. I'm ok to land this before or after that.

### CODE REVIEW

**Comment by kripken** [comment]
(commits starting with `TEMP, FIXME, WIP` can be ignored and removed before or after landing)

**Comment by kripken** [comment]
Fuzzing asm2wasm for a while also looks good.

**Comment by kripken** [comment]
There is a parallel `binaryen-stack` branch in the emscripten repo now, that is meant to work with this. When we merge this we should merge them together.

**Comment by kripken** [comment]
The last asm2wasm fixes here allow the [emterpreter](https://github.com/kripken/emscripten/wiki/Emterpreter) to run in wasm.

In polyfill testing mode, that means that our program's code is compiled into emterpreter bytecode, which is run in the emterpreter's interpreter, which is compiled from asm.js to wasm, which is run in the polyfill wasm interpreter, which is an interpreter compiled from C++ to asm.js, which is then run in a JS engine. (The meme writes itself.)

**Comment by kripken** [comment]
And objections to me cleaning this up a little and landing it?

The main downside is that the wasm backend and s2wasm stuff would all be disabled on master (since it's not updated yet for 0xc/stack). The upside is that this PR is big, and people are filing bugs on master that are already fixed (e.g. https://github.com/kripken/emscripten/issues/4531).

**Comment by kripken** [comment]
Btw, I ran csmith fuzzing on the asm2wasm path on this branch for 4 days, and found just one minor bug (when running asm2wasm itself compiled to JS, which we do for testing but users would normally run asm2wasm natively, which works ok).

**Comment by dschuff** [comment]
I think I'm almost ready for this. The waterfall has been a bit chaotic lately. Right now the standalone (non-emscripten) tests are running with a frozen version of binaryen to test v8's native wasm mode, so they won't be affected. I'm about to land https://reviews.llvm.org/D24053 which fixes several tests. Currently though the emscripten build on the waterfall is actually broken because of the build warning that @aheejin reported in https://github.com/kripken/emscripten/pull/4501. So maybe we should fix that and get it building again before landing this? Shouldn't be too hard, I'll look into it.

**Comment by kripken** [comment]
Sounds good. I commented in that issue now with one possible quick fix.

**Comment by kripken** [comment]
Rebased, cleaned up a little, and re-enabled spec tests on latest upstream `stack` branch. This is good to land whenever you are ready.

**Comment by kripken** [comment]
Spec repo now has a [PR with the new import/export stuff](https://github.com/WebAssembly/spec/pull/324/files#diff-ee1769ecbe9d6c631a7292399308156c) with a concrete syntax, which differs from the temporary one I guessed here. Added a commit for imports now.

**Comment by kripken** [comment]
@dschuff, ping - are you ok with this landing?

Meanwhile I did some more parsing work here for upcoming spec repo changes.

**Comment by dschuff** [comment]
I think so. Is it still the case that s2wasm/wasm backend is completely disabled? I guess what we have to do is just update the wasm building code in s2wasm, so that it builds the new IR?

**Comment by kripken** [comment]
Yes, in this PR that's disabled. There are the handwritten and autogenerated tests etc. that need to be fixed up, unless you've already done that?

If not, what do you think about landing this first?

**Comment by kripken** [comment]
Anyone know why appveyor keeps failing? There isn't a build to check an error on, weird.

**Comment by kripken** [comment]
@dschuff: ping - are you ok to land this? (needs a merge fix which I'll fix, and later on master we can figure out the .s/wasm-backend tests)

**Comment by dschuff** [comment]
Yeah, go ahead and land it. Thanks for the heads-up.

**Comment by kripken** [comment]
Ok, rebased and tests passed, merging.

**Pull request merged**
