### PR TITLE
Validator: Check subtyping in CallIndirect [DO NOT LAND]

### PR DESCRIPTION
**Pull request by kripken**
V8 requires this, e.g.
```wat
(module
 (rec
  (type $0 (sub (func)))
  (type $1 (sub (func)))
 )
 (type $2 (func))
 (table $0 1 1 (ref null $1))
 (func $0
  (call_indirect (type $0)
   (i32.const 0)
  )
 )
)
```
errors on
```
CompileError: WebAssembly.Module(): Compiling function #0 failed: call_indirect: Immediate signature #0 is not a subtype of immediate table #0 @+46
```

However, @tlively you wrote otherwise in a test, so I am confused:

https://github.com/WebAssembly/binaryen/blob/f6bb943490dc87b16481bfc1604a796edf2acea8/test/lit/passes/unsubtyping.wast#L525-L536

Reading the main spec, it still mentions only funcref, so it is pre-typed-function-references I guess. Reading the typed function references [spec](https://webassembly.github.io/function-references/core/valid/instructions.html#control-instructions) I only see it change the requirement from `funcref` to `ref null func`. I also cannot find anything in the overviews, so I am lost as to what the correct behavior is.

cc @jakobkummerow for the V8 behavior - am I reading that error right, and if so where in the spec is that validation rule added?

### CODE REVIEW

**Comment by kripken** [comment]
(found by fuzzing with #6327)

**Comment by tlively** [comment]
Sounds like there is a V8 bug here.

The validation rule for `call_indirect` deliberately requires that the table element type is any subtype of `ref null func`, even with typed function references and GC. This is safe because the typing and semantics of `call_indirect` are precisely equivalent to `(table.get x) (ref.cast y) (call_ref y)` and the cast will fail if the table element has an incompatible type.

The V8 error message here is extra interesting because it implies that V8 will also disallow `call_indirect` with a _supertype_ of the table element type, which is perfectly safe and wouldn't even trap.

**Comment by tlively** [comment]
I have a PR up adding spec tests for this: https://github.com/WebAssembly/gc/pull/526

**Comment by jakobkummerow** [comment]
V8-side fix in flight: [crrev.com/c/5319505](https://chromium-review.googlesource.com/c/v8/v8/+/5319505)

**Comment by kripken** [comment]
Great, thanks @jakobkummerow , let's close this PR then.

**Pull request closed without merging**
