### PR TITLE
LLVM is now emitting private labels with a ".L" prefix. Update binaryen.

### PR DESCRIPTION
**Pull request by sunfishcode**
The .L prefix convention is admittedly not the prettiest convention
possible, but it is widely used in the ELF ecosystem.

### CODE REVIEW

**Comment by jfbastien** [comment]
Was this created with `./update.py`? It should update `lkgr` as well, otherwise the files aren't reproducible.

**Comment by sunfishcode** [comment]
We need a lock-step change to both LLVM and binaryen here, and it's not clear to me how to get everything updated appropriately. I hoped I could just update the tests manually at the same time, and things would sort themselves out.

**Comment by jfbastien** [comment]
The waterfall is currently broken because of the wasmate breakage, which is unrelated to this change (caused by the previous commit). I'm almost done removing it, and the waterfall should turn green after this.

I guess for now a manual update is fine, but I'd really like to avoid doing this in the future.

**Comment by kripken** [comment]
lgtm. there is a merge conflict, though.

@jfbastien , should we wait to merge this for that bot update?

**Comment by jfbastien** [comment]
It can be merged now, as the bot is currently red. Once this is checked in the bot will turn green and `update.py` should be able to update lkgr.

**Comment by kripken** [comment]
Merged.

**Pull request merged**
