### PR TITLE
Postorder

### PR DESCRIPTION
**Pull request by kripken**
This switches the binary format to postorder, as was decided.

### CODE REVIEW

**Comment by jfbastien** [comment]
We should only land this post-March, right?

**Comment by kripken** [comment]
Or post-February..? ;)

**Comment by jfbastien** [comment]
You're saying post-haste? :p

**Comment by JSStats** [comment]
Looks like it could be made a command line option for a manage transition and for experimentation.

**Comment by kripken** [comment]
I'd rather not have to support both - it would be a lot of extra code, basically each ast handler would have ifs and multiple code paths.

Since the wasm spec is moving to postorder, I think we should just land this now, as in any case we have not had interoperability with other tools.

**Comment by JSStats** [comment]
Has someone written a specification that you are following or is it a matter for experimentation?

Are there particular goals for this decision?

It does not look like a pure post-order encoding. For example the EndMarker seems to just terminate a pre-order operator. If you wanted post-order then a block could still have an immediate count and would just pop the expressions from the stack.

If people want to actually interpret this code then it will need to deal with the values resulting from these expressions, so either need to explicitly discard unused values for each expression or be pre-order. To discard the unused values in a post-order encoding will require explicit pop operations be included. If you want to explore this then you might want to change the representation from an AST to a stack machine and evaluate that.

I also expect people will want single-pass AST conversion with validation so will need to track pre-order state for some of these operations.

**Comment by titzer** [comment]
Can we just pick a date for the postorder transition?

**Comment by kripken** [comment]
@JSStats: there isn't a full postorder spec yet. This just moves us towards that general goal. That's also why it's not complete, as you pointed out. But it passes the full test suite, so it's already a good checkpoint I think.

I see no reason not to merge this now, since nothing depends on binaryen's binary tools yet? Am I missing something?

**Comment by JSStats** [comment]
@kripken But if 'post-order' is just a 'general goal' then what basis is there for a move towards this? Would it not be more prudent to explore both options and then compared them on technical merit?

If abstracted well, and if it only affects the serialization of the AST, then if should not be a big burden for tools to support both pre and post order encodings.

There are some basic questions that no-one has been willing or able to answer such as:

Is there an expectation that interpreters will interpret the code literally, or is it expected that it will be decoded into an AST first? It might be important because if interpreted literally then there is no top-down information, no expected types, no expected number of values, no function result type, no block labels. It becomes a stack machine and there is no longer an AST.

If it's is just a matter of the serialization of the AST then it might still have implications for single pass SSA conversion and for compression efficiency. It not clear how single pass SSA conversion could be done efficiently without pre-order information?

Also some effort was made to have binaryen be consistent with the v8 encoding, issues were filed on differences etc, and some progress has been made on resolving differences between the v8 encoding and the wasm spec. A quick look suggests that the only area still needing resolution is the `br` arity and mv issues - that seems really close to me. Plus the naming and number of some operators, which I submit a PR for soon.

**Comment by titzer** [comment]
On Sun, Feb 28, 2016 at 4:55 PM, JSStats <notifications@github.com> wrote:

> @kripken <https://github.com/kripken> But if 'post-order' is just a
> 'general goal' then what basis is there for a move towards this? Would it
> not be more prudent to explore both options and then compared them on
> technical merit?
>
> If abstracted well, and if it only affects the serialization of the AST,
> then if should not be a big burden for tools to support both pre and post
> order encodings.
>
> There are some basic questions that no-one has been willing or able to
> answer such as:
>
> Is there an expectation that interpreters will interpret the code
> literally, or is it expected that it will be decoded into an AST first? It
> might be important because if interpreted literally then there is no
> top-down information, no expected types, no expected number of values, no
> function result type, no block labels. It becomes a stack machine and there
> is no longer an AST.
>
I wrote a prototype pre-order direct interpreter after exploring various
rewriting strategies and found that it's entirely possible to do direct
interpretation of preorder. It's also highly brittle and counterintuitive
(since execution order reflects AST evaluation order, not encoding order).
You can see a prototype here: https://codereview.chromium.org/1675183004/

I implemented a post-order prototype here:
https://codereview.chromium.org/1694303002/

The data that I gathered from that prototype showed that postorder is
40-60% faster to decode, with no loss in expressiveness. It was also a big
simplicity win. I didn't finish the job yet with a postorder interpreter,
but suspect that it will also be simpler and easier to reason about; the
post order encoding reflect execution order.


> If it's is just a matter of the serialization of the AST then it might
> still have implications for single pass SSA conversion and for compression
> efficiency. It not clear how single pass SSA conversion could be done
> efficiently without pre-order information?
>
It works. One simply needs to use bracketed blocks (i.e. block ... end) and
an in-order encoding of if (i.e. {cond} if {true} else {false} end). That
actually works out quite naturally, since the in-order bytecodes appear at
exactly the points where SSA renaming must split or merge environments.

**Comment by kripken** [comment]
There have also been `preorder` and `postorder` branches in this repo for a while, for experimentation with this. Testing things like decode speed, I also see benefits to postorder, like @titzer (different sizes though, but that's probably due to measurement method).

The one downside to postorder (or postorder + something else for control flow) is that it makes the raw binary 1% or so larger, which is expected (since in preorder we an avoid end markers for some control flows). However, testing on real-world code like Poppler and BananaBread, that vanishes and even reverses after gzip (and lzma and others). I don't have a good explanation for that, but it does suggest that code size is not a serious problem for postorder.

**Comment by rossberg-chromium** [comment]
I actually wonder if we really need the end markers in postorder. The decoder should be able to maintain a stack

**Comment by rossberg-chromium** [comment]
Oops...

**Comment by JSStats** [comment]
Thank you all for the feedback. It's obviously much more subtle than just a post-order encoding, a hybrid. I'd like to implement an encoder/decoder and check the compression and explore some concerns. It would be very interesting to be able to compare the pre-order interpreter to a post-order interpreter, in particular I would like to understand the story for multiple values and if it now needs a `pop` operator and how validation would work etc. I'll have to follow up.

**Comment by rossberg-chromium** [comment]
@JSStats, it's just an encoding change, it has no effect on semantics.

**Comment by titzer** [comment]
The V8 patch probably doesn't apply cleanly anymore, but I suggest starting
there. I will update it soon.

**Comment by kripken** [comment]
Ok, merging this in. Its just a small step towards postorder, but since it's a clean refactoring and passes the test suite, and there is consensus to move towards postorder overall, it's helpful to merge it now.

**Pull request merged**
