### PR TITLE
License and contributing

### PR DESCRIPTION
**Pull request by jfbastien**
Same as the other repos.

### CODE REVIEW

**Comment by jfbastien** [comment]
@kripken , would you mind if this repo were consistent with the other wasm ones? I don't want to force this on you, but it seems pretty weird to license everything differently!

We can discuss tomorrow over beers :-)

**Comment by kripken** [comment]
I feel like I don't understand the background here. Sure, talking over beers sounds good.

**Comment by kripken** [comment]
Some thoughts before beers, so I don't forget:

If the goal is to have a uniform license for the WebAssembly/ projects so they can share code, then that sounds good. However, I don't think the Apache 2 license is the best for our purposes. The two main problems are

 * Apache has a binary attribution clause, which makes it troublesome for code included in build outputs (e.g., the binaryen asm.js => wasm polyfill would ship with the build, and fall under that clause). For example, LLVM is considering moving to Apache, but [only with a runtime exception](http://lists.llvm.org/pipermail/llvm-dev/2015-October/091536.html). So I think we would need a runtime exception here as well, and there isn't a standard one, so we'd need to write one and people would need to read it carefully.
 * Apache 2 is not GPL 2 compatible.

The MIT license has neither issue and is standard and familiar, which is why I tend to prefer it.

**Comment by kripken** [comment]
Merged per discussion. We do want to add an exception for the attribution issue, but can do that later. For now, it's Apache 2.0 as in all the other WebAssembly/ projects.

**Pull request merged**
