### PR TITLE
[EH] Fuzz throws from JS

### PR DESCRIPTION
**Pull request by kripken**
We already generated `(throw ..)` instructions in wasm, but it makes sense to model
throws from outside as well, as they cross the module boundary. This adds a new fuzzer
import to the generated modules, `"throw"`, that just does a throw from JS etc.

Diff without whitespace is smaller.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, feedback should be addressed.

I also realized we can test this directly, and added that.

**Comment by kripken** [comment]
New testcase found an issue with hardcoded logging import names. They need to be flexible, like the throwing import one already was.

**Comment by kripken** [comment]
Also we must compute those names before we use them, a slight reordering in how we modify functions.

**Comment by aheejin** [comment]
Why would the logging function name changes are related to the throwing capability? And in which way are we changing the logging names (other than storing them in a map)?

**Comment by kripken** [comment]
@aheejin Before this PR, `execution-results.h` treated all imports from the `"fuzzing-support"` module as logging functions. After this PR, it only treats those with a name starting with `"log*"` that way.

By itself that shouldn't change much, but the fuzzer started to error on these tests because it was seeing initial content that already used a name like `(func $log-i32 ..`, so when the fuzzer tried to add another such function, it failed. Instead the fuzzer now uses `getValidFunctionName` to make up the new names, saves it in the map, and calls the functions using those names.

**Comment by kripken** [comment]
And I think the fuzzer started to fail because it ran into those files a lot more because they have been recently updated in this PR. The problem existed before AFAICT.

**Review by aheejin — APPROVED** [review]

**Pull request merged**
