### PR TITLE
CtorEval Fuzzer: Generalize export regex

### PR DESCRIPTION
**Pull request by kripken**
Just look for export names as "" with some non-" in the middle.

That should handle everything but escaping of " in an export name (which I don't know
if we can handle in a regex?).

Missing from the old regex: spaces, parens, and probably more. Spaces and parens
are used in the test suite, which is how this was noticed by the fuzzer.

### CODE REVIEW

**Review by tlively — APPROVED** [review]
If you require the close parent to be preceded by nothing or anything except for a `\`, then you should be able to avoid accidentally matching it on an escaped quote.

**Comment by kripken** [comment]
Do you know how to do that in a regex?

**Comment by kripken** [comment]
Doing some tinkering, it seems like `r'"((?:[^\\"]|\\.)*?)"'` might work..

**Comment by tlively** [comment]
I was thinking of something along the lines of `".*[^\\]?"`

**Comment by kripken** [comment]
Thanks, that's even simpler. I keep forgetting that regex `.*` is not "literal" (it still complies with the constraints afterward, rather than consuming everything til the end).

**Review by tlively — APPROVED** [review]

**Pull request merged**
