### PR TITLE
Disable fuzzing of `return_call_ref`

### PR DESCRIPTION
**Pull request by tlively**
The latest V8 has updated to emit a type annotation on `return_call_ref` so our
fuzz output will not validate until we make the corresponding update. Disable
emitting that instruction until we get a chance to make that change.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5030** <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/5030" target="_blank">Graphite</a> 
    * **PR #5031** <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/5031" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/WebAssembly/binaryen/5031?utm_source=stack-comment).

**Review by kripken — APPROVED** [review]
If we have `return_call_ref` in the test suite then we'll need to ignore those files too. But maybe that will be rare enough that we can wait to fix the binary format.

**Comment by tlively** [comment]
There are a couple, but I'll just fix the format instead.

**Comment by tlively** [comment]
Closing in favor of #5068.

**Pull request closed without merging**
