### PR TITLE
wasm-emscripten-finalize: prepend unserscores to user-defined functions

### PR DESCRIPTION
**Pull request by sbc100**
This is the format the emscripten expects from asm2wasm so we
should mimick that format. Perhaps in the future we can move away from
this, but for now it will simplify emscripten to have to deal with
a single format.

### CODE REVIEW

**Comment by kripken** [comment]
Why is this useful - I thought we already handled all the inconsistencies between the two formats in emscripten?

**Comment by sbc100** [comment]
We do.. but I'm running into another place where I need to handle this and I thought "why do we keep having to deal with this, isnt' this exactly what wasm-emscripten-finalize is for".

There is also at least once place where emscripten want to distinguish between "user-space" functions, and it uses this as a kind of namespace.
 
Its not super important, we could cotninue to handle both in emscripten..

**Comment by jgravelle-google** [comment]
This looks good, is there an accompanying emscripten-side change? Or does this somehow not break things.
Might be useful to see the simplifications this allows us to do emscripten-side, to see how much this buys us.

For clarity: I fully support minimizing the inconsistencies and unifying these, and this seems like the easiest way to do that.
Given infinite engineering time, I'd like to move asm2wasm to use upstream's conventions. It's possible that the simplest path to get to that state is to maintain both conventions for now, and convert for free when we eventually deprecate asm2wasm. It's likely though that it doesn't matter which convention we use, and simplifying our implementation is the only thing we can actually get out of it, so I don't feel at all strongly about this, and am just thinking out loud in case anyone else has better insights here.

**Comment by sbc100** [comment]
I think I'm gonna hold off on this, at least for now.

**Comment by dschuff** [comment]
I wish we had thought to do this in 2016....

**Comment by kripken** [comment]
It might be possible to transition asm2wasm to remove underscores - in ASSERTIONS mode we could emit wrappers that emit nice errors if the user forgot one ("you're calling _main, you should call main"), so the change might not be too disruptive.

**Pull request closed without merging**
