### PR TITLE
Fix install locations per FHS and allow to customize them

### LINKED ISSUE #951: `make install` should not put `.js` files in `.../bin/`
These files are specifically `wasm.js` and `binaryen.js`.

### PR DESCRIPTION
**Pull request by jirutka**
Include built-in cmake module GNUInstallDirs that defines customizable
CMAKE_INSTALL_* variables with common defaults per FHS.

New FS structure when installed with `CMAKE_INSTALL_PREFIX=/usr`, `BUILD_SHARED_LIBS=ON`:

```
    usr
    ├── bin
    │   ├── asm2wasm
    │   ├── s2wasm
    │   ├── wasm-as
    │   ├── wasm-dis
    │   ├── wasm-opt
    │   └── wasm-shell
    ├── include
    │   └── binaryen-c.h
    ├── lib64
    │   └── libbinaryen.so
    └── share
        └── binaryen
            ├── binaryen.js
            └── wasm.js
```

~~Only src/js is not parametrized, I'm not sure where it should be
correctly installed and there's no variable for $PREFIX/src in
GNUInstallDirs.~~

EDIT: I’ve removed src/js, because it’s needed and used only for building binaryen.js.

See https://cmake.org/cmake/help/v2.8.7/cmake.html#module:GNUInstallDirs
for more information about used variables.

Fixes #951

### CODE REVIEW

**Comment by phil-el** [comment]
Hi, /usr/src must be avoided, it's used for reference only. Also js as a name is way too generic, you are more likely to have conflict with other package with such name, can the content of /js go to share/binrayen?

**Comment by jirutka** [comment]
Agree. I don't know for what are these files inside src/js really used or useful.

**Comment by dschuff** [comment]
IIRC The JS files in `src/js` are just for building `binaryen.js` and probably don't even need to be installed. Not sure about `binaryen.idl` though. But if it does need to be installed, `share/binaryen` seems about right.

**Comment by kripken** [comment]
The `idl` is used to build `binaryen.js`, and isn't needed afterwards.

**Comment by kripken** [comment]
Looks great to me too. Please join the [wasm group](https://www.w3.org/community/webassembly/participants) if you haven't already.

**Comment by jirutka** [comment]
> Please join the wasm group if you haven't already.

Done.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
