### PR TITLE
Update wasm-shell expected failures

### PR DESCRIPTION
**Pull request by jgravelle-google**

### CODE REVIEW

**Comment by jgravelle-google** [comment]
Updating the pinned waterfall version to take advantage of attributes in the expected failures. Updating torture-s files as well so we can have green builds for both.

**Comment by jgravelle-google** [comment]
Ping @kripken @dschuff , any objections to updating the waterfall revision / checked in .s torture tests?

**Comment by kripken** [comment]
I don't object, but I also don't fully understand the value of the checked in .s torture tests currently. I assume they'd go away with s2wasm eventually anyhow? Anyhow, as I said, if has value for now, sounds ok to me.

**Comment by jgravelle-google** [comment]
As I understand it, the checked in .s torture tests are something of an additional layer of regression testing for the s2wasm parser. I think they made more sense before the wasm spec had stabilized?
But yeah, we won't recreate them after removing s2wasm.

**Comment by dschuff** [comment]
Yeah, think of the checked-in .s tests as "unit" tests for the .s parser, (and the waterfall .c->.s->.wast pipeline as an integration test). We have existing binary<->wast tests, and if we add another format, we'll have similar tests for it.

**Pull request merged**
