### PR TITLE
Fix zero-extension in i64.load32_u.

### PR DESCRIPTION
**Pull request by sunfishcode**
This fixes a bug in the interpreter with i64.load32_u, which affected printf, which caused the incorrect output observed here: https://llvm.org/bugs/show_bug.cgi?id=27518

I'm not sure how to write or run tests for this code, and I'm not attached to the particulars here, in case someone wants to fix this a different way.

The following is a small testcase which produces the problem without calling printf. It should print "aA" but with the bug it prints "aP".

```
#include <stdint.h>
#include <stdio.h>

volatile uint64_t x = 0x0101010101010101;
volatile uint32_t u = 0xfefefefe;

int main(void)
{
   putchar('a' + (x >> 60));

   x = u;    // i64.load32_u

   putchar('A' + (x >> 60));
   putchar('\n');
   return 0;
}
```

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

I guess this was not detected by all the asm2wasm testing and fuzzing since asm2wasm has no native i64s... and the spec tests have i64 loads, but we have different code for them in wasm.js, the memory access must integrate with the JS-accessible heap.

We can add a test for the wasm backend, just by adding a cpp and a txt (of the output, and same basename) to `wasm_backend/`.

**Comment by sunfishcode** [comment]
Ok, test added.

**Comment by sunfishcode** [comment]
Also, this doesn't include the updates to bin/binaryen.js and bin/wasm.js because I'm not sure I built them properly.

**Comment by kripken** [comment]
No problem, I can update that part. I'll push to this PR.

**Comment by kripken** [comment]
Fixed a check.py bug that this hit. Merged.

Thanks again for looking into that bug!

**Comment by dschuff** [comment]
It looks like this PR resulted in a merge commit. I thought we disabled merge commits and only use sqaushing?

**Comment by kripken** [comment]
In general squashing is nicer, but in this PR for example i think a merge is better, for future reading of the commits - squashing would eliminate some information.

**Pull request merged**
