### PR TITLE
[NFC] Add validation checks in OptUtils::optimizeAfterInlining

### PR DESCRIPTION
**Pull request by kripken**
This can help find errors in the middle of passes like Inlining, that do
multiple cycles and include optimizations in the middle.

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Should we do this only for higher PassDebug levels to avoid affecting the pass timings reported at level 1?

**Comment by aheejin** [comment]
Do we need to do the check also before the optimization, not only after it? In that case, if we run the optimization function multiple times, wouldn't we run the optimization twice on the same input after an iteration and before the next iteration?

**Comment by kripken** [comment]
It could be wasteful in that case, yeah. But the existing passes call it once in each iteration, so we do something like "inline some functions, optimize, inline some more functions, optimize", and for that it makes sense to check for errors both in the inlining and in the optimizations. (And while that is slower, pass-debug mode is where we do the slowest checks.)

**Comment by kripken** [comment]
@tlively 

> Should we do this only for higher PassDebug levels to avoid affecting the pass timings reported at level 1?

Hmm, that's a good question. It does seem bad to add to those timings, but mode 1 is the one most tested and fuzzed. I'll think some more, maybe there's a good way to avoid this problem.

**Review by aheejin — APPROVED** [review]

**Comment by kripken** [comment]
@tlively I can't think of a better solution than your idea to do this in level 2+, so I switched to that. It is nice and simple and captures almost all the benefits without that timing downside.

**Pull request merged**
