### PR TITLE
Added default optimization passes for convenience in the runPasses API.

### PR DESCRIPTION
**Pull request by COFFEETALES**
It brings the ability to use
``` javascript
decodedModule.runPasses(['default-optimization-passes']);
```
from the JS API, only for convenience.

### CODE REVIEW

**Comment by tlively** [comment]
I wonder if it would make more sense to just add a pass called "default-optimizations" that would just run all the default optimization passes as subpasses. This could be a really nice refactoring to get all the default pass logic out of the option parsing, too. @kripken what do you think?

**Comment by kripken** [comment]
@tlively interesting idea! I think that might work, the only thing is we need to make sure not to change the output of `BINARYEN_PASS_DEBUG` (=1,2,3). I think not making them nested passes should be enough for that.

**Comment by kripken** [comment]
As for names, we have have `-O`, `-O2`, etc., and they'd also set the opt level etc.

**Comment by hummeleBop** [comment]
Hi there,

Right now, the js API still lacks the ability to push the default optimization passes on the pass runner.

Something simple as the following code could be really helpful ..

``` diff
> git --no-pager diff --no-index -- C:\dev\tmp\binaryen\src\binaryen-c.orig.cpp C:\dev\tmp\binaryen\src\binaryen-c.cpp
diff --git "a/C:\\dev\\tmp\\binaryen\\src\\binaryen-c.orig.cpp" "b/C:\\dev\\tmp\\binaryen\\src\\binaryen-c.cpp"
index c91c154..e754c41 100644
--- "a/C:\\dev\\tmp\\binaryen\\src\\binaryen-c.orig.cpp"
+++ "b/C:\\dev\\tmp\\binaryen\\src\\binaryen-c.cpp"
@@ -3788,7 +3788,10 @@ void BinaryenModuleRunPasses(BinaryenModuleRef module,
   PassRunner passRunner((Module*)module);
   passRunner.options = globalPassOptions;
   for (BinaryenIndex i = 0; i < numPasses; i++) {
-    passRunner.add(passes[i]);
+    if (0 == std::string("default-optimization-passes").compare(passes[i]))
+      passRunner.addDefaultOptimizationPasses();
+    else
+      passRunner.add(passes[i]);
   }
   passRunner.run();
 }
```

Thanks a lot,

**Pull request closed without merging**
