### PR TITLE
Revert "Stop propagating/inlining string constants (#6234)"

### PR DESCRIPTION
**Pull request by kripken**
This reverts commit 9090ce56fcc67e15005aeedc59c6bc6773220f11.

Disallowing  such optimization prevents e.g. `string.eq` from being
optimized out, if doing so depended on propagating constants to its arms.
Instead, to fix the real problem here, #6257 adds a pass that is run at the
end to collect `string.const` to globals. What will happen in practice is that
we propagate strings as we optimize, then at the end we collect them.

cc @gkdn - do you have thoughts on what order should these PRs land?

### CODE REVIEW

**Review by tlively — APPROVED** [review]

**Comment by gkdn** [comment]
@kripken I think it would be best to avoid submitting this until we can complete the switch to imported string otherwise it would cause regression. (We cannot do the production switch until latest Chrome changes hit stable plus couple of weeks)

**Comment by gkdn** [comment]
Just to double check my understanding:
StringGathering pass will move all string.const to globals and will be running by part of O2.
Then later you will add additional pass which will be flag controlled to lower strings to imports.

When the other pass is added, will there be a benefit of running StringGathering as part of optimization loop vs. just running behind the scenes as part of the lowering pass that we will run once at the end? 

Or is this just a temporary state so we can get the benefits of propagation without regression until we switch to imported strings?

Ordering wise seems like should we submit https://github.com/WebAssembly/binaryen/pull/6257 first?

**Comment by kripken** [comment]
@gkdn 

> When the other pass is added, will there be a benefit of running StringGathering as part of optimization loop vs. just running behind the scenes as part of the lowering pass that we will run once at the end?

It will not be needed at that time, correct. We might still keep it around because other toolchains might not run the other pass at the end, and in that case it would still help.

> Ordering wise seems like should we submit https://github.com/WebAssembly/binaryen/pull/6257 first?

Agreed, yeah. Then when we land the reversion we won't get a regression.

Sound good to land them now, in that order?

**Comment by gkdn** [comment]
Sounds good.

**Pull request merged**
