### PR TITLE
Remove API tracing

### PR DESCRIPTION
**Pull request by dcodeIO**
¯\\(ツ)/¯

### CODE REVIEW

**Comment by dcodeIO** [comment]
A few stats:

|         | Before | After
|------|---------|------
| binaryen-c.cpp (loc) | 5.223    | 3.136
| binaryen_js.js (bytes)    | 4.164.907 |  3.976.715
| binaryen_wasm.js (bytes) | 2.948.074 | 2.908.208

**Comment by dcodeIO** [comment]
Please also take a look at my `auto*` and `(const) auto&` cleanup that became possible by this, you know, in case I'm doing something stupid again.

**Comment by tlively** [comment]
Aww man I was really proud of some of the nasty hacks I put in there to make the tracing semi-maintainable. But yeah I've never actually *used* the tracing, per se. I whole-heartedly support this change 👍

**Comment by dschuff** [comment]
https://i.kym-cdn.com/photos/images/original/001/126/238/e84.gif

**Comment by kripken** [comment]
Great, landing!

**Pull request merged**
