### PR TITLE
update wasm version to 0x01

### PR DESCRIPTION
**Pull request by kripken**
In prep for release, and since browsers are ready to accept it.

At least I think they are - sm accepts 0x1, while v8 doesn't appear to yet, but from the email discussion it sounded like it was about to (and we should merge this in now so they can get the type system update together with it)? cc @dschuff

### CODE REVIEW

**Comment by dschuff** [comment]
V8 is supposed to accept 0x1 binaries: https://chromium.googlesource.com/v8/v8/+/fa7d1f8f75e340d917831ef74f401154b0a90cc7 does it not work for you?

**Comment by dschuff** [comment]
There is one potential hiccup: [jsc](https://github.com/WebAssembly/waterfall/pull/172) probably does not. But we want binaryen to work for the browsers that have preview releases that support wasm today, so I think 0x1 is the right thing. I'd like to have jsc work on the waterfall but we can always hack the binary or convert with some other tool or whatever, since the actual binary is the same.

**Comment by dschuff** [comment]
oh i think that patch has not been merged to the browser yet. i think that's what ben is waiting on. anyway this LGTM

**Comment by kripken** [comment]
Ok, cool, thanks. Will merge once green.

**Comment by wllang** [comment]
The CG as a whole has not agree to release WASM any time soon, and to make these changes may mislead the web community and damage the development work. Thus on behalf of the CG members I ask that the binaryen project disassociated itself from the CG and to please stop using the WebAssembly banding of the CG. If you fail to correct this within 24 hours a vote to take harsh action and expel the binaryen project will go to the members. If there are web browser vendors promoting or spreading misinformation then they also have 24 hours to disassociate from the CG and to stop using the CG branding. This is your first and final warning.

**Comment by dschuff** [comment]
@wllang 
Disclaimer: This is my personal belief/opinion and I'm not a lawyer and I do not (or you, for that matter) represent the CG nor the W3C. I also do not officially speak for the Binaryen project.

I don't believe Binaryen is technically a product of the wasm CG. For example the description given of CGs (cf https://www.w3.org/community/about/) is that a CG is for discussion and [optionally](https://www.w3.org/community/about/faq/#proposal-good-practice) publishing ideas or specs or (if specified in the misson) even producing code or tests, but for wasm specifically, code seems outside the scope of the CG's stated [mission](https://www.w3.org/community/webassembly/).

This makes sense to me for 2 reasons. 
First, my primary goal for binaryen (and wabt and LLVM which notably is definitely not affiliated with or covered by the CG) is that it be useful for people who want to build software for the web. This means (for example) that a primary goal and constraint is that the code we produce be accepted by the environments that people want to use and target; namely, web browsers (but also in the future, environments such as node.js and other possible non-JS embeddings of wasm). If we don't do that, then we are just a research project.  By the way, there's nothing wrong with research projects. I would even be willing to consider contributions to Binaryen (or wabt or LLVM) that are meant for experimentation if they don't prevent us from serving our other users. But serving those users who just want to build code for wasm and the web is my primary goal. My goals and priorities might not be exactly the same as someone else's, and where there are differences, then we should discuss, persuade, negotiate, and advocate for the users and use cases that we care about. I would love to engage in any of those activities (but issuing ultimatums is not negotiating).

Secondly, in some hypothetical future world where wasm is spec'd and shipped, and the browser vendors are no longer devoting resources to adding features, it's entirely possible that the CG will be closed, but that we or someone will still want to maintain and develop Binaryen and other tools. In other words, Binaryen could outlive the CG.

My conclusion is that I want Binaryen to be an open-source software product that serves its users (regardless of what happens on Github discussions) and also its bug tracker to be a place where everyone who cares feels like they can participate in a constructive way.

**Comment by wllang** [comment]
@dschuff Yes binaryen could disassociate from the CG with little impact on it and avoid some bias on the process, and could take some reasonable measures to avoid misleading the community, for example to claim to only follow the deployments by the web browser vendors etc and to not reference these by the branding of the CG, and I call on it to do so. Alon is Mozilla staff I believe and the lead of this project so that might also create a conflict of interests that is hard to avoid, it's not just someone forking binaryen adding this change.

**Comment by dschuff** [comment]
BTW I'm also happy to have "influence the CG discussion and/or wasm standardization process" be one of the goals and/or outcomes of Binaryen (hence my willingness to negotiate on goals and patches). But I fail to see what an attempt to explicitly disassociate ourselves from the CG would accomplish in that regard. 

But in general we have to put our users first. You seem to be concerned that emitting binary format "0x1" would mislead users into thinking that the CG has published wasm. I don't think our users care about the CG's opinion of wasm. They also do not care that (for example) webkit-prefixed CSS properties are discouraged by the standard. They do not care about the purity of the wasm language, or the design process, or what we like to argue about on github, or version numbers. They only care about what helps them serve their users. Practically speaking, if we do not do this, nobody will be able to use Binaryen, and I care about that. 

To the extent that Binaryen is part of the product of CG (and again, maybe it totally is) its purpose can still be different than the purpose of the design or spec parts of the CG. I want this space to be somewhere we worry about how to serve our users' purposes, not about sending messages to the web community. To the extent that we (the developers of Binaryen) are browser vendors or have conflicts or differences in priorities, I would hope we can resolve those in a friendly way, and thus far I believe we have, in a way that helps everyone. Alon may test most with SpiderMoneky, but he reports V8 bug as he finds them; I test mostly with V8 but I'm helping bring up JSC support on the build waterfall. In Binaryen I've focused most on support for the upstream LLVM backend and Alon has done more work with asm2wasm and optimizations. But somehow we manage to get along without arguments and threats.

**Comment by wllang** [comment]
@dschuff This is not about positive influences that binaryen has had on the project, and they don't justify the current action. Bineryen and emscripten have not helped the group answer matters such as the utility of  a `pick` operator or the encoding efficiency of an SSA encoding or provided support for others to exploring compilers for these. I have written to Alon politely sharing my wip, and that was around a year ago and I believe the response then was that there was not time! Sorry this excuse seems damaging to the project to me, and if it were not for this excuse a year ago we might have made much better progress. I don't want to see the work of the group squashed by this constraint.

I am a user, and I am concerned about getting a good outcome. It is not me saying that wasm is ready for a release. I can demonstrate many of the problems and can argue the technical case, and even demonstrate better alternatives, these are matters of good performance etc, matters that I believe users care about.  For example, Luke Wagner of Mozilla was recently supportive of a 15%-20% performance lose for 32-bit x86, see https://bugzilla.mozilla.org/show_bug.cgi?id=1338217 I think, well hope, there are users who care and such matters. I have engaged and pointed out the problems, and for a long time have suggested paths forwards. I believe I have more claim to representing a good outcome for users.

> I don't think our users care about the CG's opinion of wasm.

I hope there are a good number of CG members who are users very interested in meeting use cases including performance. I am a user, I am here.

This is all about a subgroup attempting to ram through a release without being prepared to stand up and defend the technical merits of that decision, and a group that has failed to explore design ideas raised long ago, or to accommodate use case raised long ago.

Don't try and blame the CG members, we have tried, we are not claiming the design is ready. Accept your own failures.

> But somehow we manage to get along without arguments and threats.

So if CG members try to defend a good working environment and protect the group against what seems reasonable to describe as the absolute contempt for them by a subgroup then you are going to slur their character as being argumentative and threatening? Well shame on you. I will give them a private vote, they do not need to support me, but I will at lease give them the respect of a vote and I will put the technical case to them and discuss it with them.

To the CG, I have asked Mozilla for the peer of the Firefox WebAssembly component. I understand these position are based on merit and I believe I can demonstrate merit, I can certainly demonstrate better performance of some alternatives. If granted the peer I will focus the work on the technical matters to try to keep this process objective and will explore ways of opening it up so that more people feel confident contributing such as holding a competition in which you can all participate and receive some recognition for good entries in various categories.

**Comment by dschuff** [comment]
> I am a user, and I am concerned about getting a good outcome.

You have made this concern perfectly clear in discussion on the other wasm projects. Not everyone is going to have the same priorities as you are, and the same idea of what a "good outcome" is, and the same opinion of what the tradeoffs are, and not everyone will pay the same cost for those tradeoffs.

> I hope there are a good number of CG members who are users very interested in meeting use cases including performance. I am a user, I am here.

You are not the only user. I am willing to lend some support your use case, but I'm not willing to compromise everyone else's use case to get it (e.g. by making Binaryen incompatible with the browsers many users want to use).

> This is all about a subgroup attempting to ram through a release

Not for me, it isn't. For me, "this" was your post demanding changes to Binaryen, with some vague threat of expulsion from a group which you do not control, whose purpose is not even particularly well-defined.  

> So if CG members try to defend a good working environment

Defending a good working environment is exactly what I'm trying to do here. 

> I will give them a private vote, they do not need to support me, but I will at lease give them the respect of a vote and I will put the technical case to them and discuss it with them.

You are encouraged to discuss whatever you want with CG members, and take as many votes as you like. In fact, persuading others to come out in support of your ideas sounds like an excellent way to move those ideas forward in discussion and implementation.

>If you fail to correct this within 24 hours a vote to take harsh action and expel the binaryen project will go to the members. If there are web browser vendors promoting or spreading misinformation then they also have 24 hours to disassociate from the CG and to stop using the CG branding. This is your first and final warning.
...
> slur their character as being argumentative and threatening? Well shame on you.

I don't know what else to say. I stand by my interpretation of this post as argumentative and threatening. I refuse to be ashamed of asking anyone not to be argumentative and threatening. I am sorry if a subgroup of the wasm CG has not respected your opinions, or implemented your ideas. I am sorry if you feel anyone has treated you with contempt. I don't want anyone to feel disrespected or threatened, and all I am trying to do is keep this part of the working environment (to the extent that I have influence over it) as friendly as possible. 

I humbly suggest that your approach is not likely to be very effective in achieving your ends, but I demand that you act respectfully and professionally, even (especially) if you believe that others have not so acted toward you.

**Comment by wllang** [comment]
> I stand by my interpretation of this post as argumentative and threatening.

That is a slur on my character, and a repeated on.

> but I demand that you act respectfully and professionally

The business of this group is a professional matter. I believe your characterisation of it otherwise is a slur on my character. Take a look at yourself pal, and shame on you.

**Comment by kripken** [comment]
@wllang 

I am afraid I must agree with @dschuff that your message is unproductively worded, for example when you say things like

> This is your first and final warning.

It appears you have issues with the wasm design process as a whole, but this PR is not the right place for them. All Binaryen is, is a technical project that helps us compile to wasm, and all this PR is, is updating the bits Binaryen emits so that browsers will accept it - this is us responding to what browsers tell us to do. Binaryen has no choice in the matter.

**Comment by qwertie** [comment]
> I humbly suggest that your approach is not likely to be very effective in achieving your ends, but I demand that you act respectfully and professionally, even (especially) if you believe that others have not so acted toward you.

+1 to that. I share @wlllang's desire for more inclusive and transparent behavior from the browser devs, but he often takes an overly harsh, confrontational approach. Which evidently hasn't worked if they're already switching to the final version 0x01 :(

**Comment by wllang** [comment]
@qwertie Ok, thank you for the honest feedback, but I don't see much left that I can do, and not without support of the community. My offer to be the peer of the Firefox WebAssembly component was time limited and lapsed without response, and I have no interest in dealing with a hostile Mozilla. I believe the wasm 1.0 being promoted falls way short of the design principles and I have no wish to be associated with it. i certainly have wip with better performance and encodings that better meet the design principles and that overcome many shortcomings that the project will inevitably run into. There seems nothing left but to give up and so I resign (as soon as I work out how). So you need no longer need put up with me, have a good one, and I apologize to anyone who I may have offended but I hope someday people can accept that I just wanted to see the project a success and it seemed a generational opportunity and given my age my last chance to see. Obviously I am very disappointed in the outcome. Perhaps I can work with some of you in other forums where our interest are better aligned, e,g. I am taking my variant to low end IoT devices.

**Comment by qwertie** [comment]
@wllang I see. Well, on a positive note, I have admired the persistence and determination with which you pursued your ideas in the face of indifference. If I had that same tenacity, I really think I would have been able to influence the design, at least a little.

**Pull request merged**
