### PR TITLE
Encode command line to UTF8 on Windows

### LINKED ISSUE #4995: Processing modules at paths that contain extended unicode characters on windows fails
As far as I can determine, binaryen always fails to open files that contain non-ascii (or perhaps non-latin-1 or some other windowsy encoding) in their path on windows. This is probably because there is no explicit "wide char" support in the code, which is how windows represents unicode, as utf-16.

I have tried to process files via unicode paths with a self-built wasm-opt.exe within the developer command prompt, inside cygwin's mintty, and programmatically (from rust bindings):

cygwin:

```
$ bin/wasm-opt.exe ../..//hello_world❤️.wasm -o ../..//hello_world_opt.wasm
Failed opening '../..//hello_world??.wasm'
```

command prompt:

```
c:\cygwin64\home\Brian\binaryen\build>bin\wasm-opt.exe ..\..\hello_world❤️.wasm -o ..\..\hello_world_opt.wasm
Failed opening '..\..\hello_world??.wasm'
```

Fixing this seems like it would require all paths to be hidden behind some platform-specific typedefs that resolve to WCHAR on windows, but I don't have much experience here.

cc https://github.com/brson/wasm-opt-rs/issues/40

### PR DESCRIPTION
**Pull request by dschuff**
This PR changes how file paths and the command line are handled. On startup on Windows,
we process the wstring version of the command line (including the file paths) and re-encode
it to UTF8 before handing it off to the rest of the command line handling logic. This means
that all paths are stored in UTF8-encoded std::strings as they go through the program, right
up until they are used to open files. At that time, they are converted to the appropriate native
format with the new `to_path` function before passing to the stdlib open functions.

This has the advantage that all of the non-file-opening code can use a single type to hold paths
(which is good since std::filesystem::path has proved problematic in some cases), but has the
disadvantage that someone could add new code that forgets to convert `to_path` before 
opening. That's somewhat mitigated by the fact that most of the code uses the `ModuleIOBase`
classes for opening files.

Fixes #4995

### CODE REVIEW

**Comment by dschuff** [comment]
This is essentially the orthogonal piece to #5627 (i.e. it doesn't depend on std::filesystem, which may end up being problematic) and I think it actually should accomplish the same goal as #5514 . It's not exactly done but as I'm OOO next week I thought I'd upload it.
Basically it encodes the command line to UTF8 and keeps std::string as the way to carry filename information. Then it encodes back to wchar on Windows where we open the file.

**Comment by dschuff** [comment]
This is slightly cleaned up. For some reason there still seems to be an issue with the source map paths. i.e. I tried testing by running  tests in a directory with an emoji (so all paths would have it) and the input and output paths seem fine, but source maps are failing to open for some reason I don't understand yet.

But it does show one possibility that doesn't require std::filesystem or use of std::wstring anywhere other than right at the point of opening files. One downside is that it does require explicitly doing the conversion everywhere we open a file, so it's easy to make a mistake. I think the only way to avoid that is use an abstraction like std::filesystem (or reinventing the path part of std::filesystem).
What do you all think?

**Review by kripken — COMMENTED** [review]
I'm not an expert on the windows stuff but overall this looks reasonable and non-intrusive.

**Comment by dschuff** [comment]
@brson maybe you can help here, I'm a bit stumped. Currently this patch *looks* like it should work, and it does when opening input files, but opening output files (either for e.g. wasm conversion output like in the lit tests here, or for source map output) fails. And not with a "file not found" error, but with an "invalid argument" error (you can see this in the test output on this PR). Does it have the same behavior on your machine? Do you have any ideas about what the issue might be?

**Comment by brson** [comment]
I'll get back to this next week and give this patch a test then.

**Comment by brson** [comment]
@dschuff I have tested this patch and made a fix:

https://github.com/brson/binaryen/commit/f8d37bbdd8575142d79d714927ac9d09159abfd5

This seems to resolve the issue of the `-o` flag not working.

**Comment by brson** [comment]
Here's a patch for the current windows build error:

https://github.com/brson/binaryen/commit/5183149c27f8c81294d2bf2993aa63c7116bcf68

The error is:

```
  D:\a\binaryen\binaryen\src\support\path.cpp(29,87): error C2440: 'return': cannot convert from 'std::wstring' to 'const wchar_t *' 
```

This is because the signature of `Path::to_path`

```
const PathString::value_type* to_path(const std::string& s) { return string_to_wstring(s); }
```

is asking for a `wchar_t*` on windows but returning a `wstring`. This signature won't work on windows because it requires returning a raw pointer to a temporary wstring's buffer.

Changing the signature to

```
const PathString to_path(const std::string& s) { return string_to_wstring(s); }
```

returning a string/wstring, works for all callers and fixes the build error on windows, still builds on linux.

I tested that wasm-opt on windows still works with unicode paths, but have not run the test suite.

**Comment by dschuff** [comment]
That is basically what I had in [9fe2f9b](https://github.com/WebAssembly/binaryen/pull/5671/commits/9fe2f9b86b1ccfcda7eeb0c837ae68637d305ed5) (now rebased to [9fdb5df](https://github.com/WebAssembly/binaryen/pull/5671/commits/9fdb5dfeca64d3d670446252ff13ea1cae8115cf) so you can see the current CI). The problem is that it doesn't work on mingw (which has GNU libstdc++ on top of windows)... libstdc++ doesn't have wchar versions of functions like `std::basic_ifstream<char>::open()`, presumably because they aren't useful on Linux where libstdc++ was developed. At this point I think I'm tempted to just not have good support for unicode paths on minGW. TBH I'm not even sure whether anyone uses the mingw build, but if someone pops up and asks about this, maybe they can help us figure out a solution :)

**Comment by dschuff** [comment]
I think this can be reviewed now. @kripken @brson WDYT?

**Comment by dschuff** [comment]
(CI note: the linter really wants "shellapi.h" to be included before "windows.h" but my understanding is that windows.h should be included first, so I'm leaving it).

**Review by kripken — APPROVED** [review]
Not an expert on the windows side, but those details look good in general, and overall this seems nonintrusive and helpful.

Testing here seems sufficient for now to me.

@brson can you confirm this fixes things for you?

**Comment by brson** [comment]
@kripken Yes, confirmed this patch works for me. I have tested it with the Rust bindings and our Unicode tests work on windows with it.

Thanks @dschuff!

**Pull request merged**
