### PR TITLE
Add a CMake flag to enable Wasm exceptions in the BinaryenJS build

### PR DESCRIPTION
**Pull request by dschuff**
This is useful for wasm performance (and for size tests, since Emscripten EH makes the binary unnecessarily slow and large).

### CODE REVIEW

**Review by aheejin — APPROVED** [review]

**Comment by dschuff** [comment]
I guess at some point we might want to make this the default, as most wasm runtimes will support exceptions. I imagine this might have already happened with some version of node... do we have any idea which?

**Comment by aheejin** [comment]
What do you mean by "it" in "it happened with some version of node"? Having Wasm EH support? Or supporting it by default without a flag? I just tested with several versions of node on my local machine and they turn on EH support by default (= without a flag) as of v17.5. v17.0 doesn't turn it on by default.

Not sure what you mean by "make this the default".

**Comment by MaxGraey** [comment]
Wasm exceptions enabled by default in node 17. 

See https://webassembly.org/roadmap
Screenshot 2023-02-03 at 00 35 11

**Comment by aheejin** [comment]
Hmm my local v17.0 was a nightly version I installed a few years back, so it might be the reason it didn't work..? Anyway, thanks for the info!

**Pull request merged**
