### PR TITLE
Add binaryen option --add-stack-limit-global

### PR DESCRIPTION
**Pull request by juj**
Add binaryen option --add-stack-limit-global to enable controlling when to emit the stack limit global variable to the wasm module.

### CODE REVIEW

**Comment by kripken** [comment]
This should be controlled by the emscripten `ASSERTIONS` flag - is that not good enough for some reason?

**Comment by juj** [comment]
This is for release builds. We want to have ability to check free stack space, but not emit runtime stack checks or other debug code.

**Comment by kripken** [comment]
> We want to have ability to check free stack space

Oh, can't you do that with `stackSave()` already? That gets the current stack location. Then you have `STACK_BASE` and `STACK_MAX` which is the valid range for it.

**Comment by sbc100** [comment]
Hopefully a lot of this will not be necessary in https://github.com/emscripten-core/emscripten/pull/11166 lands.

After this change it should be possible to these two new functions as aliases that live in `system/lib/compiler-rt/stack_ops.s` which can then be exported as needed via `EXPORTED_FUNCTIONS`.

The alias syntax in the `.s` format is:

```
set alias_of_foo, foo
``

**Comment by juj** [comment]
> Oh, can't you do that with `stackSave()` already?

I was not able to call `stackSave()` from C code, that did not seem possible, although with Sam's assembly code that would become a possibility?

> Then you have `STACK_BASE` and `STACK_MAX` which is the valid range for it.

Also was not able to access these from within wasm, without having to jump out to JS.

**Comment by sbc100** [comment]
> > Oh, can't you do that with `stackSave()` already?
> 
> I was not able to call `stackSave()` from C code, that did not seem possible, although with Sam's assembly code that would become a possibility?

Yes, as of, #11166 you should now be able to call stackSave() and friends from the C code.

> 
> > Then you have `STACK_BASE` and `STACK_MAX` which is the valid range for it.
> 
> Also was not able to access these from within wasm, without having to jump out to JS.

**Comment by juj** [comment]
This was resolved in another way earlier, so no longer relevant.

**Pull request closed without merging**
