### PR TITLE
Move bits.h to support/

### PR DESCRIPTION
**Pull request by jfbastien**
Faster compiles.

### CODE REVIEW

**Comment by jfbastien** [comment]
Hacked this up quickly but it's not quite ready for prime-time, but it's getting late here... Will fix tomorrow.

**Comment by kripken** [comment]
Oddly, this broke gcc on my machine (4.8.2), fixed in 6dab47590562df6e542ff3f0c105db138b8f4fd9

**Comment by kripken** [comment]
Oddly, this broke gcc on my machine (4.8.2), fixed in 6dab47590562df6e542ff3f0c105db138b8f4fd9

**Comment by jfbastien** [comment]
Huh, weird. Thanks for fixing.

**Pull request merged**
