### PR TITLE
Optimize away sets of the same local

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Comment by MaxGraey** [comment]
Hmm, after that PR in some our generated tests increased its size. Also it lead to performance degradation in [n-body benchmark](https://github.com/AssemblyScript/assemblyscript/blob/master/examples/n-body/build/optimized.wat) on ~5%.

Results before:
```
Performing 20000000 steps (AssemblyScript WASM) ...
Took 2928.2440619999998ms
```
Results after:
```
Performing 20000000 steps (AssemblyScript WASM) ...
Took 3045.604018ms
```

**Comment by kripken** [comment]
Sounds important - please find the specific commit that changed things, and show me your wasm before any optimizations, and I can investigate it.

**Comment by MaxGraey** [comment]
Sure!
This archive contain `wat` and `wasm` n-body example before release 69 and latest 72-nightly (actually master upstream). All where built with `-O4` in term of binaryen:
[nbody-binaryen-example.zip](https://github.com/WebAssembly/binaryen/files/2947566/nbody-binaryen-example.zip)

Also here you could see difference:
https://github.com/MaxGraey/assemblyscript/commit/ce698644412f6d0275923d1b919f1101f9827816#diff-764be5e57c2f6ba87580e44a5b0cc033

**Comment by MaxGraey** [comment]
@kripken Is this information enough? Let me know if you need anything else.

**Comment by MaxGraey** [comment]
Ok, I rechecked bench several times without any background tasks for avoid fluctuations and should correct - slowdown not 4-5% but 2-3%.

**Comment by kripken** [comment]
Can you get me the wasm file before optimizations? That is, I want to be able to run the earlier and later optimizer, and see the results locally.

**Comment by MaxGraey** [comment]
before and after wat and wasm files attached to this comment: https://github.com/WebAssembly/binaryen/pull/1940#issuecomment-471086813

**Comment by kripken** [comment]
Sorry, maybe I wasn't clear. What I need is a wasm file before binaryen optimized it - not before the new optimization change.

I just need that one file. With that, I will run the binaryen optimizer using a build before that commit, and after, and compare and debug that locally.

Is that file one of those included there? I interpret "before" as "optimized using the binaryen from before", am I wrong?

**Comment by MaxGraey** [comment]
Ah, got it! Here you are:
[untouched.wasm.zip](https://github.com/WebAssembly/binaryen/files/2962541/untouched.wasm.zip)

and untouched wat file you can find here: https://github.com/MaxGraey/assemblyscript/blob/ce698644412f6d0275923d1b919f1101f9827816/examples/n-body/build/untouched.wat

**Comment by kripken** [comment]
Ok, when I run `wasm-opt -Os` on that wasm file, I do see a change happen on 7e56e5b9eb08a68631d98f6d0d7db2adc2cd8236 which is
```
--- v83aa0dc2daf32.wat	2019-03-13 16:37:25.041479549 -0700
+++ vmaster.wat	2019-03-13 16:38:01.925810726 -0700
@@ -28,42 +28,41 @@
      (local.get $0)
     )
     (i32.shl
      (local.get $1)
      (i32.const 2)
     )
    )
   )
  )
  (func $~lib/array/Array<Body>#__get (; 1 ;) (; has Stack IR ;) (type $1) (param $0 i32) (param $1 i32) (result i32)
-  (local $2 i32)
   (if (result i32)
    (i32.lt_u
     (local.get $1)
     (i32.shr_u
      (i32.load
-      (local.tee $2
+      (local.tee $0
        (i32.load
         (local.get $0)
        )
       )
      )
      (i32.const 2)
     )
    )
    (i32.load offset=8
     (i32.add
      (i32.shl
       (local.get $1)
       (i32.const 2)
      )
-     (local.get $2)
+     (local.get $0)
     )
    )
    (unreachable)
   )
  )
  (func $assembly/index/Body#offsetMomentum (; 2 ;) (; has Stack IR ;) (param $0 i32) (param $1 f64) (param $2 f64) (param $3 f64)
   (f64.store offset=24
    (local.get $0)
    (f64.div
     (f64.neg
```

That looks like a good change, removing an unnecessary local.

But it's different than your diff. Perhaps you're running with different optimizations? I need the exact steps to reproduce your build.

**Comment by MaxGraey** [comment]
Yes, as I mentioned in this [comment](https://github.com/WebAssembly/binaryen/pull/1940#issuecomment-471086813) you should use `-O4`

**Comment by kripken** [comment]
Sorry for missing that earlier!

Testing with -O4, I don't see any difference at all on all the relevant commits.

In the past, I think we saw that AssemblyScript had some flags on, like maybe debug info? Flags might alter how optimizations work.

**Comment by MaxGraey** [comment]
I'm not sure this regression changes coming from this PR. It could probably after that [commit](https://github.com/WebAssembly/binaryen/commit/7e56e5b9eb08a68631d98f6d0d7db2adc2cd8236)

You could see wat differences here: 
https://github.com/MaxGraey/assemblyscript/commit/ce698644412f6d0275923d1b919f1101f9827816#diff-764be5e57c2f6ba87580e44a5b0cc033

**Comment by kripken** [comment]
Ok, I bisected this on -O4, and the change happens in 83aa0dc2daf327ed264cc22e51af1a866787a764

Investigating this, the change is that we add an extra copy of a local in the loop. That's definitely not good. The reason is we can't identify it properly as a copy yet. I'm actually working on fixing that this week, so hopefully this will go away.

Meanwhile I don't think we should revert that other change - it's doing something more correct in general, and here as well, but it just happens to get unlucky later when it fails to remove that copy.

**Comment by MaxGraey** [comment]
Thanks Alon! Hope this will go away after your next improvements

**Pull request merged**
