### PR TITLE
RemoveUnusedBrs: Allow less unconditional work and in particular division

### PR DESCRIPTION
**Pull request by kripken**
See #5983: The testcase from there is used here in a new testcase
`remove-unused-brs_levels` in which we check if we are willing to unconditionally
do a division operation. Turning an `if` with an arm that does a division into a
`select`, which always does the division, is almost 5x slower, so we should probably
be extremely careful about doing that.

I took some measurements and have some suggestions for changes in this PR:

* Raise the cost of div/rem to what I measure on my machine, which is 5x slower
  than an add, or worse.
* For some reason we added the if arms rather than take the max of them, so
  fix that. This does not help the issue, but was confusing.
* Adjust `TooCostlyToRunUnconditionally` in the pass from 9 to 8 (this helps
  balance the last point).
* Use half that value when not optimizing for size. That is, we allow only 4 extra
  unconditional work normally, and 8 in `-Os`, and when `-Oz` then we allow any
  extra amount.

Aside from the new testcases, some existing ones changed. They all appear to
change in a reasonable way, to me.

We should perhaps go even further than this, and not even run a division
unconditionally in `-Os`, but I wasn't sure it makes sense to go that far as
other benchmarks may be affected. For now, this makes the benchmark in
#5983 run at full speed in `-O3` or `-Os`, and it remains slow in `-Oz`. The
modified version of the benchmark that only divides in the if (no other
operations) is still fast in `-O3`, but it become slow in `-Os` as we do turn that
if into a select (but again, I didn't want to go that far as to overfit on that one
benchmark).

Thoughts?

### CODE REVIEW

**Comment by kripken** [comment]
I ran the emscripten benchmark suite on this. Several tests grow by a tiny amount, typically a few bytes, which is what you'd expect as a result of leaving some ifs as ifs and not selects. But it's far less than 1%. It also looks like a few tests get slightly faster, like corrections which is 6% faster. So that data supports this as a move in the right direction.

**Comment by dschuff** [comment]
I think this is a good idea. A div cost of 5x seems in the right ballpark to me. Actually a very brief and wildly unscientific look at https://www.agner.org/optimize/instruction_tables.pdf suggests that it's maybe even worse than that on recent Intel chips. e.g. IDIV on Cannon Lake shows a latency of 12-17 cycles compared to as low as 1 for add and 2 for conditional jump. But in any case if you've measured then this seems like a good improvement.

**Review by tlively — APPROVED** [review]
This all seems reasonable to me 👍

**Comment by kripken** [comment]
Ok, let's land this for now then.

I'm not sure why my measurements don't match the Agner charts, but we're measuring multiple things here I guess. This PR is a careful move in the right direction, I think, and we can improve more later.

**Comment by dschuff** [comment]
Yeah I would imagine the methodology matters a lot when talking about instruction latency, because instructions don't execute in a vacuum, they execute concurrently with a lot of other stuff happening at the same time. This PR definitely seems like the right direction.

**Pull request merged**
