### PR TITLE
Add CodeCov to CI

### PR DESCRIPTION
**Pull request by tlively**
Add a CI step to build with gcov instrumentation and run the lit test suite to
gather profiles, then upload those profiles to codecov.io to generate a code
coverage report for each PR. The goal is not necessarily to achieve 100% code
coverage, but rather to help find important missing test cases and dead code.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5856** <a href="https://app.graphite.dev/github/pr/WebAssembly/binaryen/5856" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/WebAssembly/binaryen/5856?utm_source=stack-comment).

**Comment by tlively** [comment]
Here's an example of the output: https://app.codecov.io/gh/WebAssembly/binaryen/commit/bb00d4ef4d54d3e6b8e681344727b0564c94e06a/tree

Once `main` has support for this, the links in the comments left by codecov-commenter should be much more useful

**Review by kripken — APPROVED** [review]
Looks useful!

**Comment by aheejin** [comment]
Nice! By the way does the coverage report show what our whole codebase covers, or what the specific PR covers? If the former it is not easy to figure out the specific effect of the PR, and if the latter the coverage will be really low.

**Comment by tlively** [comment]
You can see an example here: https://github.com/WebAssembly/binaryen/pull/5857#issuecomment-1664808196.

Basically it shows both coverage for the entire codebase as well as a diff in coverage for the specific PR.

**Pull request merged**
