### PR TITLE
Update waterfall revision to 7265

### PR DESCRIPTION
**Pull request by dschuff**
Also update torture-s tests.
This brings in the .functype directives and causes 2 more tests to pass.

### CODE REVIEW

**Comment by dschuff** [comment]
Looks like we have our first winner in the "upstream LLVM commit breaks binaryen build" lottery. I'll close this and try another.

**Comment by kripken** [comment]
Wow, that was fast. Is clang really that unstable in development? If this is going to be a problem, we could use an older and more stable build for building, and not the same as for the tests?

**Comment by dschuff** [comment]
Well to be fair, the commit that broke it was reverted after 50 minutes. I just happened to pick a really-new build and got unlucky.

**Comment by dschuff** [comment]
(but having said that, that sort of thing is not too uncommon.)

**Pull request closed without merging**
