### PR TITLE
fix build error for `std::isdigit is not found`

### PR DESCRIPTION
**Pull request by petamoriken**
fix Visual Studio 2015's error code.

### CODE REVIEW

**Comment by rwtolbert** [comment]
I think the `std::` is probably required for non-Windows.

A simpler fix is to `#include <cctype>`

**Comment by kripken** [comment]
cc @jfbastien 

fixing windows to work with `std::` seems better to me too.

**Comment by jfbastien** [comment]
`#include <cctype>` is better since you need the header for `isdigit` anyways (or `<ctype.h>` for the C version, but the C++ one is better for obscure reasons).

**Comment by kripken** [comment]
An include for `cctype` has been added.

**Pull request closed without merging**
