### PR TITLE
Refactor AsmConstWalker to use smaller subfunctions

### PR DESCRIPTION
**Pull request by jgravelle-google**

### CODE REVIEW

**Comment by kripken** [comment]
lgtm.

On a side note, I think all those `cashew::IString`s should be `Name`s. The IString stuff is an internal detail of how Name works. Unless I am forgetting a reason this code needs those internals.

**Comment by jgravelle-google** [comment]
Good call, done

**Comment by kripken** [comment]
Thanks, looks even better to me. (lebtm?)

**Comment by dschuff** [comment]
It was originally a hack around the fact that you couldn't put a `Name` in an unordered map because it didn't have the right hash overload. Somone fixed that but we (I) didn't get around to going back and fixing all of the places that should be `Name`s now.

**Pull request merged**
