### PR TITLE
Investigate thread sanitizer failure

### PR DESCRIPTION
**Pull request by kripken**
Just for debugging, this is not a PR to merge.

Print stderr in torture tests, run them on 1 thread, and skip all other tests.

### CODE REVIEW

**Comment by kripken** [comment]
Looks like the 3 unexpected failures all end in -9, with no stdout and no stderr. Looks like the waterfall harness lets tasks run up to 10 seconds. Perhaps those 3 are pushed over the limit of 10 seconds due to slower execution in thread-sanitizer mode? That would explain things if -9 is the error code when hitting the rlimit quota that the waterfall sets.

Note that there are other tasks ending in -9 already, marked as known failures - probably infinite loops bugs in the wasm backend, s2wasm, or wasm-interpreter. So this just adds 3 more to that list of bugs to investigate.

Either way, there isn't any thread-sanitizer output here, so tsan isn't actually finding a proper bug. So either they run out of time as suggested above, or some other difference occurs when running in tsan mode, like using more memory and running out of that. Seems like we need a way to mark "might fail" tests in the waterfall, if we don't already, and add those 3 to it? Or a tsan-fail list?

**Comment by jfbastien** [comment]
Hmm odd. Do they timeout locally? I thought I remembered there being tsan output before, maybe it went away!

**Comment by kripken** [comment]
Hmm, not sure how to test locally. I just investigated via travis.

**Comment by jfbastien** [comment]
Do the same build but with tsan, here's the script I use:
```
#!/bin/bash

set -e
set -u
set -x

export GOOG=/path/to/my/toolchain
export LD_LIBRARY_PATH=$GOOG/x86_64-grtev4-linux-gnu/lib64/
export CC=$GOOG/bin/clang
export CXX=$GOOG/bin/clang++
export COMPILER_FLAGS="-fsanitize=thread"

export BINARYEN_ROOT=/s/wasm/binaryen

rm -rf $BINARYEN_ROOT/build-tsan
mkdir $BINARYEN_ROOT/build-tsan
cd $BINARYEN_ROOT/build-tsan

cmake -G Ninja $BINARYEN_ROOT/ \
  -DCMAKE_C_COMPILER=$CC \
  -DCMAKE_CXX_COMPILER=$CXX \
  -DCMAKE_CXX_FLAGS="-fsanitize=thread" \
  -DCMAKE_BUILD_TYPE=Debug

ninja
```

You have to build and run with the same environment setup, because some of the tests also use the compiler.

**Comment by kripken** [comment]
Hmm, I get `clang-3.5: error: unsupported option '-fsanitize=thread'`, so I guess a special build is needed?

Anyhow, I don't think we would see something different locally, the travis results look consistent and stable. Unless the issue is timing out, in which cases a local machine faster/slower than travis might differ, of course.

And indeed the issue is timing out: meanwhile I tested adjusting the timeout, and increasing it from 10 seconds to 90 seconds lets the tsan build pass, which confirms the suspicions from before about this being a tsan-is-slow issue. And unsurprisingly, the tsan build takes much more than the others, around 8:30 (vs 6:30 for the normal ones).

So one way to fix the tsan bot is to modify the waterfall to increase the timeout. Or add an option to it to increase the currently hardcoded timeout of 10 seconds. Another option is to add the 3 super-slow failing tests to a "might fail tsan" list, but maybe that's less nice. Anyhow, I'm ok with any of those.

**Comment by jfbastien** [comment]
Increasing the timeout seems like the best thing IMO. Could you do that?

**Comment by kripken** [comment]
Sure, opened https://github.com/WebAssembly/waterfall/pull/45

**Comment by kripken** [comment]
The investigation here was concluded, closing this PR.

**Pull request closed without merging**
