### PR TITLE
[Wasm GC] GC-prefixed opcodes are int8, not LEBs

### PR DESCRIPTION
**Pull request by kripken**
This starts to matter with strings, it turns out. This change should make us
runnable in v8.

https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md#instructions-1

### CODE REVIEW

**Review by aheejin — APPROVED** [review]

**Comment by tlively** [comment]
Please revert this. It must be a bug in V8.

**Comment by kripken** [comment]
Happy to do it either way, but the spec doc linked above seems to be aligned with v8?

**Comment by kripken** [comment]
To be clear, the part of the spec I am reading is stuff like `0xfb01` which I assume means those literal bytes..? Maybe that's wrong...

**Comment by tlively** [comment]
Talked to Jakob this morning about this and we're going to switch over to using LEBs for now. It's been an established convention for years that prefixed opcodes are LEBs and if we're going to break with that convention, we will require more stakeholder buy-in first. You can see that this is how the binary format for SIMD instructions and all other prefixed instructions is specified: https://webassembly.github.io/spec/core/binary/instructions.html#vector-instructions.

**Pull request merged**
