### PR TITLE
Allow allocations on side threads

### PR DESCRIPTION
**Pull request by kripken**
Not efficiently yet, maybe we'll never need them to be efficient, but at least allow them.

### CODE REVIEW

**Comment by kripken** [comment]
Hmm, travis c++ compilers don't like unique_ptr to void*... my local compiler doesn't complain.

**Comment by jfbastien** [comment]
At that point it's better to keep a reference to the allocator on a per-thread basis, instead of locking. Each thread owns its own bump allocator, no locks.

**Comment by kripken** [comment]
Good point. Ok, now this adds a bump allocator per thread in a simple way. It still locks, could be much optimized, but since this path is very rare let's leave that for later.

**Comment by binji** [comment]
This is pretty weird; why do you need each MixedArena to know about the others? Seems like it would be better to allocate a MixedArena per thread and destroy it when the thread is destroyed. Then you don't have to modify MixedArena at all.

**Comment by kripken** [comment]
An arena might live less than the thread. More specifically, each wasm Module has an arena, and there could be multiple modules, they aren't global structures. After this patch, each module has an arena which might become a list of arenas, one per thread.

**Comment by kripken** [comment]
(But in practice, the optimizer very rarely needs to allocate nodes, instead they can be reused. So the list should not be a hot operation.)

**Comment by binji** [comment]
I see, you want to allocate memory per-thread but have it owned by the Module? I'd say a more natural way to do this is to create a new MixedArena per thread, then pass it back to the main thread when the thread is finished with its operation. The main thread would then merge in the chunks allocated by the other thread. This way there is always one owner of any MixedArena, so it can still be written as a single-threaded class.

**Comment by kripken** [comment]
Maybe I don't follow, but that sounds more complicated to me, for the following reasons. First, the thread class and thread pool classes would need to understand about arenas. This component interaction would get trickier if we could run multiple thread pools at once, or add additional background threads, etc.

Second, I don't follow how you would handle multiple arenas in action at the same time? Or did you mean to avoid that situation by having a singleton arena per thread? But we may have multiple arenas, with different lifetimes, active at once: consider linking 2 modules to another module, each with its own arena. They can't share arenas, as after linking we'd want to erase the first two modules and their arenas, but not the third.

The way this PR is written, the arena class is inherently thread-safe, and does not need special support from other components. Each arena instance is a thing that can be used safely no matter if one is single-threaded or not, and there can be any number of arenas active at once, each is entirely self-contained.

I might not understand your approach yet, though, sorry if the above is based on a misunderstanding.

**Comment by binji** [comment]
You can't hide from complexity when you start using threads. :)

What I'm suggesting is conceptually very simple. If a work item needs to give back memory, it creates a MixedArena, and when it's finished it gives it back to the creator of the work item, which can do whatever it wants with the memory. In this case it would merge the memory into its own arena.

The trouble with making MixedArena handle everything is that it pushes all the complexity into MixedArena. You now have `number of threads` locks per MixedArena, where each previous lock in the linked-list must be acquired before you can allocate anything. You can make this better using TLS, but why bother? Isn't it easier to leave MixedArena as it is, and handle the complexity of dealing with threads where it already exists (i.e. in the thread queue)?

**Comment by kripken** [comment]
> What I'm suggesting is conceptually very simple. If a work item needs to give back memory, it creates a MixedArena, and when it's finished it gives it back to the creator of the work item, which can do whatever it wants with the memory. In this case it would merge the memory into its own arena.

But what if a work item needs to allocate memory in multiple arenas? That is, if the creator of the work item has multiple arenas?

**Comment by kripken** [comment]
(Added more documentation to the MixedArena class.)

**Comment by binji** [comment]
> But what if a work item needs to allocate memory in multiple arenas? That is, if the creator of the work item has multiple arenas?

Allocate a MixedArena per module, for each work item.

What you have now doesn't really make any sense to me. What is the point of having an arena per thread if you have to walk a linked list acquiring locks to get to the arena for your thread? If you're going to lock, you might as well just have two arenas, one for the first thread (no lock), and one for every other thread (lock).

**Comment by kripken** [comment]
> Allocate a MixedArena per module, for each work item.

Sure, but how do you coordinate that? A work item would need to know about what modules are active, which is additional interaction and complexity. Right now (and in this PR) work items do not need to know anything about allocation and vice versa. And as work items get more complex (now we have a single thread pool class, later we may have more background threads, multiple pools, etc.), that separation of concerns seems very useful.

> If you're going to lock

The locks are unnecessary, I just didn't want to bother with optimizations at this early stage, and it's not a perf issue since side threads allocations are extremely rare in the design of the optimizer. But, if the locks bother you, then a lock is only needed to *append* to the linked list, which happens once per side thread per module (should be negligible). Otherwise, every other operation does not need to lock.

But again, in practice, the current code should be fine for now - it only locks on side threads, on which allocations are extremely rare. But, if you prefer, I can do the optimization to only lock when necessary here.

**Comment by binji** [comment]
> But, if the locks bother you

It's not the locks that bother me, it's the unnecessary synchronization. You're introducing threads to improve parallelism, and any synchronization you add hurts that.

I took a closer look at how you're currently doing things. How about another approach: you currently shard work by Function. Why not just have a MixedArena per `Function` stored on the module? Now ownership still hangs off the `Module`, and you never need synchronization. Any known single-threaded code can continue to allocate via the primary Module allocator.

> But, if you prefer, I can do the optimization to only lock when necessary here.
Sorry, I'm not trying to hold up your PR. Just trying to help :)

**Comment by kripken** [comment]
Once the locks here are gone, I don't think there is significant loss - main thread is still fast, and for side threads, they allocate far less, and when they do, they just look in the (short) linked list. (Only building the list takes a lock, and it happens once per core and that's it, not once per allocation.) So performance-wise, this should be near-optimal, I think.

I implemented that now in this PR. I guess I didn't realize how silly the code looked without this optimization ;) Hopefully now it looks less weird. Although I guess now I need atomic operations on next?

About arena per function: each MixedArena has some overhead, and modules can have many small functions, so I worry about having an arena allocator per function. In addition, while currently functions are the basis for parallelism, that might well change in the future (e.g., an operation might be parallel in basic blocks, or it could run parallel threads for the entire function, like a multithreaded register allocator), so I think it's safer to make MixedArena always thread-safe, as in this PR.

**Comment by binji** [comment]
> So performance-wise, this should be near-optimal, I think.

But incorrect. :)

> Although I guess now I need atomic operations on next?

Yeah, you can't read `next` outside the lock without some other kind of synchronization. There are many documents describing the issues with the double-checked locking pattern, see this for example: http://preshing.com/20130930/double-checked-locking-is-fixed-in-cpp11/.

> About arena per function: each MixedArena has some overhead, and modules can have many small functions, so I worry about having an arena allocator per function.

In the single-threaded version, just an empty `std::vector` and an `int`, 32 bytes on 64-bit machine. `Function` is 152 bytes, so not an insignificant addition. But you could make a `Chunk` struct and move `index` into that, then use a singly linked list instead of a `std::vector` to reduce that to one pointer.

> an operation might be parallel in basic blocks...

Once you do that, you're going to need more synchronization than just a thread-safe allocator. I wouldn't worry about designing for that case until you actually start doing it.

**Comment by kripken** [comment]
Thanks! I fixed the atomics.

> I wouldn't worry about designing for that case until you actually start doing it.

I agree on basic block parallelism, it's complex and I have no current plans for it. But other kinds of parallelism I can see the use for in the nearer future (like a parallel register allocator, which I'm thinking about). And more generally, binaryen is meant to be a library, which might be used in all sorts of ways. I think that having the core arena class be thread-safe, without support from external components (like the thread pool) is the safest way to do that.

**Comment by jfbastien** [comment]
I tend to agree with @binji here. Either have one allocator per-thread if memory lifetime is bound to the work item, or have the allocator in each task (e.g. each function to be optimized has one). You can mix both approaches too (you know at each allocation point how long something will live), but in the end there's no lock.

If there are locks in the allocator you're usually better off with malloc.

**Comment by kripken** [comment]
> You can mix both approaches too (you know at each allocation point how long something will live), but in the end there's no lock. If there are locks in the allocator you're usually better off with malloc.

This PR only locks ~once per thread per allocator, which is generally once per thread per module. In other words, on a 4 core machine, we are talking about 4 locks total **for the entire lifetime of that module, through all optimization passes.** In other words, the locks are essentially negligible, unless I'm missing something.

**Comment by kripken** [comment]
Let's merge this in for now. It only modifies the MixedArena class in a small way, so it's not limiting future improvements. And it's blocking 2 other PRs (improve-remove-brs and improve-simplify-locals).

If you still feel strongly that there is a better approach, then perhaps writing a PR with the alternative might help. When you suggested ideas here, I thought in my head how I would implement them, and the result seemed less good than this PR - but obviously that might be my fault ;) Maybe seeing a concrete implementation that is better would change my mind.

**Comment by binji** [comment]
[Challenge accepted!](https://gist.github.com/binji/16b9bc4a1e875b6a64663ff797456a5b)
Nothing fancy, but that's kind of the point. One neat thing is that the not-yet-filled chunks are handed back and forth between the `Module` and `Task` allocators, so it's likely they'll eventually get filled up.

**Comment by kripken** [comment]
Thanks! Ok, now I think I see more clearly what you mean.

This does look pretty nice, I admit. It is a bunch more code, though, in particular the interactions between the classes with passing around and merging the allocators. But I can see the argument that the design is clean and might be worth it. So I guess that part could go either way.

Looks like you're taking a lock a few times per task, which means per function?

A bigger concern is that you have an allocator per task, which means per function? It seems like that would lead to a great many chunks, at least one per function?

**Comment by binji** [comment]
> Looks like you're taking a lock a few times per task, which means per function?

Yeah, but that's just to manage the two queues. If that becomes highly contested, you could use a lock-free queue instead.

> A bigger concern is that you have an allocator per task, which means per function? It seems like that would lead to a great many chunks, at least one per function?

It would, but I work around that by having the main thread only queue up N*2 tasks at a time (where N is the number of threads in the pool). Since the chunks are stolen from the main thread's allocator and handed off to the thread's allocator right before they're used, you'll typically only have N*2 not-yet-filled chunks. Take a look at the sample output from that gist; you can see that it runs 200 tasks twice, but only creates 8 chunks.

**Comment by kripken** [comment]
I'm not that familiar with lock-free queues, but your main thread and worker threads need to block at some points. Doesn't that imply a mutex and locking? Or busy-wait?

Ah, I missed that about the `N*2` tasks maximum. Yes, that would make the number of extra chunks overhead on the order of cores as opposed to functions. Why not `N` btw?

**Comment by binji** [comment]
Yeah, you still would end up spin-waiting, but the overhead would be less. But honestly, it's not even worth thinking about lock-free anything until the measurement shows it's worth it. The point I was making above is that this is a required synchronization point between the main thread and the worker threads, and there are ways you can optimize it, if necessary. The allocator is not required to be synchronized, so it's nicer if you don't.

`N*2` I just grabbed from nowhere. Since the main thread is queuing up the tasks, I figured it would be nice if the worker threads had a little slack in case the main thread isn't scheduled for a bit.

**Comment by kripken** [comment]
I think in the end at least one of the two, getting tasks and doing allocations, must be coordinated. In your approach it's the tasks, while allocations are trivially lock-free, while on the other hand in mine tasks are trivially lock-free, while allocations must be coordinated.

Not fully symmetrical, though, it seems like the coordination on tasks requires blocking (spin-wait or a mutex, etc.) while coordination on allocations needs those things only until the allocator has a side allocator per thread, so after `O(number of cores)` there will never be a need for blocking.

I guess which is better depends on the usage patterns. I think there may be more tasks than side thread allocations, at least that's my goal (reuse nodes, etc.), but I might be wrong. Or I might be right now but new optimizations we write later might need more allocations and prove me wrong.

Aside from perf, I think your approach is more code, even if I do see the appeal and the design now. And it might require more code later if e.g. a task has more than one allocator (like when linking modules) or changes on the task pool side, because of the interaction between allocation and tasks.

So overall I think I still prefer the current approach, but it's close.

**Comment by binji** [comment]
> In your approach it's the tasks, while allocations are trivially lock-free, while on the other hand in mine tasks are trivially lock-free, while allocations must be coordinated.

That's not true, they're orthogonal. You can just as easily have an allocator per-thread using a callback + atomic increment method (how you're currently doing it in binaryen). Stealing chunks becomes slightly more complex, requiring a lock or CAS on the chunk linked list. I implemented tasks as a queue becomes it is the normal, simple way of doing it.

> I guess which is better depends on the usage patterns.

Yeah, ultimately I'm guessing none of this really matters, and the majority of time will be spent elsewhere. That's usually how these things work. :)

> Aside from perf, I think your approach is more code

Really? My entire example including chunk allocator, thread, thread pool and a simple task fits in 300 lines of code. In any case, I'd argue that the simplicity of the solution is more important without measurement to prove otherwise. What you have currently requires synchronization in the form of atomics, locks or condition variables in the traversal, thread, thread pool, and arena classes. What I suggested requires only a lock and CV in the queue, where synchronization is required. But let me reiterate that there's nothing special about what I've written, it's the naive, obvious way of implementing threading. Are you certain that you need to add this complexity elsewhere for performance reasons? 

Think of this from the perspective of someone who doesn't know the code as well as you do. Isn't it easier to look at code where nearly everything is known to be accessed by only one thread?

Anyway, I think we've discussed this to death, so I'll leave it at that.

**Comment by kripken** [comment]
I suspect this really comes down to differences in perceived complexity. I understand what you say about your approach being more obvious for you. For me, though, passing around allocators seems like unnecessary complexity, and it's simpler to have the allocator itself be thread-safe.

I admit you might be right that most people might find your approach more obvious. I'm not sure how to measure that. But I think you have more experience with this type of code than me, so you are perhaps more likely to be correct.

**Pull request merged**
