### PR TITLE
Improve inlining of `return_call*`

### PR DESCRIPTION
**Pull request by vouillon**
Use the previous implementation when no `return_call` is in a `try` block. This avoids moving code around (as a sibling of the caller body or the inlined body), so that should allow more local optimizations after inlining.

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Thanks, this LGTM! Have you had a chance to run the fuzzer on this? Usually running it for about 10k iterations is enough to give us confidence for a change like this.

**Comment by tlively** [comment]
Ahh, right. I was hoping to use `try_table` since that's the new standard instruction, but we should change the tests to use `try` instead because that's better supported by all the optimization passes. The fuzzer shouldn't have any issues with `try`.

**Comment by vouillon** [comment]
I did not found any issue with the fuzzer.

**Comment by tlively** [comment]
Great, thanks!

**Pull request merged**
