### PR TITLE
 Add clangd cache to .gitignore

### PR DESCRIPTION
**Pull request by MATRIXKOO**

### CODE REVIEW

**Comment by kripken** [comment]
I've never heard of this feature. Do you have a link explaining it perhaps?

**Comment by MATRIXKOO** [comment]
It's a clang tool.

clangd understands your C++ code and adds smart features to your editor: code completion, compile errors, go-to-definition and more.

clangd is a language server that can work with many editors via a plugin. 
https://clangd.llvm.org/

**Comment by MATRIXKOO** [comment]
When I build project on Vscode with clangd extension.There's cache file will be generate automatically.

**Review by kripken — APPROVED** [review]
Thanks for the info, sounds good.

**Pull request merged**
