### PR TITLE
Rename various SIMD load instructions

### PR DESCRIPTION
**Pull request by dcodeIO**
Renames the SIMD instructions

* LoadSplatVec8x16 -> Load8SplatVec128
* LoadSplatVec16x8 -> Load16SplatVec128
* LoadSplatVec32x4 -> Load32SplatVec128
* LoadSplatVec64x2 -> Load64SplatVec128
* Load32Zero -> Load32ZeroVec128
* Load64Zero -> Load64ZeroVec128

as per https://github.com/WebAssembly/binaryen/pull/3784#discussion_r610106108.

### CODE REVIEW

**Comment by dcodeIO** [comment]
There are also

* LoadExtSVec8x8ToVecI16x8
* LoadExtUVec8x8ToVecI16x8
* LoadExtSVec16x4ToVecI32x4
* LoadExtUVec16x4ToVecI32x4
* LoadExtSVec32x2ToVecI64x2
* LoadExtUVec32x2ToVecI64x2

mapping to

* `v128.load8x8_s(memarg) -> v128`: load eight 8-bit integers and sign extend each one to a 16-bit lane
* `v128.load8x8_u(memarg) -> v128`: load eight 8-bit integers and zero extend each one to a 16-bit lane
* `v128.load16x4_s(memarg) -> v128`: load four 16-bit integers and sign extend each one to a 32-bit lane
* `v128.load16x4_u(memarg) -> v128`: load four 16-bit integers and zero extend each one to a 32-bit lane
* `v128.load32x2_s(memarg) -> v128`: load two 32-bit integers and sign extend each one to a 64-bit lane
* `v128.load32x2_u(memarg) -> v128`: load two 32-bit integers and zero extend each one to a 64-bit lane

but these seem a bit odd in that they use the `v128` namespace, but it may be arguable that these may as well use the `i16x8` etc. namespaces to denote their return value, so I didn't rename these yet. Do you know why these use `v128`?

**Comment by dcodeIO** [comment]
Found this issue for reference meanwhile: https://github.com/WebAssembly/simd/issues/297. Makes sense when thinking about the common denominator being `load`s.

**Comment by dcodeIO** [comment]
Perhaps names could be:

* LoadExtSVec8x8ToVecI16x8 -> Load8x8ExtSVec128
* LoadExtUVec8x8ToVecI16x8 -> Load8x8ExtUVec128
* LoadExtSVec16x4ToVecI32x4 -> Load16x4ExtSVec128
* LoadExtUVec16x4ToVecI32x4 -> Load16x4ExtUVec128
* LoadExtSVec32x2ToVecI64x2 -> Load32x2ExtSVec128
* LoadExtUVec32x2ToVecI64x2 -> Load32x2ExtUVec128

**Comment by tlively** [comment]
That looks good to me!

**Review by tlively — APPROVED** [review]

**Pull request merged**
