### PR TITLE
[CMake] Enable sing extensions for binaryen_js wasm target

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by MaxGraey** [comment]
@kripken Could you also look at this PR? I guess `sing extension` proposal quite mature for all browsers and node LTS.

**Comment by kripken** [comment]
Any uses on the Web should be ok, I agree. For node, yes, looks like the current LTS supports this. However, are you not worried about people using something older, like a linux distro's bundled node? I think most of those are older than node LTS which was recently updated. Given that risk, I'm not sure this is worth it. But, what is the benefit, did you measure that?

**Comment by MaxGraey** [comment]
According to Chrome status sign-expensions shipped in Chrome 69 in 2018. That is, almost four years ago. I think that's quite enough. Besides, binaryen.js is mostly used in browsers and assemblyscript (where the minimum requirement is node.js 14). In all other cases the native binaryen is used.

**Comment by kripken** [comment]
> (where the minimum requirement is node.js 14)

Does node.js 14 support sign extensions?

**Comment by MaxGraey** [comment]
It should due to Node.js 14 released in 2020.

**Comment by kripken** [comment]
It's not that simple - node from 2020/4/22 uses a V8 from some earlier date, possibly months earlier. It's best to check to make sure.

And again, what benefit does this change bring? If it gives us a 10% speedup then I'm willing to take some risks, but if it is a 0.1% speedup then I doubt it's worth it.

**Pull request closed without merging**
