### PR TITLE
Update submodules while running build.sh, and make it runs well

### PR DESCRIPTION
**Pull request by TheKK**

### CODE REVIEW

**Comment by kripken** [comment]
I actually don't know git submodules that well - what do those commands do? I wouldn't want them to pull new changes from those repos, as I need to pull them manually and fix things when they break.

**Comment by jcbeyler** [comment]
Agreed, I do that manually to keep the HEAD sane. Doing it at build time is really an invitation to having issues for the user / testers / etc.

**Comment by jcbeyler** [comment]
Plus bug reports would become really annoying since each user might have a different configuration depending on what is happening in the submodules compared to what you have or will have by the time you test...

**Comment by binji** [comment]
None of those commands pull new changes, see https://git-scm.com/docs/git-submodule.

**Comment by jcbeyler** [comment]
True I read way too fast the code. The pull command would be adding new updates :)

**Comment by TheKK** [comment]
`git submodule update` won't checkout the latest commit for submodules, but stay at the commit when you add it as submodule unless you manually checkout to different commit in submodules then commit changes in binaryen.

Perhapse updating submodule in `build.sh` is not the best idea. But since files from these submodules are needed while running `check.py`, I think we should tell others to download them or help them with that.

**Comment by kripken** [comment]
I see, thanks. How about creating an `update.sh` that does this? And perhaps warn from `check.py` if those directories are not created/up to date?

On the other hand, keeping it in `build.sh` as currently done in this pull is nice for simplicity, it would just work for most people. I guess I don't feel strongly either way.

**Comment by jcbeyler** [comment]
Actually you could put an option to build.sh that does the update or not and then test for that option. At least that way you don' t have to have two different scripts, no?

It' s mostly a build time question. Every time you build you will have to wait for git to finish checking the submodules. So depending on how often you are building, you may or not start caring about this

**Comment by TheKK** [comment]
As I know binaryen is now seeking for new build system, does that means build.sh will gone in the future? If so, maybe we could just put submodule update instruction to README, otherwise adding an option to build.sh sounds nice.

**Comment by kripken** [comment]
Yeah, we need a proper build system anyhow, so build.sh will be going away, I hope ;)

So I'm ok to merge this as-is. Although, the idea of putting the info in the README instead sounds better actually.

**Comment by kripken** [comment]
Thinking some more, let's do both, I'll merge this and add it to the readme.

**Pull request merged**
