### PR TITLE
Port most passes tests to lit

### PR DESCRIPTION
**Pull request by tlively**
Using the script from #3963. Be careful to exclude metrics and fuzz-exec tests,
which have output that is not captured by the check generator script.

### CODE REVIEW

**Comment by aheejin** [comment]
image
😮🤯🤩

**Comment by kripken** [comment]
It's hard to review this as the `/files/` github page is extremely slow. How about splitting this up into smaller pieces? That would be easier in other ways as well.

**Comment by tlively** [comment]
Sure, splitting this up makes sense!

**Comment by tlively** [comment]
I'll close this in favor of the split-up approach.

**Pull request closed without merging**
