### PR TITLE
Add a -O3 test file to trigger segfault

### PR DESCRIPTION
**Pull request by maurolacy**
Related to #4136.

### CODE REVIEW

**Comment by MaxGraey** [comment]
@maurolacy As first time contributor your PR required some approval for CI workflow. You have to wait until one of the meinteiners does it.

**Comment by maurolacy** [comment]
OK. It turns out I couldn't reproduce this in `main`. It only fails in the `version_101` tag, so, it seems this is already a solved issue.

Will add a couple of scripts and instructions with the path for reproduction.

Question would be then: when `version_102` is going to be released?

**Comment by maurolacy** [comment]
Bug triggers when building statically on alpine (build script added for reference), but only in the `version_101` tag.

If `--debug` is added, segfault disappears. ?-) Dangling pointers having fun I guess.

If I build a static binary based on the alpine build, but in debian, `wasm-opt` segfaults when launched without args. More dangling pointers.

Anyway, seems this is solved / couldn't reproduce in the main branch. Will close and wait for 102 I guess?

**Comment by kripken** [comment]
Thanks for confirming. Yes, I think we can just release 102 now, I'll open a PR.

**Comment by kripken** [comment]
Ok, 102 was tagged and CI is working on builds.

**Pull request closed without merging**
