### PR TITLE
Travis: Remove build for ppc64le, it takes more than 50 minutes

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by dschuff** [comment]
Thanks!

**Comment by jirutka** [comment]
BTW is there some way how to cut the build time? Maybe omit some components, so at least some part would be built on emulated architectures?

**Comment by dschuff** [comment]
Probably; building a subset of the build targets would probably work. Binaryen has a variety of stuff; is there some use case you care more about than others? I suspect there's also possibly some refactoring that could reduce build time (moving code from headers to C++ files, or checking the CMake library targets for duplicates and fixing those).

**Comment by jirutka** [comment]
> …is there some use case you care more about than others?

I don’t know, I currently don’t use Binaryen for anything. You’d probably better know what components are more important for your users and takes more time to build.

**Pull request merged**
