### PR TITLE
vs_static_analyzer

### PR DESCRIPTION
**Pull request by juj**
Add new CMake option `-DRUN_STATIC_ANALYZER=1` to enable running Visual Studio static analyzer during build.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm. what could the benefits be here?

**Comment by juj** [comment]
The output looks like this: http://pastebin.com/SPwVTKbm

**Comment by juj** [comment]
In the above list, all `C6000` and `C28000` level warnings are from static analyzer.

**Comment by kripken** [comment]
Nice.

**Comment by juj** [comment]
Windows buildbot now runs with VS static analyzer enabled (but in warnings mode only).

**Comment by dschuff** [comment]
Cool. by the way is the emscripten waterfall down, or has the URL changed or something?

**Comment by dschuff** [comment]
Never mind, I had the old waterfall page bookmarked, and the upgrade changed the latter part of the URL. Looks good!

**Comment by juj** [comment]
There was an upgrade from buildbot 0.8 to buildbot 0.9, and that changed the URLs. The address http://clb.demon.fi:8112/ can be used to visit (like you already noticed)

**Pull request merged**
