### PR TITLE
.gitignore ninja files

### PR DESCRIPTION
**Pull request by jfbastien**
They get generated when using cmake -G Ninja.

### CODE REVIEW

**Comment by kripken** [comment]
Is this ninja thing good? Should I be using it? :)

**Comment by jfbastien** [comment]
It's ninja fast! Probably won't make a difference for now, but for LLVM it's quite significant.

**Comment by binji** [comment]
@kripken It's a pretty great build system, written originally as a GYP backend for Chromium to improve on the incremental build time. It's much more low-level than Make, and not meant to be written by hand, so it's only really used by meta build tools like CMake and GYP.

**Comment by kripken** [comment]
Interesting, thanks.

**Pull request merged**
