### PR TITLE
Update tests for upstream changes.

### PR DESCRIPTION
**Pull request by sunfishcode**
This does not update tests through the official mechanism, because the test updates need to be made in lock-step with an LLVM change, http://reviews.llvm.org/D16091 . Please advise me on the appropriate procedure for performing such changes.

Changes include:
 - the @FUNCTION symbol kind
 - .skip instead of .zero
 - the allocarray_inbounds test

### CODE REVIEW

**Comment by sunfishcode** [comment]
Also, the s2wasm parser will probably need to be updated to strip @FUNCTION symbol suffixes.

**Comment by kripken** [comment]
Can @FUNCTION be simply ignored? what information does it convey?

**Comment by sunfishcode** [comment]
It conveys that the symbol is to be resolved to a function index, rather than a linear memory address. s2wasm is probably already special-casing function symbols in direct calls, so it doesn't change anything there, but for taking addresses, `i32.const abc` is the address of a variable in linear memory, while `i32.const xyz@FUNCTION` is a function index.

**Comment by kripken** [comment]
It's not actually disambiguating anything, is it? I guess it's just for clarity? Or is it due to a backend internal thing?

**Comment by kripken** [comment]
Those commits should make all the tests pass.

**Comment by kripken** [comment]
And travis confirms. If my commits lgtm feel free to merge it.

**Comment by sunfishcode** [comment]
Ah, right, this may not be an issue for s2wasm.

When linking multiple .o files together, ELF tools have a tendency to forget which symbols are for functions and which are for data because they assume you're just going to need a virtual address in either case. Using separate relocation codes for functions and data means that the tools always know what they're supposed to do.

**Comment by kripken** [comment]
I see.

Just to confirm it's not possible to have both "foo" which is a global, and "foo@FUNCTION" which is a function, correct? (Otherwise s2wasm would need to remember where it removed "@FUNCTION".)

**Comment by sunfishcode** [comment]
That's right. There's still only a single namespace. The @-suffix syntax is just for saying "I want the linker to do something special here instead of just giving me the virtual address".

**Comment by sunfishcode** [comment]
Changes lgtm. Merging.

**Pull request merged**
