### PR TITLE
 Update call_indirect text syntax to match spec update

### PR DESCRIPTION
**Pull request by dschuff**
Function type gets its own element rather than being a part of the call_indirect
(see WebAssembly/spec#599)

### CODE REVIEW

**Comment by kripken** [comment]
lgtm but looks like the spec tests we run need to be updated too.

**Comment by binji** [comment]
This doesn't seem to support the inline format: `(call_indirect (param i32) (result i32) ...)` etc.

**Comment by dschuff** [comment]
Ah you're right; I was mostly trying to resolve the backwards
incompatibility that was causing waterfall breakage. Maybe I'll add the new
functionality in a separate change.

**Comment by dschuff** [comment]
@kripken Have our spec tests really not been updated since 2016? I was going to try to update them here but if it's been that long then it probably makes more sense to do that in a separate change because there will certainly be a lot of unrelated stuff. The script I ran to update the tests for this PR also updated our copy of the spec tests, so I could check that in for now to get the tools all compatible again. But we should probably do another pull from the spec repo to get all the new tests (and also of course we've made changes to the IR since then so it's probably worth revisiting anyway).

**Comment by kripken** [comment]
@dschuff: Well, we sort of gave up on updating them since wasm became a stack machine and things diverged. We definitely can't support a bunch of things in the upstream tests. And we don't claim to support the upstream text format at this point.

But the spec tests have been updated with various specific changes, current commit looks like it's from August 27 2017. So we might want to do that for this change.

Alternatively, do we need to update this, since we still won't be able to support the full upstream text format anyhow?

**Comment by dschuff** [comment]
Since we do support a subset of the upstream text format, I think it makes sense to make this change, so that we continue to support the same subset (instead of just an outdated subset). And probably also to make the change that @binji mentioned, since that's probably a small change too. So I updated the spec tests to their new-format equivalent.

**Pull request merged**
