### PR TITLE
wasm2js: Remove global dict arguments to asmFunc

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by MaxGraey** [comment]
Oh great. Now this [PR](https://github.com/WebAssembly/binaryen/pull/2952) can be deprecated

**Comment by sbc100** [comment]
Sorry I didn't see that.  Are you OK with this one landing?

**Comment by MaxGraey** [comment]
Yeah, I'm totally fine close my PR which really outdated already. Btw probably you could find something useful in my old PR. It will be great if at least somehow my PR comes in handy)

**Review by kripken — APPROVED** [review]
lgtm but I would verify with the emscripten test suite locally if you haven't already.

**Comment by sbc100** [comment]
Yes, tested locally and the result was: https://github.com/emscripten-core/emscripten/pull/12715

**Pull request merged**
