### PR TITLE
[OptimizeInstructions] Improve cache misses for canonicalize routines

### PR DESCRIPTION
**Pull request by MaxGraey**
Usually after first OptimizeInstructions pass we already have pretty canonicalization IR which is rarely violated by next passes, so we can improve caching by marking conditions as unlikely in canonicalize routines.

### CODE REVIEW

**Comment by MaxGraey** [comment]
### Benchmarks
`wasm-opt` for 1.5 mb input real world file.

#### main branch:

1) [PassRunner]   running pass: optimize-instructions... 0.0632812 seconds.
2) [PassRunner]   running pass: optimize-instructions... 0.0586864 seconds.
3) [PassRunner]   running pass: optimize-instructions... 0.0608243 seconds.

####  this PR branch:  
1) [PassRunner]   running pass: optimize-instructions... 0.0535724 seconds.
2) [PassRunner]   running pass: optimize-instructions... 0.0558105 seconds.
3) [PassRunner]   running pass: optimize-instructions... 0.0529371 seconds.
4) [PassRunner]   running pass: optimize-instructions... 0.0551918 seconds.

**Comment by kripken** [comment]
Interesting... this may be worth doing. Can you measure on some large things, though?

If we do this, we should probably add `BYN_UNLIKELY` as we don't want to depend on LLVM code here.

Most generally, though, it seems like every single optimization pattern in this file is unlikely - probably it finds one in a hundred or so (just a guess). So I wonder if we shouldn't annotate them all somehow. But then that would probably remove the benefit. Maybe it should be only for unreachability and things like that.

**Comment by MaxGraey** [comment]
Here another one for 4 runs. Same file (1.5 mb unoptimized wasm file)

main with -O3:

1. [PassRunner] passes took 4.17425 seconds.
2. [PassRunner] passes took 4.218 seconds.
3. [PassRunner] passes took 4.19139 seconds.
4. [PassRunner] passes took 4.15892 seconds.


this PR with -O3:

  1. [PassRunner] passes took 4.12122 seconds.
2. [PassRunner] passes took 4.09263 seconds.
3. [PassRunner] passes took 4.14114 seconds.
4. [PassRunner] passes took 4.09389 seconds.

**Comment by kripken** [comment]
I made an LTO build and tested this on some large wasm files. I actually don't see a speedup here. Maybe that's due to my CPU or some other difference?

**Comment by MaxGraey** [comment]
Perhaps it depends on what is wasm module. I assume these modules were generated by LLVM? It's just that in this case OptimizeInstruction will rarely be called I think

**Comment by kripken** [comment]
One was from LLVM, the other was a very big one from J2CL (Wasm GC from Java). But maybe you're right that both use this pass less. Do you have a link to a large AssemblyScript one perhaps?

**Comment by MaxGraey** [comment]
Yes, I used this file:
[assemblyscript.untouched.wasm.zip](https://github.com/WebAssembly/binaryen/files/7001920/assemblyscript.untouched.wasm.zip)

**Comment by kripken** [comment]
Ok, I tested a lot on that file, both doing `--optimize-instructions` by itself as well as `-O1` and `-O3` which runs it internally. I don't see a difference. Maybe certain CPUs benefit and others don't...

Maybe an argument could be made that this improves code clarity, by marking what is likely and what not. But I'm not sure that it does, myself.

**Comment by MaxGraey** [comment]
The acceleration is really very slight and will depend on the size of the cache. Well I can close this PR. Or is it better to leave only the new macros but delete everything else?

**Comment by kripken** [comment]
I think let's close it for now. The macros do look useful, but we can return to this PR when we find their first user.

**Pull request closed without merging**
