### PR TITLE
Don't create already-existing dynCalls

### PR DESCRIPTION
**Pull request by kripken**
This can happen in emscripten if we run fpcast-emu after previous passes created dynCalls already. If so, it's fine to just do nothing.

Fixes https://github.com/emscripten-core/emscripten/issues/8229

### CODE REVIEW

**Comment by sbc100** [comment]
Hmm... do we want wasm-emscripten passes to be idempotent like this?  I would have thought that calling the EmscriptenGlueGenerator in the middle of some other pass seems like a bug.  Does 
FuncCastEmulation pass really depend on this?  If so perhaps generateDynCallThunks would be better exposes as pass itself?

**Comment by kripken** [comment]
I suppose it could be a pass, true. But it's not something I see as useful by itself. We just need to ensure dynCalls exist in a few places (wasm-emscripten-finalize, and emulate-func-casts), so having it in library code that is just called from those places seems reasonable to me.

**Comment by kripken** [comment]
I also think it's reasonable for that code to handle the case with existing dynCalls - by not erroring when trying to create them. This doesn't add complexity, and makes the code usable in emulate-func-casts. Maybe there's a downside I'm missing though?

**Comment by sbc100** [comment]
I don't think I have a clear enough understanding of why emulate-func-casts needs these dynFuncs so I don't really know the correct solution.

I can imagine a user accidentally defining their own function called "dynCall_", in this case it would be better to have wasm-emscripten-finalize error our perhaps?  At least i think wasm-emscripten-finalize should be able to assume that its input has *not* yet been finalized.

Mostly it just seems strange that emulate-func-casts is doing parts of the the finalize process.  Anyway lgtm for now since this change goes intrpdude that strangeness, but fixes a real bug.

**Pull request merged**
