### PR TITLE
Fuzzing: Emit BINARYEN_PASS_DEBUG in the autoreducer scripts

### PR DESCRIPTION
**Pull request by kripken**
That env var is the one piece of global state we use.

### CODE REVIEW

**Comment by kripken** [comment]
This tries to match the conditions seen during running the fuzzer. So that when someone runs the script later they get the exact same result. The env var was set for all the commands during running the fuzzer, so that seems right, unless I don't understand you?

**Comment by tlively** [comment]
My usual workflow is to run the fuzzer without BINARYEN_PASS_DEBUG, then once I find an error I set BINARYEN_PASS_DEBUG=3 to dig in. Setting the end variable should never cause a bug to be missed, but if it catches an earlier bug that should be ok.

**Comment by kripken** [comment]
The fuzzer itself will set that flag, though - see `randomize_pass_debug()` (with low probably - this catches more bugs, but is slower). This PR makes the output script mirror that.

**Comment by tlively** [comment]
Ok, sounds good.

**Pull request merged**
