### PR TITLE
Memory access offset flag is bit 4.

### PR DESCRIPTION
**Pull request by JSStats**

### CODE REVIEW

**Comment by JSStats** [comment]
Double checked this in the v8 source code: `typedef BitField<bool, 4, 1> OffsetField;`

**Comment by kripken** [comment]
I guess I'm not sure what "bit 4" means. Is it "the fourth bit", in which case 1,2,4,8, so 8? Or is there a "bit 0" which is 1?

**Comment by binji** [comment]
It means 2**4 == 16 == 0x10. I use 0x10 in sexpr-wasm as well.

**Comment by kripken** [comment]
Cool, thanks @binji and @JSStats.

**Pull request merged**
