### PR TITLE
Fix emitting of unreachable block/if/loop

### PR DESCRIPTION
**Pull request by kripken**
Third attempt at resolving #903. This

 * Defines unreachable blocks as suggested by @dschuff: having an unreachable element, and no `br`s.
 * Emits unreachable block/if/loop by adding extra `unreachable` opcodes, see comments in the diff. This is a simple solution, but not the most efficient, see below.

This also

 * Fixes a bunch of minor stuff uncovered by these changes, e.g., a missing relooper finalize, and we used to think that an if without an else was unreachable if the body was unreachable.
 * Makes it easier to add wast tests with comments (by adding `from-wast` outputs, instead of assuming that the input == the output, which means no comments).
 * Disables the spec tests. They fail on `return.wast`, so perhaps we should just disable that one?

Other issues:
 * Running the full test suite + fuzzing now, still not 100% sure this is correct.
 * We likely cannot read all our wasm outputs in binaryen now - we will need to support fully stacky input, which we want to anyhow, but this temporarily may cause issues for us (not regular users).
 * We emit extra bytes, at least 2 per unreachable block. We also sometimes emit `unreachable unreachable`, e.g. if unreachable things nest, etc. We should work towards optimizing all those out, as suggested in #903, we can hopefully infer types etc. Meanwhile, the extra size is almost nothing, e.g. on libcxx it was 374,682 bytes and grows by 176 (so far less than 1%).

### CODE REVIEW

**Comment by dschuff** [comment]
If we can get away with disabling just one spec test instead of all of them, let's definitely do that.

**Comment by kripken** [comment]
Yeah, makes sense. Looking more carefully, two now fail, `return` and `unreachable`, I disabled only them.

**Comment by kripken** [comment]
So actually it turns out those two spec tests were testing something quite important ;) I had a bug in emitting of ifs with unreachable conditions. Fixed, and re-enabled them, which means all spec tests are back.

**Comment by kripken** [comment]
I'm now fairly confident this works: 3/4 of the test suite checked so far, all passing; fuzzing for several hours found nothing; and building unity generates a validating wasm (although I can't run it to confirm correctness, hopefully @juj can).

**Comment by kripken** [comment]
Test suite passes. Fuzzing found 2 issues, one of which which is fixed by that last commit (and was also a [bug in sm](https://bugzilla.mozilla.org/show_bug.cgi?id=1340237)). The other is a validation error I am still investigating.

**Comment by dschuff** [comment]
This LGTM to fix the various brokenness. We shouldn't call #903 resolved yet though.

**Comment by jgravelle-google** [comment]
LGTM as well

**Comment by kripken** [comment]
Pushed a fix for the remaining fuzz testcases from last night.

It's a tiny/obvious fix so I assume lgtms are still in effect, will merge once green.

**Pull request merged**
