### PR TITLE
[wasm-metadce] Consider ref.func as introducing a dependency + fix rooting of segment offsets

### PR DESCRIPTION
**Pull request by vouillon**
`wasm-metadce` could wrongly consider some functions as unused since it did not take `ref.func` into consideration.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks! This looks mostly correct to me, but reading the code around it I think I see a problem. `InitScanner` does nothing when `parentDceName` is null, so checking that does not actually do anything. And it means we have not been rooting things properly. I think we should fix that first, so that this PR can root properly.

I can look into that fix. Unless you prefer to do it?

**Comment by vouillon** [comment]
Indeed, this looked weird to me. But I did not understand the code well enough to know whether there really was a bug there. After thinking a bit more about that, I think I can write a proper fix.

**Comment by vouillon** [comment]
So, there was a typo in the initial code, which was incorrectly fixed in #4246 by not rooting the global.
I have pushed a fix and a test.

**Review by kripken — APPROVED** [review]
Thanks! Looks great.

I think we can add some helper functions and things here to simplify the code, I'll look into that in a followup.

**Pull request merged**
