### PR TITLE
WIP: Prototype OpCode Tables

### PR DESCRIPTION
**Pull request by mbebenita**

### CODE REVIEW

**Comment by mbebenita** [comment]
@lukewagner so far, the approach I took looks something like:

For each function:

1. Walk over the body of the function and construct a table of the opcodes that are used and count the occurrences. Opcodes that are more frequent will have lower indices in the opcode table. This doesn't help with compression but it's necessary so we can assign all used opcodes valid indices. Opcodes with immediates are also added to the table (as a pair opcode+immediate), but only if the immediate is lower than some set threshold. 
2. Sort the table by number of occurrences.
3. Emit function bodies as before, but use the table index instead of the original opcode number. For opcodes with immediates, if the opcode+immediate pair doesn't exist in the opcode table, encode it as before.

* I don't yet emit the tables themselves, so the results are not really valid ATM.
* I don't yet handle all opcodes.
* I don't have a way to limit the table size right now, but luckily it doesn't get too large if I limit the range of immediates.

Results (bytes, angrybots)
```
# raw
before: 12381858
after:  11402475

# gzip
before: 3972606
after:  4166769

# lzma
before: 2584020
after:  3132206
```

So far the results are not great. Uncompressed size improves if we use opcode tables, however both gzip and lzma are both worse. Things will be even worse once I actually emit the tables themselves.

Next steps / ideas:

1. Support all opcodes.
2. Emit opcode tables.
3. Try constructing a single opcode table for the entire file.
4. Opcode table hierarchy maybe?

@lukewagner I know you had better results when you last tried this. What was your approach?

For reference, the wast I am trying to encode has the following AST node counts:
```
 binary         : 740459
 block          : 183453
 break          : 56364
 call           : 166125
 call_import    : 13186
 call_indirect  : 16371
 const          : 924337
 get_local      : 1620040
 if             : 163429
 load           : 470673
 loop           : 17490
 nop            : 2068
 return         : 57224
 set_local      : 580108
 store          : 309300
 switch         : 2093
 unary          : 11946
```

**Comment by kripken** [comment]
Process-wise, I'd prefer to not merge this until there is clear consensus the spec is moving this way, is that ok?

**Comment by mbebenita** [comment]
@kripken absolutely. I am just posting this here to open up a discussion on a possible design.

**Comment by kripken** [comment]
Cool, just wanted to make sure there are no misunderstandings.

**Comment by mbebenita** [comment]
Similar work is happening on https://github.com/WebAssembly/binaryen/tree/opcode-table.

**Pull request closed without merging**
