### PR TITLE
Fix another invalid type-pun

### PR DESCRIPTION
**Pull request by jfbastien**
I thought I'd already fixed that one.

### CODE REVIEW

**Comment by kripken** [comment]
One does not just `bit_cast` into Mordor ;)

See #152, when I tried to do this, I got signalling nan bit errors on 32-bit. Still figuring out what to do in that pull.

**Comment by jfbastien** [comment]
Ah right, that's why I remembered this code getting fixed. I just didn't remember the part where it didn't land because of the bug :-)

**Comment by jfbastien** [comment]
Actually, we could also conditionalize this fix on !x86-32. That would address your immediate NaN bit issue while keeping correctness for the other platforms. WDYT?

**Comment by kripken** [comment]
After the recent merge, I think that's no longer relevant?

**Comment by jfbastien** [comment]
Agreed.

**Pull request closed without merging**
