### PR TITLE
Fix threads on 32-bit ubuntu 14.04

### PR DESCRIPTION
**Pull request by kripken**
Sadly #390 broke threads on my 32-bit ubuntu 14.04 machine. This PR restores the necessary `-pthread` command that makes things work.

I added it behind the condition added in #390, so hopefully we are still an improvement over the status before that PR. If not and OS X is still broken, perhaps we should ifdef for linux or for os x.

### CODE REVIEW

**Comment by kripken** [comment]
cc @adam852 - any idea why your pull had that effect?

**Comment by kripken** [comment]
The specific problem I see without that flag is a runtime abort when I try to use threads,

````
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)
````

**Comment by adam852** [comment]
cc @kripken - ok, I will check it.

**Comment by binji** [comment]
@kripken strange, I use the same technique in sexpr-wasm for threads, and it works fine for the i686 build on my ubuntu 14.04 laptop. See https://github.com/WebAssembly/sexpr-wasm-prototype/blob/master/CMakeLists.txt#L363. Maybe the difference is using `target_link_libraries` instead of modifying `CMAKE_EXE_LINKER_FLAGS` directly?

**Comment by kripken** [comment]
@binji: thanks, that does fix it for me. I updated this PR to do that.

**Pull request merged**
