### PR TITLE
Enable bulk memory feature for binaryen_js target

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by tlively** [comment]
What is the context for this change? Have you measured a benefit of enabling bulk memory here?

**Comment by MaxGraey** [comment]
I don't measured benefit yet, but this should reduce size and speed a little and cost nothing for portability. So I don't see any reason why this unnecessary. But if someone know potential drawbacks I could investigate more and make some benchmarks

**Comment by tlively** [comment]
I'm not sure it will help speed at all because it's basically swapping out calls to a memcpy function for calls to a function polyfilling memory.copy, which is probably no faster. It is also probably bad for size because of the extra polyfill functions that need to be added.

**Comment by MaxGraey** [comment]
Hmm, good point about codesize. But I don't think it's blow code out too much:
[wasm2js_memory_fill](https://github.com/WebAssembly/binaryen/blob/master/test/wasm2js/bulk-memory.2asm.js#L38)
[wasm2js_memory_copy](https://github.com/WebAssembly/binaryen/blob/master/test/wasm2js/bulk-memory.2asm.js#L123)
[wasm2js_memory_init](https://github.com/WebAssembly/binaryen/blob/master/test/wasm2js/bulk-memory.2asm.js#L204)

**Comment by tlively** [comment]
Right, I don't expect this change to make much of a difference, so unless we can measure some benefit, I think it would be simpler to just maintain the status quo.

**Comment by kripken** [comment]
I agree with @tlively - without a clear benefit this has just risks?

**Comment by MaxGraey** [comment]
Alright, I'll make some benchmarks which compare compilation speed of binaryen.js with and without this flag

**Comment by MaxGraey** [comment]
According to benchmarks it doesn't improve processing speed but slightly increase size of binarien.js so closing this

**Pull request closed without merging**
