### PR TITLE
Output NaN payloads only

### PR DESCRIPTION
**Pull request by jfbastien**
As discussed with @binji and @sunfish in https://github.com/WebAssembly/sexpr-wasm-prototype/issues/28

### CODE REVIEW

**Comment by kripken** [comment]
Why are the memcpys necessary?

**Comment by jfbastien** [comment]
Because it's UB to type-pun through unions otherwise. memcpy is also technically UB, but it's the only valid way to type-pun without incurring the wrath of compilers (there's a gentleperson's agreement).

**Comment by jfbastien** [comment]
I can factor it out as `bit_cast` or something if you want.

**Comment by kripken** [comment]
Oh, it's UB? I thought unions were "the way" to do it? TIL :)

If so, then actually this might be the cause of the weird intermittent bug? We might fix two things at once if you make this use the `Literal.reinterpret*` methods from `wasm.h`, and make those methods do a memcpy internally, which they don't right now.

**Comment by jfbastien** [comment]
Done.

**Comment by kripken** [comment]
Looks good. We can also use that in `Literal.reinterpret*` as mentioned, I'll do it as a followup.

**Pull request merged**
