### PR TITLE
Replace python command with python3 to compile binaryen on Linux again.

### PR DESCRIPTION
**Pull request by apoleon**
This is the fix for #1691

### CODE REVIEW

**Comment by kripken** [comment]
Thanks @apoleon!

It looks like there is no python3 in that docker image, which is causing that error.

@trzecieu I think that's your image - is the lack of python3 intentional there? If so maybe we need to install it in our CI here.

**Comment by trzecieu** [comment]
Hi @kripken, @apoleon it wasn't it's more like a base image, but indeed as Emscripten has nice python3 support I will switch to it.

**Comment by trzecieu** [comment]
Hi,
I've fixed my building scripts and added python3 to `emscripten-slim` images. 
```
➜ docker run --rm -it trzeci/emscripten-slim python3 --version
Unable to find image 'trzeci/emscripten-slim:latest' locally
latest: Pulling from trzeci/emscripten-slim
9fc222b64b0a: Pull complete 
c83a77646c07: Pull complete 
5a0d43034d7b: Pull complete 
7c1ece14290e: Pull complete 
7b4816a5faa6: Pull complete 
7fc9b6a1940b: Pull complete 
53d18c007e95: Pull complete 
9d4e29476964: Pull complete 
c1ca614584e0: Pull complete 
Digest: sha256:98caf2d2e3cf644bc03e98a3ceefcd325c0a9806ceb78eb88711fe7d417dc945
Status: Downloaded newer image for trzeci/emscripten-slim:latest
Python 3.5.3
```
So that Emscripten Slim 1.38.34+ is shipped with python3 and python2. Still managed to have a total size of 170MB which is still sweet. 
Sorry for inconvenience.

**Comment by sbc100** [comment]
So maybe if I retry the travis job it will pass now?

**Comment by trzecieu** [comment]
It will fail as I didn't set in place `sdk-incoming-64bit` tag and I was focused on the tagged releases.

**Comment by trzecieu** [comment]
Should work now:
```
➜ docker run --rm -it trzeci/emscripten-slim:sdk-incoming-64bit python3 --version
Python 3.5.3
➜ docker run --rm -it trzeci/emscripten:sdk-incoming-64bit python3 --version 
Python 3.5.3
```

**Comment by trzecieu** [comment]
Can it be re-triggered and tested?

**Pull request merged**
