### PR TITLE
Remove `-sEXPORT_ES6` + Node.js workaround for binaryen.js

### PR DESCRIPTION
**Pull request by kleisauke**
This workaround is no longer needed after commit https://github.com/emscripten-core/emscripten/commit/ce4c405700d96a0b945f4937e414fd7c114fb2a4.

### CODE REVIEW

**Comment by kripken** [comment]
cc @dcodeIO

**Comment by kleisauke** [comment]
FWIW, the CI failure in commit 217a505ade2d9290cb081b0131fb0a0da0bea655 is expected for now, I think the (temporary) commit e858ca18625d49af112b31840dc358a8981ef687 fixes that.

**Comment by kleisauke** [comment]
This is ready for review now. This PR also includes commit eec62615b16d6f01b960af5d90342c4872a7a877 to facilitate testing of a specific Emscripten branch in the future, though I can omit that change if needed.

**Review by kripken — APPROVED** [review]
Thanks!

@dcodeIO , do you want to take a look too?

**Comment by dcodeIO** [comment]
Just tried this branch compiled with Emscripten tot, seeing no issues :)

**Comment by kripken** [comment]
Great! Landing.

**Pull request merged**
