### PR TITLE
Set CMAKE_OSX_DEPLOYMENT_TARGET

### PR DESCRIPTION
**Pull request by sbc100**
This version represents that current reality although we
would like to lower this for increased compatibility. See: #4299

### CODE REVIEW

**Comment by dschuff** [comment]
Before we land this, we should make sure that this option gets properly overidden if set on the command line (since that's exactly what we are currently doing for emscripten-releases).

**Comment by sbc100** [comment]
> Before we land this, we should make sure that this option gets properly overidden if set on the command line (since that's exactly what we are currently doing for emscripten-releases).

I'm confident enough that that is how it works... if you want to double check please do but I'm tempted to just land it.

**Comment by sbc100** [comment]
> > Before we land this, we should make sure that this option gets properly overidden if set on the command line (since that's exactly what we are currently doing for emscripten-releases).
> 
> I'm confident enough that that is how it works... if you want to double check please do but I'm tempted to just land it.

See https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry

**Review by tlively — APPROVED** [review]

**Comment by dschuff** [comment]
FTR, I checked after the DEPS roll and it looks good.

**Pull request merged**
