### PR TITLE
[Wasm GC] OptimizeInstructions: remove casts leading to comparisons

### PR DESCRIPTION
**Pull request by kripken**
Comparing references does not depend on the cast, so if we are ignoring
traps we can remove them.

Noticed by @jakobkummerow

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Nice!

**Comment by kripken** [comment]
Hmm, I think I realized a bug. This has to at least keep the type an `eqref`, that is, this would be bad:
```
(ref.eq
  (ref.as_data
    (ref.func $foo) ;; not eqref! without the ref.as we won't validate
```
Of course this will trap at runtime, but we shouldn't break validation. I'll look into it...

**Comment by kripken** [comment]
Fixed. However, I don't think this could have been a problem in practice as other opts will modify such trapping expressions anyhow...

**Review by tlively — APPROVED** [review]

**Comment by kripken** [comment]
Fuzzing found no issues.

**Pull request merged**
