### PR TITLE
Use jsvu to get SpiderMonkey to test asm.js validation

### PR DESCRIPTION
**Pull request by kripken**
[jsvu](https://github.com/GoogleChromeLabs/jsvu) is an easy way to get JS VMs. This uses it to get SpiderMonkey, which is then used to check asm.js validation in the wasm2asm tests.

Those currently fail, so we should merge this only after those are fixed. We should probably make fixing those a priority. cc @froydnj

### CODE REVIEW

**Comment by froydnj** [comment]
Cool!  I'll look at removing the extraneous `return` statements next week.

**Comment by kripken** [comment]
I think the extra `return` statements would be good to remove, but the optimizer could do that for us, so if it's not easy to do in wasm2asm then we don't need to. But removing those warnings would make seeing the errors easier, though.

**Comment by froydnj** [comment]
It looks like this is all that's needed:

```diff
diff --git a/src/wasm2asm.h b/src/wasm2asm.h
index 59f2d6a..5cd757e 100644
--- a/src/wasm2asm.h
+++ b/src/wasm2asm.h
@@ -655,7 +655,8 @@ Ref Wasm2AsmBuilder::processFunction(Function* func) {
   ExpressionList* stats = isBodyBlock ?
       &static_cast<Block*>(func->body)->list : nullptr;
   bool endsInReturn =
-      (isBodyBlock && ((*stats)[stats->size()-1]->_id == Expression::ReturnId));
+      (isBodyBlock && ((*stats)[stats->size()-1]->_id == Expression::ReturnId)) ||
+    func->body->_id == Expression::ReturnId;
   if (endsInReturn) {
     // return already taken care of
     flattenAppend(ret, processFunctionBody(func, NO_RESULT));
```

which requires regenerating all the `.2asm.js` files; I'm going to wait until at least #1442 lands before putting together a PR for this.

**Comment by kripken** [comment]
> which requires regenerating all the .2asm.js files

Just wanted to make sure you're aware of `auto_update_tests.py`, which does that automatically.

**Comment by froydnj** [comment]
> Just wanted to make sure you're aware of `auto_update_tests.py`, which does that automatically.

I was not, that's super useful!  I had written a one-liner to update the tests, but it wasn't perfect; having an already-written script will make things much easier.

**Comment by froydnj** [comment]
@kripken Can you repush this to re-run CI now that multiple return statements have been fixed?

**Comment by kripken** [comment]
Done.

**Comment by kripken** [comment]
Great, after your last fixes @froydnj this PR is now green!

Any concerns or should I land this?

**Comment by froydnj** [comment]
I would have said mentioning testing with node and spidermonkey in the `README.md`, but I see there's nothing specifically mentioning `wasm2asm` there in the first place.  So I don't think we need anything there.  No other concerns from me!

**Pull request merged**
