### PR TITLE
Refactor validator API to use enums

### PR DESCRIPTION
**Pull request by kripken**
As suggested in #1204 

I may be missing something in how to use enums here - I  seem to need to cast to the enum type when I `or` two values. There's probably a better way, I think?

### CODE REVIEW

**Comment by jgravelle-google** [comment]
Rrright, the bitwise operators return `int`s, not enum types.
Some searching says there's probably *not* a simple better way: https://blogs.eae.utah.edu/jkenkel/c-bitmasks-the-mess/
From there: I think the best solution is to add something like Windows' `DEFINE_ENUM_FLAG_OPERATORS` macro to a Binaryen util header? (Either re-implement or copy: http://www.cplusplus.com/forum/general/44137/ ) That way we get around this mostly easily in the future.
I remember now running into the same problem when adding enum flags in wasm2asm, which we then changed to bitfields.

**Comment by kripken** [comment]
I guess another option is to use consts and not enums? Anyhow, I don't think it's too bad to do the cast given this API is small and not used everywhere.

**Comment by binji** [comment]
In the past I've done it this way:
```
enum BitfieldValues { Zero = 1 << 0, One = 1 << 1, Two = 1 << 2 };
typedef uint32_t Bitfield;
```

Looks like that is covered as `TestClassicMaskWithTypedef`.

**Comment by kripken** [comment]
Thanks @binji, that does look nicer. I updated it that way.

**Pull request merged**
