### PR TITLE
[C API] Add getters and setters for various expressions

### PR DESCRIPTION
**Pull request by dcodeIO**
Covers `CallRef`, `RefTest`, `RefCast`, `BrOn`, `StructNew`, `StructGet`, `StructSet`, `ArrayNew`, `ArrayInit`, `ArrayGet`, `ArraySet`, `ArrayLen`, `ArrayCopy`, `StringNew`, `StringConst`, `StringMeasure`, `StringEncode`, `StringConcat`, `StringEq`, `StringAs`, `StringWTF8Advance`, `StringWTF16Get`, `StringIterNext`, `StringIterMove`, `StringSliceWTF`, `StringSliceIter`.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Random observation: `StringNew` and `StringEncode` utilize `ptr` expressions in their linear memory variants, but have no attached memory name for multi-memory support like other such expressions.

**Review by kripken — APPROVED** [review]
Thanks!

**Comment by kripken** [comment]
I still think it would be a good idea to autogenerate these, but I haven't found the time to look into that. After this PR, perhaps there won't be a big number of new instructions for a while... so autogenerating might be less urgent. Though it could help on the JS API side.

**Comment by kripken** [comment]
> StringNew and StringEncode utilize ptr expressions in their linear memory variants, but have no attached memory name for multi-memory support like other such expressions.

Ah, I think what happened is I added these around when @ashleynh was working on multi-memories, and because they landed around the same time they don't have multi-memory support yet. That would be good to add, though not urgent I suppose.

**Pull request merged**
