### PR TITLE
Fixed missing memory_size -> current_memory in s2wasm

### PR DESCRIPTION
**Pull request by Lichtso**

### CODE REVIEW

**Comment by kripken** [comment]
@dschuff, @sunfishcode: the `llvm_autogenerated` folder has autogenerated tests from llvm, correct? are they just out of date, or does the llvm backend still emit the older form `memory_size`?

**Comment by dschuff** [comment]
It still has `memory_size` (https://llvm.org/svn/llvm-project/llvm/trunk/lib/Target/WebAssembly/WebAssemblyInstrMemory.td)

So we should fix that. I guess the semantics are the same and only the name has changed so that should be simple. More interestingly, I don't know if the `llvm_autogenerated` tests have been updated recently, so I don't know if re-generating them would also have other changes. But we should probably just go ahead and do it anyway.

**Comment by dschuff** [comment]
By the way if this is blocking someone who doesn't want to wait for a fix in LLVM we could always just accept both names temporarily, and then go back to just one when we update the tests.

**Comment by kripken** [comment]
@Lichtso: did you manually change these files, or automatically? This should probably be done automatically, and might include other changes as @dschuff says.

I'm also ok to support both temporarily if that unblocks something.

**Comment by dschuff** [comment]
I'll just go ahead and fix LLVM now.

**Comment by binji** [comment]
> So we should fix that. I guess the semantics are the same and only the name has changed so that should be simple.

It switched to returning pages. But maybe binaryen was already doing that?

**Comment by dschuff** [comment]
I thought the change to returning pages was done before already? Binaryen is already using pages anyway. (Also the implementation is apparently already called `CurrentMemory` so the renaming looks like it will only affect s2wasm anyway?)

**Comment by dschuff** [comment]
OK, LLVM and clang are fixed as of r268256

**Comment by Lichtso** [comment]
@kripken I did not rerun the autogen, just used search & replace. As dschnuff said, s2wasm is the only thing affected.

**Comment by Lichtso** [comment]
This pull request is done, but there is a new bug: #572

**Pull request closed without merging**
