### PR TITLE
Skip .weak after .type

### PR DESCRIPTION
**Pull request by tsavola**

### CODE REVIEW

**Comment by kripken** [comment]
Note that s2wasm will be deprecated eventually, as the llvm wasm backend will eventually emit a binary directly. But still worth fixing issues of course.

Do you have a testcase showing the problem here that we could add to the test suite?

**Comment by tsavola** [comment]
I get weak references when using libcxx and assigning something (traditional function or lambda) to a std::function.

It seems binaryen's test suite doesn't run the hello_libcxx test. It probably would be a large undertaking to get libcxx-dependent tests to run?

**Comment by tsavola** [comment]
```c++
#include <functional>

static void dummy() {}

int main()
{
  std::function<void()> f = dummy;
  return 0;
}
```

https://gist.github.com/tsavola/f0b36840ccf2b0639591aa7f30750498

**Comment by dschuff** [comment]
We do run the emscripten testsuite (at least the test_core part) against upstream LLVM/s2wasm on our bot (see e.g. https://wasm-stat.us/builders/linux/builds/25522/steps/Execute%20emscripten%20testsuite%20%28emwasm%29/logs/stdio). But it doesn't look like that actually builds hello_libcxx, that seems odd.

**Comment by axic** [comment]
I think this PR can be closed since #1607 s2wasm has been removed.

**Pull request closed without merging**
