### PR TITLE
Fix {i32,i64}.trunc_{s,u}/{f32,f64} in interpreter

### PR DESCRIPTION
**Pull request by binji**
Check the binary representation of the float instead of converting it to
a float first.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm, except it might be nicer to put that code in `support/`. Not sure if in `bits` or `safe_integer` though?

**Comment by binji** [comment]
I moved it to `safe_integer`, seemed to fit with the other `is*` bounds checks there.

**Comment by kripken** [comment]
Thanks, lgtm. @jfbastien?

**Comment by jfbastien** [comment]
Looks great! ty.

**Pull request merged**
