### PR TITLE
Enable LocalCSE by default?

### PR DESCRIPTION
**Pull request by kripken**
I'm not sure of the tradeoffs here - looking for feedback.

We want to enable LocalCSE by default - it shrinks J2CL output by 15% (!)
and likely will help anything that did not run through LLVM or another
optimizing compiler before. But, this is a fairly slow pass as it computes
effects and other things. On LLVM output it shrinks less than 1% but it
takes 10% longer to run. As a result, the emscripten test suite will (on
the modes we enable this) run maybe 10% slower, for small benefit, for
example.

We could in theory enable this when GC is enabled and not otherwise.
That might be a reasonable compromise, but there are non-LLVM compilers
that do not use GC (Go, AssemblyScript, Grain, off the top of my head).
Also, it would be weird to enable the pass based on that feature as the
feature isn't really needed - one weirdness is that running `wasm-opt -all`
would do more work than `wasm-opt` on the same file.

Thoughts?

### CODE REVIEW

**Comment by kripken** [comment]
Actually, nevermind the worries - I was measuring it wrong (I had ASan enabled...). Testing properly, this pass is quite fast as expected. There is no significant slowdown, and as it helps by some small amount in general, I think we should enable it as this PR suggests, in `-O3` and `-Os` and above.

**Comment by MaxGraey** [comment]
We got some optimize regressions with new local CSE or related yo this changes (I guess prev CSE handled this better?). Like  "optimize-added-constants-propagate" and "licm" passes didn't do job anymore

**Comment by MaxGraey** [comment]
new Loacal CSE in general works better. But sometimes it skip such case:
```wat
global.get $~lib/memory/__stack_pointer
local.tee $2
```
and transform it to
```wat
global.get $~lib/memory/__stack_pointer
global.get $~lib/memory/__stack_pointer
```
https://github.com/AssemblyScript/assemblyscript/pull/2029/files#diff-154bbbb1ac81c8436843f12b2625190bdd5413569867f80612dcea95fa408a44R1968

Not sure how better handle this in CSE or in simplify globals

**Comment by kripken** [comment]
Interesting @MaxGraey , can you get me a testcase that is easy to debug? The best thing would be a small .wat file with a single small function that I can run localcse on before and after the rewrite, and see the problem.

**Comment by MaxGraey** [comment]
I tried reproduced licm issue and basically got binaryen's crush on this example:
```wat
(module
 (type $i32_i32_=>_none (func (param i32 i32)))
 (memory $0 0)
 (table $0 1 funcref)
 (elem $0 (i32.const 1))
 (export "loop1" (func $module/loop1))
 (export "memory" (memory $0))
 (func $module/loop1 (param $0 i32) (param $1 i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  i32.const 0
  local.set $2
  i32.const 0
  local.set $3
  loop $for-loop|0
   local.get $3
   local.get $0
   i32.lt_s
   local.set $4
   local.get $4
   if
    local.get $2
    local.get $1
    i32.load
    i32.add
    local.set $2
    local.get $3
    i32.const 1
    i32.add
    local.set $3
    br $for-loop|0
   end
  end
 )
)
```
it doesn't relate to local-cse. Even if I comment all local-cse passes in our pipeline binaryen still crashes. But previous version worked normally

**Comment by kripken** [comment]
The diff is
```diff
--- a	2021-08-18 10:29:30.721274415 -0700
+++ b	2021-08-18 10:29:39.697370107 -0700
@@ -1,20 +1,22 @@
 (module
  (type $i32_i32_=>_none (func (param i32 i32)))
  (memory $0 0)
- (export "loop1" (func $loop-test/loop1))
+ (export "loop1" (func $module/loop1))
  (export "memory" (memory $0))
- (func $loop-test/loop1 (param $0 i32) (param $1 i32)
+ (func $module/loop1 (param $0 i32) (param $1 i32)
   (local $2 i32)
   (local $3 i32)
+  local.get $1
+  i32.load
+  local.set $1
   loop $for-loop|0
    local.get $0
    local.get $2
    i32.gt_s
    if
     local.get $1
-    i32.load
     local.get $3
     i32.add
     local.set $3
     local.get $2
     i32.const 1
```

That looks like an LICM issue, not LocalCSE?

In general, I don't think it's worth doing LICM in the tools. It increases code size (as can be seen here), and the VM will do it anyhow, so it should not affect speed.

**Comment by MaxGraey** [comment]
> In general, I don't think it's worth doing LICM in the tools. It increases code size (as can be seen here), and the VM will do it anyhow, so it should not affect speed.

This is not always the case. For example there are interpreters such as wasm3 or wasm-micro-runtime which are quite popular not only for embedded devices. And these interpreters do not have the ability to optimize loops.

> That looks like an LICM issue, not LocalCSE?

I guess it's related to recent #4059 changes. But I'm not sure

**Comment by MaxGraey** [comment]
I think I'll move this discussion to a separate issue since it is not relevant to this PR.

**Comment by kripken** [comment]
Some final measurements here: Indeed there is no real slowdown when using this pass after LLVM. LLVM has already found the CSE opportunities. So there is no harm to enable this by default.

This *does* slow down compilation of non-optimized output (say, by clang, but with -O0), by something like 4%. That is actually not mostly due to the speed of the pass itself, which is quite fast! Interestingly the issue is it makes later passes somewhat slower, as it adds more locals - which makes local-analysis passes slower. But, that is worthwhile.

**Review by tlively — APPROVED** [review]

**Pull request merged**
