### PR TITLE
Suppress leak detection in ASan builder

### PR DESCRIPTION
**Pull request by dschuff**
This should reduce most of the noise in the ASan build

### CODE REVIEW

**Comment by dschuff** [comment]
@jfbastien @flagxor Any idea why this wouldn't be working?

**Comment by jfbastien** [comment]
Huh that would be nice... Does it work locally? I didn't know about that option.

Ooh adding this would be nice too:
```
ASAN_OPTIONS="detect_leaks=1 symbolize=1 external_symbolizer_path=$SRC/third_party/llvm-build/Release+Asserts/bin/llvm-symbolizer" 
```
(well, with the right path)

**Comment by dschuff** [comment]
leak suppression worked locally for me when I set that env var. The thing I
was confused about was why the travis build of the branch didn't seem to
pick up the extra env var in .travis.yml. We could just land this and see
what happens since the bot is xfail anyway.

**Comment by jfbastien** [comment]
Yeah that sounds fine. But weird. I'd expect it to work!

**Pull request merged**
