### PR TITLE
Expose sign extension ops in Binaryen-c/.js

### PR DESCRIPTION
**Pull request by dcodeIO**
Potentially allows using them for testing purposes.

Introduces getters for the respective unary op constants in the C-API:

* BinaryenExtendS8Int32()
* BinaryenExtendS16Int32()
* BinaryenExtendS8Int64()
* BinaryenExtendS16Int64()
* BinaryenExtendS32Int64()

with the JS-API mimicing the [spec](https://github.com/WebAssembly/sign-extension-ops/blob/master/proposals/sign-extension-ops/Overview.md#new-sign-extending-operators) as usual:

* i32.**extend8_s**(value: `ExpressionRef`): `ExpressionRef`
* i32.**extend16_s**(value: `ExpressionRef`): `ExpressionRef`
* i64.**extend8_s**(value: `ExpressionRef`): `ExpressionRef`
* i64.**extend16_s**(value: `ExpressionRef`): `ExpressionRef`
* i64.**extend32_s**(value: `ExpressionRef`): `ExpressionRef`

### CODE REVIEW

**Comment by dcodeIO** [comment]
Btw., would it make sense to have passes for transforming sign extensions in either direction? If there was one to convert the new operations to something supported today, the AssemblyScript compiler could use the new instructions already instead of implementing an option on its own.

**Comment by kripken** [comment]
lgtm, thanks!

I think we also need to update the docs here? https://github.com/WebAssembly/binaryen/wiki/binaryen.js-API

**Comment by dcodeIO** [comment]
Done: https://github.com/WebAssembly/binaryen/wiki/binaryen.js-API#sign-extension-operations-

**Comment by kripken** [comment]
Oh great, thanks again :)

**Pull request merged**
