### PR TITLE
[Strings] Adopt new instruction binary encoding

### PR DESCRIPTION
**Pull request by vouillon**
See https://github.com/WebAssembly/stringref/pull/46.
This format is already adopted by V8: https://chromium-review.googlesource.com/c/v8/v8/+/3892695.
The text format is left unchanged (see https://github.com/WebAssembly/binaryen/issues/5607 for a discussion on the subject).

I have also added support for `string.encode_lossy_utf8` and `string.encode_lossy_utf8 array` (by allowing the `replace` policy for Binaryen's `string.encode_wtf8` instruction).

### CODE REVIEW

**Comment by kripken** [comment]
Thanks for the PR!

You say V8 already implemented this change - is it backwards compatible? AFAIK our state before this PR works in V8, and the linked V8 CL is quite old, so I'm surprised things have been working so far for people using Binaryen+V8...

**Comment by vouillon** [comment]
No, this changes is not backwards compatible. I investigated this because `string.new_wtf8_array replace` was not working.
Maybe they are using `string.new_wtf8 wtf8` which happens to be interpreted by V8 as instruction `string.new_utf8` followed by a `nop` (opcode 0x01)?

**Comment by kripken** [comment]
Interesting... maybe it happens to work out that way.

**Review by kripken — APPROVED** [review]
Looks right to me. I'm not 100% sure we understand why the same binaries seem to work before and after this change (that is, with v8 and binaryen using incompatible versions) but it seems like this should only help. And if we see breakage after it lands we can back it out and investigate further.

**Pull request merged**
