### PR TITLE
wasm-emscripten: Don't use debug names in implementedFunctions

### PR DESCRIPTION
**Pull request by sbc100**
implementFunctions should use the export names, not the
internal/debug name for a function.  This is especially
imported with lld where the debug names are demanagled.

implementFunctions should only contain functions that are
accessible from outside the module.  i.e. those that have
been exported.  There is no point in adding internal-only
functions to this list as they won't be accessible from
outside anyway.

Tested with emscripten using: ./tests/runner.py binaryen2

### CODE REVIEW

**Comment by kripken** [comment]
> implementFunctions should only contain functions that are accessible from outside the module. i.e. those that have been exported. There is no point in adding internal-only functions to this list as they won't be accessible from outside anyway.

This is not technically true in emscripten in general - we use `implementedFunctions` for some other things. However, it is possible none of those things matter for the wasm backend, although that surprises me. Looking in the code, the main relevant use seems to be

 * A JS library function uses `foo`.
 * `foo` was compiled.
 * `src/jsifier.js` will add `foo` to the list of exports from the wasm, so that the JS library function can access it.

An example of this is malloc being used from JS, but we export malloc by default so that works anyhow. 

I can't think of another example offhand, but there should be test suite coverage. If no tests failed for you, we can comment out that code (jsifier line 228) and run the complete asm2wasm test suite in all modes (including `other` and `browser`), it should find breakage.

> This is especially **imported** with lld where the debug names are demanagled.

:)

**Comment by sbc100** [comment]
I see.  Is jsifier.js able to somehow export a function from wasm that wan't exported at link time?  I guess it could use some kind of binaryen tool to do this?    I will take another look and also run more tests as suggest.

**Comment by kripken** [comment]
I pushed a commit to see what breaks, https://github.com/kripken/emscripten/tree/break

Seeing the breakage might help understand the issue better, I don't remember all of it...

**Comment by kripken** [comment]
Yeah, I guess for wasm we can't export something from wasm that wasn't exported anyhow. When we see what breaks we'll see what that means I guess.

**Comment by kripken** [comment]
Ah yes, so what happens is we have the `deps_info.json` infrastructure, used in `system_libs.py`: if we know a JS library function will need a C function, we must link it in first of all. And at that time we also make sure it is exported. So that jsifier code is redundant, I'll fix that later.

The other place we use `implementedFunctions` is in showing "unresolved symbol" warnings - we do that in jsifier.js since at that point we know what C code was linked in (`implementedFunctions`) and what was provided by JS libraries. Looking in the test suite, this is checked in `other`, specifically `other.test_warn_undefined` (and also `other.test_circular_libs`). Does that pass with the wasm backend with this change?

**Comment by kripken** [comment]
Great, thanks for checking!

**Comment by sbc100** [comment]
Is this OK to land?

I guess we can followup by looking that the uses of `implementedFunctions`, and removing some redundant code.

**Comment by kripken** [comment]
lgtm

**Pull request merged**
