### PR TITLE
New binaryen.js

### PR DESCRIPTION
**Pull request by kripken**
binaryen.js has been unmaintained for a while. Basically once we hit the issue with Literals being passed by value, I think - that's not easy to model using the webidl binder approach.

This changes us to use the binaryen C API, and create a JS API on top of that. Feedback on the JS API is very welcome, see [test/binaryen.js/test.js](https://github.com/WebAssembly/binaryen/blob/binaryen.js/test/binaryen.js/hello-world.js) for an idea (output is [this](https://github.com/WebAssembly/binaryen/blob/binaryen.js/test/binaryen.js/hello-world.js.txt)).

I'll add a full test for the whole API later, so far this is only tested on that hello world (feedback might change the API, so I don't want to do much more work before knowing we think it's the right approach).

### CODE REVIEW

**Comment by binji** [comment]
Cool! Just took a quick glance, but in general I think this API looks nicer to use.

**Comment by kripken** [comment]
Thanks @binji, your feedback and the poll results on twitter pointed me towards a more JSey API. I'm mostly done refactoring for that, I'll do another twitter poll after that maybe ;)

**Comment by binji** [comment]
Honestly, I don't write too much JavaScript, so I hope I didn't lead you astray. :-)

**Comment by kripken** [comment]
I found time to debug the test issues here. There were a few typo bugs in the bindings. Everything should be fixed now.

**Comment by kripken** [comment]
Added initial docs.

**Comment by kripken** [comment]
Looks like no concerns here, and this just adds new functionality (no risk of breaking existing stuff), so merging.

**Pull request merged**
