### PR TITLE
Some minor LocalGraph improvements

### PR DESCRIPTION
**Pull request by kripken**
* Remove the Action class - we just need a pointer to a get or set. This simplifies the code and saves a little memory, but doesn't seem to have any impact on speed.
 * Miscellaneous code style and comment changes.

cc @vloppin

### CODE REVIEW

**Comment by vloppin** [comment]
Only one remark about changing size_t to Index on line 101 and 108.
There these 'index' are table index and not set/get index, so it can be confusing. (Furthermore this introduce warnings in x64 targets :))

**Comment by kripken** [comment]
Interesting, which compiler do you see a warning on?

I guess those could be `size_t` as they are the size of the container there. However, we do have the assumption that the number of total wasm "things" fits in `Index`, and the number of blocks in those containers is bounded by that.

**Comment by vloppin** [comment]
> Interesting, which compiler do you see a warning on?

Sorry .. I misread typedef I read int32_t ... 

> I guess those could be size_t as they are the size of the container there. However, we do have the assumption that the number of total wasm "things" fits in Index, and the number of blocks in those containers is bounded by that.

Indeed

**Comment by kripken** [comment]
Cool, thanks, merging.

**Pull request merged**
