### PR TITLE
Bysyncify: async transform for wasm

### PR DESCRIPTION
**Pull request by kripken**
This adds a new pass, Bysyncify, which transforms code to allow unwind and rewinding the call stack and local state. This allows things like coroutines, turning synchronous code asynchronous, etc.

The new pass file itself has a large comment on top with docs.

So far the tests here seem to show this works, but this hasn't been tested heavily yet. My next step is to hook this up to emscripten as a replacement for asyncify/emterpreter, see https://github.com/emscripten-core/emscripten/issues/8561 

Note that this is completely usable by itself, so it could be useful for any language that needs coroutines etc., and not just ones using LLVM and/or emscripten. See docs on the ABI in the pass source.

### CODE REVIEW

**Comment by gabrielcuvillier** [comment]
Sounds great, I'll try this with the Doom 3 port as a replacement for Emterpretify

**Comment by kripken** [comment]
@gabrielcuvillier this isn't quite ready! No emscripten integration yet, and hasn't been tested heavily. But hopefully next week I'll finish those things.

About IndexedDB synchronously, something like that is already available with the emterpreter, see https://emscripten.org/docs/api_reference/emscripten.h.html#indexeddb (and I intend to make it work with bysyncify too).

**Comment by kripken** [comment]
Initial testing looks good on emscripten, however, I need full coroutine support to really see. Landing this as a first step meanwhile.

**Comment by gabrielcuvillier** [comment]
Ok, no issue. I'll test as soon as it is ready.

Yes, I know about those synchrounous IndexedDB functions, they are working well but does indeed require the Emterpreter. In D3 the file loading operations are done very very deeply in the code (+ D3 implement a concept of virtual filesystem on top of .pak files, that are .zips of assets), and using Emterpreter at the file read operation require to have too much stuff in the emterpreter whitelist in the end... something like more than 100 functions (omg!) :/  The performance impact starts to be seen compared to a non emterpreter build (not speaking about compilaiton time:)

**Pull request merged**
