### PR TITLE
asm2wasm i64 support

### PR DESCRIPTION
**Pull request by kripken**
Part of https://github.com/kripken/emscripten-fastcomp/pull/152, background and details there.

@dschuff: side issue, in this PR I added "legalization" to imports and exports, that is, if an import used an i64, the assumption is that the import actually has i32,i32 (since JS can't handle the i64), and we add a stub that connects things up properly. Maybe that could be useful for s2wasm too?

### CODE REVIEW

**Comment by dschuff** [comment]
That does look like it might be interesting. Can we factor that code out from asm2wasm.h into some cpp file so that it can reused?

**Comment by kripken** [comment]
Cool, yeah, I'll refactor (I just didn't want to do it if it wasn't useful anywhere else).

**Comment by dschuff** [comment]
I haven't thought about the details of how it works yet... I just like for things to be in cpp files :)

**Comment by kripken** [comment]
LegalizeJSInterface is now refactored to a cpp file under `passes/`.

**Pull request merged**
