### PR TITLE
Write each memory segment on its own line

### PR DESCRIPTION
**Pull request by jfbastien**
30k+ column files are silly.

### CODE REVIEW

**Comment by jfbastien** [comment]
Need to merge this to master, same problem as the other: it merged onto a non-master branch.

**Comment by kripken** [comment]
Oh, I didn't notice it wasn't to master. Feel free to cherry-pick the commit onto master.

**Comment by jfbastien** [comment]
Yeah my fault, I was branching off branches while github was down.

**Comment by jfbastien** [comment]
Done.

**Pull request merged**
