### PR TITLE
Introduce WASM_ALWAYS_INLINE. Initial inline some common helpers

### PR DESCRIPTION
**Pull request by MaxGraey**
Also add `WASM_LIKELY` and `WASM_UNLIKELY` macros

### CODE REVIEW

**Comment by tlively** [comment]
What are the performance benefits of this change?

**Comment by MaxGraey** [comment]
> What are the performance benefits of this change?

Could you suggest me how better bench this?

**Comment by MaxGraey** [comment]
I tested via `time ./check.py wasm-reduce` what a very rough estimation.

current PR:
```
 21.89s   94% cpu
21.67s   96% cpu
21.59s   96% cpu
21.74s   95% cpu
21.84s   95% cpu
```
master:
```
23.38s   94% cpu
24.06s   94% cpu
24.13s   94% cpu
24.25s   95% cpu
24.46s   94% cpu
24.45s   94% cpu
```

**Comment by tlively** [comment]
Oh right, the way I've been measuring performance for OptimizeInstructions has been to run

```shell
BINARYEN_PASS_DEBUG=1 wasm-opt in.wasm -o out.wasm --optimize-instructions
```

`BINARYEN_PASS_DEBUG` prints timing information for each pass, so I've been measuring the times just to run OptimizeInstructions. Any large binary will work, but I've attached the 1.3MB binary I've been using.


[wasm.zip](https://github.com/WebAssembly/binaryen/files/5252425/wasm.zip)

Also, it would be good to change only one part of the code at a time so we can get separate performance measurements. I think starting with just the expression matching code would be good.

**Comment by MaxGraey** [comment]
> Also, it would be good to change only one part of the code at a time so we can get separate performance measurements. I think starting with just the expression matching code would be good.

Sure! Roll back other changes

**Comment by MaxGraey** [comment]
> Oh right, the way I've been measuring performance for OptimizeInstructions has been to run
> BINARYEN_PASS_DEBUG=1 wasm-opt in.wasm -o out.wasm --optimize-instructions
> wasm.zip

Hmm, on my machine (OSX) `wasm-opt` from master and  wasm inside `wasm.zip` segfolted (67185 segmentation fault)

**Comment by tlively** [comment]
> Hmm, on my machine (OSX) `wasm-opt` from master and wasm inside `wasm.zip` segfolted (67185 segmentation fault)

Yikes! I just tested locally with `master` and it works fine. Maybe you've found a MacOS-specific bug? Are you able to run other tools like `wasm-dis` on the binary? How far does wasm-opt get when you run with BINARYEN_PASS_DEBUG=1?

**Comment by MaxGraey** [comment]
> How far does wasm-opt get when you run with BINARYEN_PASS_DEBUG=1?
It segfolt immediately with and without `BINARYEN_PASS_DEBUG=1` or any other arguments which little bit strange

**Comment by MaxGraey** [comment]
Hmm, `wasm-opt` works only inside `binaryen/bin` directory. When I move it to different place it just broke. I thought it use static linking for MacOS

**Comment by MaxGraey** [comment]
So my results:

input file:
[as.wasm.zip](https://github.com/WebAssembly/binaryen/files/5252689/as.wasm.zip)

`BINARYEN_PASS_DEBUG=1 ./wasm-opt as.wasm -o out.wasm --optimize-instructions --enable-mutable-globals`

average time for "PR": `0.02852s`
average time for "master": `0.0297176s`
for 7 runs

**Comment by tlively** [comment]
Yeah, I think the benefits are probably not worth the extra code verbosity. Thanks for looking into this, though!

**Pull request closed without merging**
