### PR TITLE
Generate emscripten dynCall thunks in s2wasm

### PR DESCRIPTION
**Pull request by dschuff**
Part of the usual emscripten glue for asm.js is thunks for calling
functions on the module given a function pointer; aka a dynCall. This is
implemented via thunks generated on the Module called
'dynCall_<signature>'. This gives support to s2wasm to generate these
thunks in the wasm module along with other emscripten glue. It also
introduces a flag to s2wasm to make generation of emscripten glue
optional.

### CODE REVIEW

**Comment by dschuff** [comment]
I guess we'll have to merge https://github.com/kripken/emscripten/pull/4245 and update the emscripten submodule revision before all the tests will work here, correct?

**Comment by kripken** [comment]
Yes, we need to do some coordination here.

lgtm. How about if we land this as follows:

1. Merge this squashed but *without* the tests. So no tests are broken.
2. Land the emscripten side fix (we can't land that first, or emscripten's test suite could be broken).
3. Make a new PR that pulls in that emscripten + enables the new tests here.

Sound ok?

**Comment by kripken** [comment]
On second though, that seems like extra work - let's just tolerate some failure on the emscripten side.

I landed the emscripten PR, so this should pass tests with a submodule update.

**Comment by dschuff** [comment]
OK, binaryen tests passed locally for me. Will see about travis.

**Comment by dschuff** [comment]
Binaryen tests pass. I guess now we just need to update the binaryen version in emscripten?

**Comment by kripken** [comment]
Yes. I can do that.

**Pull request merged**
