### PR TITLE
Function table function indexes are an index into the function excluding the imports.

### PR DESCRIPTION
**Pull request by JSStats**

### CODE REVIEW

**Comment by kripken** [comment]
Are you sure? My understanding is that we *can* add an import to the table.

**Comment by JSStats** [comment]
@kripken Yes, pretty sure this is how the v8 encoding works a present. Perhaps the wasm spec allows an import in the function table? If so then how can this conflict be resolved?

**Comment by kripken** [comment]
Do you mean the implementation, or the spec?

I believe binaryen does what the spec says (but I could be wrong on that). And I think binaryen should follow the spec and not another implementation (which might have a bug).

cc @titzer

**Comment by JSStats** [comment]
@kripken This whole exercise seems to be to get something work using the v8 encoding fwiw, and then iterate. Can we follow v8 for now to get things working, and separately explore this grey area?

**Comment by kripken** [comment]
I'm sorry, I still do not understand. There is "the v8 binary spec", and there is "the v8 implementation of that spec". Which of the two do you mean, when you say "v8"?

**Comment by JSStats** [comment]
@kripken The implementation. The spec wording is 'index into the function segment entries, referencing a function', and perhaps the final qualification was intended to communicate that the imports and exports are excluded in this index.

**Comment by kripken** [comment]
I don't think we should follow the v8 implementation - we should follow the spec (implementations can have bugs, and are not meant to be readable as specs are, etc.). If this is a spec bug, let's fix that. @titzer is already cc'd so lets see what he thinks.

The spec uses "function" to refer to all types of functions, including imports, in multiple places. That's why I think it's clear it allows imports to be in tables.

**Comment by JSStats** [comment]
1. The implementation, the v8 source code, and their sexp converter, use an index into the functions excluding the imports.

2. The v8 design spec, the documentation, notes the wording 'index into the function segment entries, referencing a function'.

It appears a consistent interpretation of the spec. I think we should use the implementation except perhaps in edge cases, but this is not an edge case, it's a very clear and a common path. There are probably also tests in the v8 source that define the expected interpretation. Writing clear documentation can be a challenge so such areas can be expected to need further qualification, so it should not be take literally.

**Comment by jfbastien** [comment]
Let's just see what @titzer and @binji say. Either way is easy to go, they'll be able to reconcile the inconsistency.

**Comment by titzer** [comment]
I think we should move the relevant parts of encoding into BinaryFormat.md
and update it to be consistent with the implementation. Then we can iterate
on the BinaryFormat.md and keep implementations up to date with that.

**Comment by titzer** [comment]
As for the unified index space, that was easier in the implementation but I
don't think we fully resolved that issue in the design. I'm happy to update
both the spec and implementation when we make a decision to have a separate
index for imports or not.

**Comment by JSStats** [comment]
@titzer The index space issue is a difference between call_indirect and call_function. V8 function tables are indexes into only the functions excluding the imports, whereas call_function has an index space including both functions and imports. Can you confirm that the wording in the spec follows the implementation?

**Comment by weilianglin** [comment]
In V8 binary format, functions and imports should share the same index space. Function table is encoded like below
[kDeclFunctionTable, func_table_count, function_index1, function_index2, ...].   // index into the functions segment entries. 

For call_indirect opcode, its encoding is like
CallIndirect, func_signature_index, index_inside_func_table

Thanks
-Weiliang

**Comment by JSStats** [comment]
@weilianglin Thank you. I know what the v8 implementation does, and this PR is to align the binaryen tool with this, but there is also a v8 design specification which specifies the table index is an 'index into the function segment entries, referencing a function'. I seems a consistent interpretation to me, but other people want some extra confirmation. So it might help so get an answer from @titzer just to confirm that these are consistent and that the v8 implementation is the correct interpretation of the design spec and not a bug?

**Comment by titzer** [comment]
Weiliang is correct. All functions (including imports) are within one index
space which is indexed into by call opcodes and the indirection function
table.

In the future I think a separate dedicated import table makes sense, in
which case we should probably separate the index spaces.

**Comment by JSStats** [comment]
@titzer Thank you. So the bug is in sexpr-wasm-prototype. Here's a test I used to convince myself:

```
;;; EXE: test/run-d8.py
(module
  (type $i_v (func (param i32)))
  (import $print_i32 "stdio" "print" (param i32))
  (import $print_i32_i32 "stdio" "print" (param i32 i32))
  (func $test (result i32)
    (call_indirect $i_v (i32.const 0) (i32.const 400))
    (return (i32.const 1)))
  (export "test" $test)
  (table $test)
)
(;; STDOUT ;;;
400
test() = 1
;;; STDOUT ;;)
```

Here's the table section produced by sexpr-wasm-prototype:
```
0000030: 05                                         ; WASM_SECTION_FUNCTION_TABLE
0000031: 01                                         ; num function table entries
0000032: 0000                                       ; function table entry
0000034: 06                                         ; WASM_SECTION_END
```

This is what confused me, the `$test` function in the table is mapped to index 0. If this were correct then I believe the above example would loop, but it actually seems to call `$print_i32` which is index 0 in the combined function index space. Sorry for the noise.

**Comment by binji** [comment]
@JSStats There is a bug in sexpr-wasm-prototype, that example should fail with a signature mismatch (tested in the spec interpreter):
```
test3.wast:7.25-7.38: indirect call signature mismatch
```

OTOH, the test in your CL to sexpr-wasm-prototype fails in the spec interpreter:
```
;;; EXE: test/run-d8.py
(module
  (type $i_v (func (param i32)))
  (import $print_i32 "spectest" "print" (param i32))
  (import $print_i32_i32 "spectest" "print" (param i32 i32))
  (func $test (result i32)
    (call_indirect $i_v (i32.const 0) (i32.const 400))
    (return (i32.const 1)))
  (export "test" $test)
  (table $print_i32)  ;; NOTE: references an import
)
(;; STDOUT ;;;
400
test() = 1
;;; STDOUT ;;)
```
This fails with the following error:
```
test.wast:10.10-10.20: unknown function $print_i32
```
You were right the first time, the spec interpreter does not allow a table to include references to imported functions; they are in a different index space. Makes sense, at least with the way things are currently defined:
```
(module
  (import $import0 "foo" "bar")
  (func $func0)
  (func
    (call 0) ;; calls $func0
    (call_import 0) ;; calls $import0
  ) 
  (table 0) ;; references $func0. If we could reference imports, what would the index of import0 be?
)
```

**Pull request closed without merging**
