### PR TITLE
[asmjs] Use native Math.trunc

### PR DESCRIPTION
**Pull request by MaxGraey**
Do we need polyfill for IE <= 11 ?

### CODE REVIEW

**Comment by MaxGraey** [comment]
However I'm not sure we even need polyfill for IE due to asm2js already used `Math.clz32` which doen't support in IE. Thought?

@kripken @sbc100

**Review by kripken — APPROVED** [review]
I think we don't need a polyfill here, as you said, someone can add polyfills for the various things later, to the output.

In general this looks good, but I am not 100% sure what happens with NaNs - wasm semantics are more strict, but I think that doesn't matter anyhow for JS which can canonicalize NaNs...

**Comment by kripken** [comment]
Oh, btw, it's "wasm2js" and not "asmjs" - we don't emit valid asm.js anymore (but it is similar).

**Comment by MaxGraey** [comment]
> Oh, btw, it's "wasm2js" and not "asmjs" - we don't emit valid asm.js anymore (but it is similar).

Yes, I know. I just got used to calling it that)

**Pull request merged**
