### PR TITLE
Reland "Fix renaming in FixInvokeFunctionNamesWalker (#2513)"

### PR DESCRIPTION
**Pull request by sbc100**
In the previous iteration of this change we were not calling
`renameFunctions` for each of the functions we removed.

The problem manifested itself when we rename the imported function to
`emscripten_longjmp_jmpbuf` to `emscripten_longjmp`.  In this case the
import of `emscripten_longjmp` already exists so we remove the import of
`emscripten_longjmp_jmpbuf` but we were not correclty calling
renameFunctions to handle the rename of all the uses.

Add an additional test case to cover the failures that we saw on the
emscripten tree.

### CODE REVIEW

**Comment by aheejin** [comment]
Please check if binaryen_js build runs OK before landing

**Comment by sbc100** [comment]
> Please check if binaryen_js build runs OK before landing

Is that not part of the CI?   I see travis-emcc-tests.sh is run by travis, is that not good enough?

**Comment by aheejin** [comment]
Not sure why, but I think the CI tests with fastcomp? The previous version of this PR broke binaryen.js build with the wasm backend.

**Comment by sbc100** [comment]
I think maybe its because the travis-emcc-tests.sh uses used the emsdk docker image to do the build, and that will end up using binaryen docker, which won't include any of the change in the PR.

I'll give it a go building locally.

**Comment by sbc100** [comment]
Verified both the failure and the fix!

**Comment by kripken** [comment]
Looks like this failed on the roll again, https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket.appspot.com/8893506903952624672/+/steps/Emscripten_testsuite__upstream__other_/0/stdout

**Comment by rohitsaini1995** [comment]
Any progress on this.?

**Comment by sbc100** [comment]
I'm going to revert once again until I can debug this.

**Comment by rohitsaini1995** [comment]
Is anyone looking into this. Is it possible to know the estimated time for it's fix.?

**Comment by aheejin** [comment]
@rohitsaini1995 I think this was already reverted in #2576.

**Comment by rohitsaini1995** [comment]
@aheejin Actually I am asking about fix of this https://github.com/emscripten-core/emscripten/issues/9950 which is dependent on this binaryen fix , I think.. #2576 is the revert commit I think, not the fix commit.

**Pull request merged**
