### PR TITLE
Don't allow tsan to fail

### PR DESCRIPTION
**Pull request by jfbastien**
Shoulnd't timeout anymore.

### CODE REVIEW

**Comment by jfbastien** [comment]
Let's see if this works!

**Comment by kripken** [comment]
Don't you need to update the waterfall too?

**Comment by jfbastien** [comment]
> Don't you need to update the waterfall too?
[Ninjas sneak things in](https://github.com/WebAssembly/binaryen/commit/e61a73d633769473e26d534bd7cac26d7891ef19). ;-)

**Comment by jfbastien** [comment]
Worked!

**Comment by kripken** [comment]
Woohoo!

**Pull request merged**
