### PR TITLE
wasm-split: accept file in keep-funcs/split-funcs

### PR DESCRIPTION
**Pull request by caiiiycuk**

### CODE REVIEW

**Comment by caiiiycuk** [comment]
Sure! However I am trying to run existing wasm-split  test but they fail (even on untouched main).
```sh
python3 check.py lit

FAIL: Binaryen lit tests :: wasm-split/basic.wast (149 of 158)
******************** TEST 'Binaryen lit tests :: wasm-split/basic.wast' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/caiiiycuk/sdk/binaryen/bin/wasm-split /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --export-prefix='%' -g -o1 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.1.wasm -o2 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.2.wasm -v 2>&1      | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-NONE
: 'RUN: at line 3';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.1.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-NONE-PRIMARY
: 'RUN: at line 4';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.2.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-NONE-SECONDARY
: 'RUN: at line 6';   /home/caiiiycuk/sdk/binaryen/bin/wasm-split /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --export-prefix='%' -g -o1 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.1.wasm -o2 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.2.wasm --keep-funcs=foo -v 2>&1      | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-FOO
: 'RUN: at line 8';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.1.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-FOO-PRIMARY
: 'RUN: at line 9';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.2.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-FOO-SECONDARY
: 'RUN: at line 11';   /home/caiiiycuk/sdk/binaryen/bin/wasm-split /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --export-prefix='%' -g -o1 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.1.wasm -o2 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.2.wasm --keep-funcs=bar -v 2>&1      | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-BAR
: 'RUN: at line 13';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.1.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-BAR-PRIMARY
: 'RUN: at line 14';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.2.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-BAR-SECONDARY
: 'RUN: at line 16';   /home/caiiiycuk/sdk/binaryen/bin/wasm-split /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --export-prefix='%' -g -o1 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.both.1.wasm -o2 /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.both.2.wasm --keep-funcs=foo,bar -v 2>&1      | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-BOTH
: 'RUN: at line 18';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.both.1.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-BOTH-PRIMARY
: 'RUN: at line 19';   /home/caiiiycuk/sdk/binaryen/bin/wasm-dis /home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.both.2.wasm | filecheck /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast --check-prefix KEEP-BOTH-SECONDARY
--
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-split" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--export-prefix=%" "-g" "-o1" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.1.wasm" "-o2" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.2.wasm" "-v"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-NONE"
$ ":" "RUN: at line 3"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-dis" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.1.wasm"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-NONE-PRIMARY"
$ ":" "RUN: at line 4"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-dis" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.2.wasm"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-NONE-SECONDARY"
$ ":" "RUN: at line 6"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-split" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--export-prefix=%" "-g" "-o1" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.1.wasm" "-o2" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.2.wasm" "--keep-funcs=foo" "-v"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-FOO"
$ ":" "RUN: at line 8"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-dis" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.1.wasm"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-FOO-PRIMARY"
$ ":" "RUN: at line 9"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-dis" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.foo.2.wasm"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-FOO-SECONDARY"
$ ":" "RUN: at line 11"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-split" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--export-prefix=%" "-g" "-o1" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.1.wasm" "-o2" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.2.wasm" "--keep-funcs=bar" "-v"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-BAR"
$ ":" "RUN: at line 13"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-dis" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.1.wasm"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-BAR-PRIMARY"
$ ":" "RUN: at line 14"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-dis" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.bar.2.wasm"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-BAR-SECONDARY"
$ ":" "RUN: at line 16"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-split" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--export-prefix=%" "-g" "-o1" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.both.1.wasm" "-o2" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.both.2.wasm" "--keep-funcs=foo,bar" "-v"
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-BOTH"
# command stderr:
/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast:120:20: error: KEEP-BOTH-NEXT: expected string not found in input
;; KEEP-BOTH-NEXT: Splitting out functions:{{$}}
                   ^
<stdin>:3:1: note: scanning from here
Splitting out functions: 
^

Input file: <stdin>
Check file: /home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast

-dump-input=help explains the following input dump.

Input was:
<<<<<<
          1: warning: not splitting any functions out to the secondary module
          2: Keeping functions: bar, foo
          3: Splitting out functions: 
next:120     X~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
>>>>>>

error: command failed with exit status: 1

-- 
```

Can you give any advice? Looks like filecheck expects something different. I tried FileCheck-[9,10,11,12] - same results.

**Comment by caiiiycuk** [comment]
If i replace 
```
;; KEEP-BOTH-NEXT: Splitting out functions:{{$}}
```
with 
```
;; KEEP-BOTH-NEXT: Splitting out functions: {{$}}
```
(added space)

seems test start working, however I am not sure is it correct or not, or why it not working as is

**Comment by tlively** [comment]
Hmm, strange. What OS are you on? Did you install filecheck from requirements-dev.txt?

**Comment by caiiiycuk** [comment]
Nope, this helps. Thank you.

**Comment by caiiiycuk** [comment]
Done. I also want to add test for case when file didn't exists. But no luck. I added this test:
```
;; RUN: wasm-split %s --export-prefix='%' -g -o1 %t.none.1.wasm -o2 %t.none.2.wasm --keep-funcs=@failed-to-open.txt -v 2>&1 \
;; RUN:     | filecheck %s --check-prefix FAILED-TO-OPEN

;; FAILED-TO-OPEN: Failed opening 'failed-to-open.txt'
```

But test fail:
```
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "/home/caiiiycuk/sdk/binaryen/bin/wasm-split" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--export-prefix=%" "-g" "-o1" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.1.wasm" "-o2" "/home/caiiiycuk/sdk/binaryen/test/wasm-split/Output/basic.wast.tmp.none.2.wasm" "--keep-funcs=@failed-to-open.txt" "-v"
note: command had no output on stdout or stderr
error: command failed with exit status: 1
$ "filecheck" "/home/caiiiycuk/sdk/binaryen/test/lit/wasm-split/basic.wast" "--check-prefix" "FAILED-TO-OPEN"

--
```

**Comment by tlively** [comment]
Add “not” before the wasm-split invocation that you expect to fail to invert the process’s return code.

**Comment by caiiiycuk** [comment]
Done

**Review by tlively — APPROVED** [review]
Excellent, thanks for doing this :)

**Comment by caiiiycuk** [comment]
clang-format is applied

**Review by tlively — APPROVED** [review]

**Pull request merged**
