### PR TITLE
[NFC] Remove excessive debugging from binary reading

### PR DESCRIPTION
**Pull request by kripken**
We were doing a debug logging for every LEB byte. It turns out that the
`isDebugEnabled()` calls are expensive when called so frequently: in a
release+assertion build, even with debug disabled, these checks are the
highest thing in the profile. This PR removes the checks, which makes
binary reading 12% faster.

Perhaps we could keep some of the logging, e.g. for section headers,
but to be honest I can't say I've used any of this logging since the very
early days of wasm when the MVP spec was changing the binary format
a lot. Does anyone else use it? cc @tlively @aheejin

### CODE REVIEW

**Review by aheejin — APPROVED** [review]
No I have never used it myself. Removing sounds good to me.

>  This PR removes the checks, which makes binary reading 12% faster.

Wow.

**Review by tlively — APPROVED** [review]
Removing this SGTM. FWIW I know the interpreter is another place with a lot of optional logging I never use.

**Comment by sbc100** [comment]
Isn't the idea the the whole BYN_DEBUG macro expands to nothing in release builds?

**Comment by sbc100** [comment]
Out of interest, how significant is the cost of reading the binary in the average call to wasm-opt?

**Comment by kripken** [comment]
> Isn't the idea the the whole BYN_DEBUG macro expands to nothing in release builds?

They expand to nothing in release builds, yes, but remain in release+asserts builds and in debug builds.

We do use release+assert builds most of time IIANM - it's the default for local builds (which is what I use all the time and I assume others?). Emscripten builds use it aside from LTO release builds.

> Out of interest, how significant is the cost of reading the binary in the average call to wasm-opt?

It can be significant in a big file. Something like 1 second per 10MB of wasm, so 1-4 seconds for things like game engines, large WasmGC projects, etc.

**Comment by sbc100** [comment]
> > Isn't the idea the the whole BYN_DEBUG macro expands to nothing in release builds?
> 
> They expand to nothing in release builds, yes, but remain in release+asserts builds and in debug builds.
> 
> We do use release+assert builds most of time IIANM - it's the default for local builds (which is what I use all the time and I assume others?). Emscripten builds use it aside from LTO release builds.
> 

I wonder if we should change that instead?   I also use `release+asserts` build of LLVM in my normal workflow and I do enable logging all the time, so maybe we designed this system to match LLVM?   Do we want to just remove the BYN_DEBUG stuff in `release+asserts` builds?   Maybe not...

> > Out of interest, how significant is the cost of reading the binary in the average call to wasm-opt?
> 
> It can be significant in a big file. Something like 1 second per 10MB of wasm, so 1-4 seconds for things like game engines, large WasmGC projects, etc.

But how significant is that compared the total cost of wasm-opt including the all the passes and the output writing?

**Comment by kripken** [comment]
> I also use release+asserts build of LLVM in my normal workflow and I do enable logging all the time, so maybe we designed this system to match LLVM? Do we want to just remove the BYN_DEBUG stuff in release+asserts builds? Maybe not...

I do agree we should keep logging in general. But logging on every single LEB read is far too much, I think - it's slow and not useful.

> But how significant is that compared the total cost of wasm-opt including the all the passes and the output writing?

If you run `-O3` then it is a small fraction of the total time, yeah, but it helps a lot more in other cases. E.g. Emscripten will invoke `wasm-opt` just to minify imports and exports, and there are other tools like wasm-merge and wasm-split, all of whom read the binary and do far less work than `-O3`.

**Comment by sbc100** [comment]
Fair enough, LGTM.

**Pull request merged**
