### PR TITLE
Function section has the flags before the signature index.

### PR DESCRIPTION
**Pull request by JSStats**
Design document seems to have this backyards compared with the v8 implementation.

### CODE REVIEW

**Comment by kripken** [comment]
The current implementation matches the v8 spec document, which I think makes more sense to do. Since we may have multiple such implementations and want to verify them against each other. If we want to change this, let's change the spec first. So I don't think we should do anything here in binaryen currently.

**Comment by titzer** [comment]
I've updated the spec to match the v8 implementation (i.e. decl flags
first).

**Comment by kripken** [comment]
Ok good, then let's merge this.

**Pull request merged**
