### PR TITLE
Binary 0xd changes

### PR DESCRIPTION
**Pull request by dschuff**
* Renumber opcodes
* Unify type encodings
* Add reserved flags fields to host and call_indirect instructions

### CODE REVIEW

**Comment by dschuff** [comment]
Probably should wait to merge until the rest of the repos.

**Comment by kripken** [comment]
lgtm, nice.

**Comment by kripken** [comment]
For the commit right before merging this, we should add a `binary_0xc` tag (like we have for 0xb).

**Comment by kripken** [comment]
What is the issue with `binary.wast`?

**Comment by dschuff** [comment]
It expects version 0xc of course😁

**Comment by rossberg-chromium** [comment]
Or you use the `binary-0xd` branch of the spec. :)

**Comment by dschuff** [comment]
Right, the problem with that is that is what I mentioned in the commit log; namely that the wast parser doesn't support the new syntax for the import tests, `(register "test")`. So I decided I'd rather disable the trivial binary test than the nontrivial import test.

**Comment by rossberg-chromium** [comment]
@dschuff, I'm confused, that syntax is not new on the branch.

**Comment by dschuff** [comment]
https://github.com/WebAssembly/spec/blob/binary-0xd/interpreter/test/imports.wast#L18

**Comment by dschuff** [comment]
Oh sorry, I read "not on the new branch" rather than "not new on the branch".
So I think the issue is that binaryen has the testsuite mirror repo as a submodule, and it is out of date. I added a binary-0xd branch to that, but it also includes the new syntax.

**Comment by rossberg-chromium** [comment]
Ah, I see, thanks. Btw, please let me know when you are fine with merging WebAssembly/spec#366. It sounds like it won't immediately affect you then.

**Comment by dschuff** [comment]
Yeah; I just commented on the v8 0xd patch (which just landed) and synced with Ben and the rest of the toolchain folks, and I think everything is ready. I've tested binaryen and wabt against v8, and AFAIK 0xd has landed in firefox too, so I'm going to go ahead and merge this.

**Pull request merged**
