### PR TITLE
Update wasm.js

### PR DESCRIPTION
**Pull request by dschuff**
There have been several changes to wasm-js.cpp since its last update.

### CODE REVIEW

**Comment by dschuff** [comment]
I think this is right? If you want you can regenerate it locally and make sure my asm output matches yours.

**Comment by kripken** [comment]
Probably fine, but what version/branch did you use to build it?

**Comment by dschuff** [comment]
incoming branch of emscripten, master branch of binaryen.

**Comment by dschuff** [comment]
maybe i should use a release version of emscripten?

**Comment by kripken** [comment]
No, that should be fine, it's what I do.

**Pull request merged**
