### PR TITLE
DWARF: Handle empty debug_loc spans properly

### PR DESCRIPTION
**Pull request by kripken**
If there is an empty span (x, x), then we must be careful not to emit
(0, 0), as that would be interpreted as an end marker. To avoid
that, decrease the base so that the relative result's identical start
and end will be != 0.

That is, for example the list
```
-1, 3
4, 4
```
means "the base is 3, and the span after it is (7, 7). Since
we recompute the base as of #2936 we used to emit
```
-1, 7
0, 0
```
using a maximal base of 7. But then the 0, 0 pair looks like
an end marker. Instead, emit
```
-1, 6
1, 1
```

### CODE REVIEW

**Comment by dschuff** [comment]
wouldn't it be simpler just to omit those spans entirely? Or would that just mean we'd have to rewrite a bunch of other offsets elsewhere?

**Comment by kripken** [comment]
Yes, we don't omit anything in debug_loc so that offsets into the section remain valid.

If necessary we could rewrite the entire section and update all offsets, but that seems like more work - it is getting more appealing though given the corner cases, I admit...

**Comment by dschuff** [comment]
or backing up, it seems odd to me that we are arbitrarily changing the base to a location that doesn't really have any meaning (e.g. it probably points to some random byte in the function declaration, right?)
I guess another option would be to notice the (0,0) and just rewrite it to some other number. But maybe it doesn't really matter, if changing the base is easier.

**Comment by kripken** [comment]
Yeah, I think your idea is simpler actually, and handles another case I hit meanwhile, good point. I opened https://github.com/WebAssembly/binaryen/pull/2940

**Comment by kripken** [comment]
Closing in favor of that other PR.

**Pull request closed without merging**
