### PR TITLE
Update i64 stores for 0xc

### PR DESCRIPTION
**Pull request by jgravelle-google**
Stores no longer return a value, so we should check shorter bytes based on the width of the stored value.

### CODE REVIEW

**Comment by dschuff** [comment]
Can you add a test (maybe in `memops.s`)?
Also in the commit description, maybe make it "width of the store" or "width of the stored value" rather than "width of the instruction"

**Comment by kripken** [comment]
As this isn't `.s` specific, please also add a test in `test/unit.wast` or `test/kitchen_sink.wast` (then run `./auto_update_tests.sh` and see the test outputs are correct).

**Comment by jgravelle-google** [comment]
Turns out there were autogenerated llvm tests that cover this, that we updated incorrectly with the 0xc changes.

I could add tests to unit.wast, but they'd basically be a copy+paste of the tests in i64-load-store-alignment.wast. Thoughts?

**Comment by kripken** [comment]
(oops, hit the wrong button)

I think it would be good to add a line to a test in `test/*.wast`, since this was a bug in core printing functionality, and not specific to `.s` files.

**Comment by dschuff** [comment]
I would still like to have at least one small handwritten test. As you can see it's pretty easy to just auto-update the generated tests and miss things. I don't much care whether it's a .s test or  wast test, it should exercise the printing either way. I guess just a tiny function with an `i64.store32` in `test/unit.wast` should do it, right?

**Comment by kripken** [comment]
> I guess just a tiny function with an i64.store32 in test/unit.wast should do it, right? 

Yeah, that should be enough.

**Pull request merged**
