### PR TITLE
Optimize normally with debug info

### PR DESCRIPTION
**Pull request by kripken**
Some of it may be removed, but that's the price of higher optimization levels. By optimizing normally in profiling and -g2 etc. builds they are more comparable to normal ones, yielding better data (for example, if we don't inline in a profiling build, the data can be misleading).

This has no change on debug info in -O0 builds, and almost no change on -O1 builds (we now run dce there, which could eliminate some debug info, but it wasn't interesting anyhow almost certainly).

### CODE REVIEW

**Comment by kripken** [comment]
cc @yurydelendik , maybe you have some thoughts?

**Comment by dschuff** [comment]
IIRC currently the model for debug locs is that there's a map from `Expression*` to a `DebugLocation`. Passes should probably be updating this map whenever they replace a node with another node, but I don't know of anywhere we do that. That's obviously a separate thing from DCE but it makes a big difference when trying to profile or debug optimized code.

**Comment by kripken** [comment]
I think we can do better here, yeah. E.g. most passes use replaceCurrent to replace nodes, so we could make it aware of debug info. Otherwise, yeah, we'd need to add manual debug info copies in the optimizations, where possible. Not sure this is high priority yet, but I imagine once wasm debugging gets better people may care more about this.

**Comment by kripken** [comment]
Added support for copying debug info in `replaceCurrent`.

**Comment by sbc100** [comment]
Looks like this broke the emscripten tests: wasm2.test_source_map and wasm3.test_source_map.

I guess to be expected, the debug line information only shored 11 and 12 now.  Should we just update the test expectations for 02 and above?

**Comment by sbc100** [comment]
Hmm.. looking at the test case it looks like the function in question is marked as " __attribute__((noinline))" .. I guess that doesn't get propagated to binaryen and its inlining it anyway maybe?

**Comment by kripken** [comment]
Yes, I landed a PR to fix these, https://github.com/emscripten-core/emscripten/commit/7f7d0d066cdec1d408be96b4dd1fe961b80572e5

And yes, binaryen doesn't know about noinline. To prevent inlining in binaryen, it just needs to be run at -O1 or below.

**Pull request merged**
