### PR TITLE
Unify JS memory segment API

### PR DESCRIPTION
**Pull request by dcodeIO**
Binaryen.js now uses `offset` instead of `byteOffset` when inspecting a memory segment, matching the arguments on memory segment creation. Also adds inspection of the `passive` property.

---

Previously, one would specify `{ offset, data, passive }` on creation and get back `{ byteOffset, data }` upon inspection. This PR unifies both to the keys on creation while also adding the respective C-API to retrieve passive status, which was missing.

### CODE REVIEW

**Comment by tlively** [comment]
@dcodeIO Would you mind pushing an empty commit to this branch to hopefully get the CI restarted?

**Comment by kripken** [comment]
Looks like we forgot to merge this? :(

It's approved, but I think the changelog part needs updating since we released a version since then.

**Comment by dcodeIO** [comment]
Looks like [the previous merge](https://github.com/WebAssembly/binaryen/pull/2533/commits/d846fbc43b5a686e79495a09e97c85ed0bb8f6d9) covered the changes, but merged again to be sure :)

**Comment by kripken** [comment]
Great, thanks again, and sorry for the delay!

**Pull request merged**
