### PR TITLE
[Wasm GC] Effects: Differentiate Struct and Array types

### PR DESCRIPTION
**Pull request by kripken**
This allows common patterns in J2CL to be optimized, where we write
to various array indices and get the values or the reference from a
struct.

It would be nice to do even better here, and look at actually specific
types, but I think we should be careful to keep the runtime constant.
That seems hard to do if we accumulate a list of types and do
`Type::isSubType` on them etc. But maybe someone has a better
idea than this PR?

### CODE REVIEW

**Review by aheejin — APPROVED** [review]
This looks like a simple enough addition and wouldn't incur much more overhead to `Effects` computation, so LGTM.

About more fine-grained analysis, maybe we can consider different levels of effects computation, with default set to the current (basic) level, because most of optimization passes don't need that..? Or for efficacy we can maybe add a framework to cache effects in case the expression hasn't changed but we need the result again.

**Comment by aheejin** [comment]
Also when we compute effects for an expression, we will traverse and recompute effects for all its children, right? Would there be a way to reuse children's effects when computing one? Surely it needs some updating methods in case its children changes though (like `ReFinalize`)

**Comment by kripken** [comment]
@aheejin 

> maybe we can consider different levels of effects computation

Oh, good point - yeah, we have the pass options already in this class (I believe you did that work actually) so we could use them. That's worth exploring.

> Would there be a way to reuse children's effects when computing one?

It is possible to do that, by calling visit instead of walk, and on the parent doing `mergeIn(childEffects)` on each child. I believe a few passes do that.

**Comment by tlively** [comment]
Would it be worth creating a new kind of `EffectsWalker` that efficiently tracks effects for the current expression? That seems less error prone than manually merging the effects as part of the pass implementation.

**Review by tlively — APPROVED** [review]
This LGTM as well. For more precise analysis, one possibility would be to maintain a small constant (but configurable?) number of root types. If the number of observed read or written types exceeds that small constant, we would fall back to the less granular analysis.

**Comment by kripken** [comment]
> Would it be worth creating a new kind of EffectsWalker that efficiently tracks effects for the current expression?

Possibly, but it looks like the two places that use `mergeIn` actually do custom processing (along Block children) and don't even use a Walker. But maybe we could find a better helper for those two, although they are very stable at this point.

**Comment by kripken** [comment]
Ok, let's land this and look into other improvements later. Good ideas here for options in that direction.

**Pull request merged**
