### PR TITLE
Emscripten no longer allows modifying Module['print'] at runtime

### PR DESCRIPTION
**Pull request by kripken**
Modify the internal out() method instead. see kripken/emscripten#6756

### CODE REVIEW

**Comment by dcodeIO** [comment]
Just noticed: With this change it isn't possible anymore to override printing to stdout, which I used to do in AssemblyScript because I am using the C-API directly. Not sure what to do instead now, but the way it is currently would make it necessary to compile a custom binaryen.js or something for the compiler. Any idea?

**Comment by kripken** [comment]
The edit looks like it should work, yeah. Another option is to add a layer of indirection, to define `Module.print` during startup as a function like this, for example:
```
Module['print'] = function(x) { Module['flexiblePrint'](x) };
Module['flexiblePrint'] = .. ; // and you can modify this later at any time
```

**Comment by dcodeIO** [comment]
So, does Emscripten still call `Module['print']` if it is present? I thought it is using the inner (to the generated JS, and thus inaccessible from the outside) `out` function now.

**Comment by kripken** [comment]
Exactly, yeah, you can define it, just not change it later (so if you need that extra flexibility, you need to add it yourself).

**Pull request merged**
