### PR TITLE
Omit trailing comma in JSON  metadata for standalone mode

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
Fix for #2906 because lol JSON

**Comment by sbc100** [comment]
I have a slightly different fix that instead moves the optional field up one slot so its not last.    I think its slightly cleaner... maybe?

**Comment by dschuff** [comment]
yeah that could be cleaner; doesn't really matter to me either way.

**Comment by dschuff** [comment]
Closing in favor of #2909

**Pull request closed without merging**
