### PR TITLE
Hacks to build and test BinaryenJS with wasm EH

### PR DESCRIPTION
**Pull request by dschuff**
Not for commit, just for testing.
These changes allow building and testing Binaryen.js with `-fwasm-exceptions`. Just configure with `emcmake` and build the `binaryen_wasm`  target as usual. It also requires testing with a nodejs version build with tip-of-tree v8.

### CODE REVIEW

**Comment by dschuff** [comment]
All the binaryenJS tests pass when built and run this way!
/cc @aheejin @kripken

**Comment by aheejin** [comment]
Just wondering, does Adobe need BinaryenJS?

**Comment by dschuff** [comment]
Not that I'm aware of. This was just to try out EH support with a larger test.

**Comment by kripken** [comment]
Oh, this basically runs the wasm version of binaryen, with wasm EH, and tests pass locally for you @dschuff ?

**Comment by dschuff** [comment]
Yes, exactly.

**Comment by kripken** [comment]
Nice, pretty good that wasm EH can pass those.

**Comment by kripken** [comment]
Looking for more things to test (not sure where else to post this), I ran the emscripten test suite with `-O0` and `-O3` with `-fwasm-exceptions`, and saw no unexpected failures (some tests fail because they e.g. Asyncify, or depend on node and I was using d8, etc.)

**Pull request closed without merging**
