### PR TITLE
[#7178] Introduce guard arround local get/set generation

### PR DESCRIPTION
**Pull request by mtb0x1**
This is an attempt fix of issue #7178  , This PR needs (?) a regression test. (I wasn't able to reproduce a wast file to trigger the issue).

### CODE REVIEW

**Comment by mtb0x1** [comment]
> If there's any information I should provide, please let me know! I'll share it.

if you can confirm the test result using this PR, you should have an error message instead of a Seg. fault.

**Comment by famasoon** [comment]
Thank you for checking!
I think adding it to the pull request might cause information to get mixed up, so I'll write the details in the Issue instead.

**Comment by famasoon** [comment]
I've written the details in the Issue. The crash no longer occurs!

**Comment by kripken** [comment]
Thanks for the PR @mtb0x1 !

Sorry, I just saw that this fixes the issue now after already opening https://github.com/WebAssembly/binaryen/pull/7183 If you want I can close that one and we can continue here, but it does add testing, and a few other things that I would have asked as changes in this PR.

**Comment by mtb0x1** [comment]
> Thanks for the PR @mtb0x1 !
> 
> Sorry, I just saw that this fixes the issue now after already opening #7183 If you want I can close that one and we can continue here, but it does add testing, and a few other things that I would have asked as changes in this PR.

no problem, I will close this one.

**Pull request closed without merging**
