### PR TITLE
[GC] Ignore public types in GlobalTypeOptimization

### PR DESCRIPTION
**Pull request by kripken**
TypeUpdater which it uses internally already does so, but we must also ignore
such types earlier, and make no other modifications to them.

Helps #7015

### CODE REVIEW

**Comment by kripken** [comment]
OTOH, SignaturePruning goes further than this:

https://github.com/WebAssembly/binaryen/blob/fd86eadb591576b82b0b564f95952b131979e91a/src/passes/SignaturePruning.cpp#L294-L297

It checks if individual types are exported etc., and not just their entire rec group.

That is more optimal, obviously, so I guess GTO should do the same? Or has our thinking changed since then @tlively ?

**Review by tlively — APPROVED** [review]
We could recover some of the lost optimization potential by changing the field of child3 to be `(ref nofunc)` and continuing to drop the values that would be used to initialize it.

**Comment by kripken** [comment]
> We could recover some of the lost optimization potential by changing the field of child3 to be `(ref nofunc)` and continuing to drop the values that would be used to initialize it.

Sorry, I don't follow - what values would those be? That's an uninhabitable type so there is nothing we can use. I'm not sure how we can fix up this code, in other words:
```wat
      (struct.new $child3
        (ref.func $func)
      )
```
It is not unreachable.

**Comment by tlively** [comment]
Oh, right, that wouldn't work because we need an inhabitable type. `(ref null nofunc)` would work if the original field were nullable, but otherwise I guess there's not much we can do.

**Comment by tlively** [comment]
I think we could do the same thing SignaturePruning does and create optimized copies of public struct types, but we could only do that safely in cases where the struct type is only public due to its rec group and not because it can actually flow out of the module. Right now we have no way to differentiate those different degrees of visibility.

**Comment by kripken** [comment]
@tlively 

> I think we could do the same thing SignaturePruning does and create optimized copies of public struct types, but we could only do that safely in cases where the struct type is only public due to its rec group and not because it can actually flow out of the module. Right now we have no way to differentiate those different degrees of visibility.

Yeah, that's exactly the issue. We'd need to identify those degrees, which means a very careful analysis of why something is public. I don't see a good way to do that atm, so I'll open a PR for SignaturePruning to limit it as well.

The good news is that at least on Java output I don't see any harm to limiting GTO and SignaturePruning in this way. But in theory on output like in #7015 (from Kotlin apparently) there is a single big rec group with mixed public/private contents that we could in theory partially optimize. But right now we break on them, so fixing things is a set up for them too.

**Comment by kripken** [comment]
Perhaps we can think of a way to split up public rec groups in closed world mode in a safe way, to make parts of such a group private again?

**Comment by tlively** [comment]
> Perhaps we can think of a way to split up public rec groups in closed world mode in a safe way, to make parts of such a group private again?

See my comment here: https://github.com/WebAssembly/binaryen/issues/7015#issuecomment-2420606899

**Comment by tlively** [comment]
> Yeah, that's exactly the issue. We'd need to identify those degrees, which means a very careful analysis of why something is public. I don't see a good way to do that atm, so I'll open a PR for SignaturePruning to limit it as well.

In principle we could do this by finding all the public types without considering rec group peers and giving them a different classification. But it would be better just to fix #6965 and let producers give us reasonable modules that don't have these issues to begin with.

**Comment by kripken** [comment]
Yeah, good point, #6965 would fix this too by having public annotations on types. That's better than on rec groups.

**Pull request merged**
