### PR TITLE
Revert "[OptimizeInstructions] Simplify add / sub with negative on LHS or RHS for floating points"

### PR DESCRIPTION
**Pull request by tlively**
Reverts WebAssembly/binaryen#5034, which didn't properly check effects before reordering.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
Might be better to just revert the first rule in the patch, which is the bad part?

If you and @MaxGraey don't have time to do that though then sgtm to land this.

**Comment by MaxGraey** [comment]
Ah, yeah. I guess better just to add `canReorder` for first rule instead remove all rules

**Comment by tlively** [comment]
I can handle fixing forward.

**Comment by MaxGraey** [comment]
I created a fix: https://github.com/WebAssembly/binaryen/pull/5066

**Comment by tlively** [comment]
Closing in favor of https://github.com/WebAssembly/binaryen/pull/5066

**Pull request closed without merging**
