### PR TITLE
Fix shareability of externalized nulls

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Thanks! How many iterations is your fuzzing going through before finding a bug on average?

**Comment by kripken** [comment]
`O(100K)` I'd say, after these last fixes.

**Comment by tlively** [comment]
Sounds good. I probably should have left it running longer (`O(1M)`?) locally before landing the fuzzer support upstream. Sorry for all the busy work!

**Comment by kripken** [comment]
No worries. Sometimes it's hard to predict the fallout.

I've never waited 1M for anything... overnight at the most, which is around 100K.

**Pull request merged**
