### PR TITLE
Disable MSVC warnings about unsafe C runtime functions.

### PR DESCRIPTION
**Pull request by dschuff**
We aren't going to switch to MSVC's alternatives.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm. @BSalita, what do you think?

**Comment by BSalita** [comment]
Good. It was on my list to learn how to add compiler defs to cmake so that _CRT_SECURE_NO_WARNINGS would be added to Visual Studio files. Derek beat me to it.
There's another flag that should be added which supresses some legacy issues: _SCL_SECURE_NO_WARNINGS
Here's the output from Visual C++ when _SCL_SECURE_NO_WARNINGS isn't used:
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2442): warning C4996: 'std::copy_n::_Unchecked_iterators::_Deprecate': Call to 'std::copy_n' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'1>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2442): note: see declaration of 'std::copy_n::_Unchecked_iterators::_Deprecate'1>  c:\sw\wasm\binaryen\binaryen32\src\binaryen-c.cpp(410): note: see reference to function template instantiation '_OutIt std::copy_n<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>,size_t,char*>(_InIt,_Diff,_OutIt)' being compiled1>          with1>          [1>              _OutIt=char *,1>              _InIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>,1>              _Diff=size_t1>          ] 

    On Friday, May 13, 2016 12:11 AM, Alon Zakai <notifications@github.com> wrote:
 

 lgtm. @BSalita, what do you think?—

**Comment by BSalita** [comment]
On my C projects, I prefer to avoid external defs. I prefer to have a #include "impldefs.h" at the top of each source file. Inside impldefs are #pragmas which turn off compiler Visual Studio warnings. I stuff other conditional definitions based on compiler/system/bit-ness/endian. The benefit is that I don't have to be concerned about settings defs in make files. Its easier to maintain. I see that there's some similar file in binaryen but it isn't carried through to all source files. 

    On Friday, May 13, 2016 12:51 AM, Bob Salita <bsalita@yahoo.com> wrote:
 

 Good. It was on my list to learn how to add compiler defs to cmake so that _CRT_SECURE_NO_WARNINGS would be added to Visual Studio files. Derek beat me to it.
There's another flag that should be added which supresses some legacy issues: _SCL_SECURE_NO_WARNINGS
Here's the output from Visual C++ when _SCL_SECURE_NO_WARNINGS isn't used:
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2442): warning C4996: 'std::copy_n::_Unchecked_iterators::_Deprecate': Call to 'std::copy_n' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'1>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2442): note: see declaration of 'std::copy_n::_Unchecked_iterators::_Deprecate'1>  c:\sw\wasm\binaryen\binaryen32\src\binaryen-c.cpp(410): note: see reference to function template instantiation '_OutIt std::copy_n<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>,size_t,char*>(_InIt,_Diff,_OutIt)' being compiled1>          with1>          [1>              _OutIt=char *,1>              _InIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>,1>              _Diff=size_t1>          ] 

    On Friday, May 13, 2016 12:11 AM, Alon Zakai <notifications@github.com> wrote:
 

 lgtm. @BSalita, what do you think?—

**Comment by dschuff** [comment]
On the other hand, warnings are disabled for the posix systems via command line flags. (I don't even know if there are pragmas for that with those compilers, but it's certainly not common practice to use them). So given that I think I'd rather have all the warning disabling going on in one place (CMakeLists.txt) for all platforms.

**Comment by BSalita** [comment]
Still it would be nice to have a #include at the top of each file. They're also handy for special OEM definitions and debugging. Anyway, if devs are accustomed to putting defs into cmake then we should continue. Yes, Visual C++ #pragmas allows you to suppress any warnings and can do many other handy things. 

    On Friday, May 13, 2016 1:10 AM, Derek Schuff <notifications@github.com> wrote:
 

 On the other hand, warnings are disabled for the posix systems via command line flags. (I don't even know if there are pragmas for that with those compilers, but it's certainly not common practice to use them). So given that I think I'd rather have all the warning disabling going on in one place (CMakeLists.txt) for all platforms.—

**Comment by dschuff** [comment]
It turns out we even already have warning disabling for Windows in CMakeLists.txt (/wd4146), so this is consistent; I think I'm going to land it.
If we have another concrete use case for a global #include, then we can talk about that separately.

**Pull request merged**
