### PR TITLE
[Simd] Add extension from i32x4 to i64x2 ops to interpreter

### PR DESCRIPTION
**Pull request by MaxGraey**
Add following instructions:
```ts
i64x2.extend_low_i32x4_s
i64x2.extend_high_i32x4_s
i64x2.extend_low_i32x4_u
i64x2.extend_high_i32x4_u
```

### CODE REVIEW

**Comment by MaxGraey** [comment]
Hmm. why `extend_low_i32x4_s` doesn't use sign extension?:
```wat
(assert_return 
  (invoke i64x2.extend_low_i32x4_s 
    (v128.const i32x4 -1 -1 -2147483648 -2147483648) 
  ) 
  (v128.const i64x2 -1 -1) 
) 
[line: 980]
seen     i32x4 0xffffffff 0x00000000 0xffffffff 0x00000000,
expected i32x4 0xffffffff 0xffffffff 0xffffffff 0xffffffff ;; i64x2 -1 -1
Fatal: unexpected, should be identical
```
I'm confused.

**Comment by MaxGraey** [comment]
@tlively I added special `extendSI64` with evaluation `lit.extendToSI64()` for every lane. This works but not consistent. What about change `extend`'s line extractor from `LaneArray<Lanes * 2> (Literal::*IntoLanes)() const` into `LaneArray<Lanes> (Literal::*IntoSingleLane)() const` and use scalar helpers like `extendToSI64`, `extendToSI16` and etc instead incoming `getLanesI32x4`, `getLanesSI8x16`?

**Comment by tlively** [comment]
@MaxGraey, yes, that sounds like a good idea to me.

**Comment by MaxGraey** [comment]
Dome!

**Review by tlively — APPROVED** [review]
Nice, thanks!

**Pull request merged**
