### PR TITLE
Added the ability to run specific (optimization) passes to binaryen-c/.js

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR adds a `BinaryenModuleRunPasses` function to the C-API respectively a `runPasses` method to the JS-API that takes an array of names of the passes to run.

Also fixes a couple of build issues with the JS binaries and includes the updated ones.

### CODE REVIEW

**Comment by kripken** [comment]
What do you think about adding a new API call alongside `BinaryenModuleOptimize`, something like `BinaryenModuleRunPasses` which receives a pass or passes to run? This both keeps backwards compatibility and also not all passes are optimization passes (although we do refer to them that way sometimes, but I feel that makes more sense internally than in an official API).

**Comment by dcodeIO** [comment]
Sure, can do that as well!

**Comment by dcodeIO** [comment]
Alright, updated the PR accordingly.

**Comment by kripken** [comment]
Great, thanks!

**Pull request merged**
