### PR TITLE
Fix pow2 util and avoid pow2 for left shifting in ZeroRemover

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix issue found by fuzzed [here](https://github.com/WebAssembly/binaryen/pull/3015#issuecomment-718001620)

cc @kripken

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Thanks!

I was wondering how we missed a big in your PR, so makes sense it was a bug in pre-existing support code :rofl:

**Comment by kripken** [comment]
Looks like there is a UBSan failure here.

**Comment by MaxGraey** [comment]
Alright, it seems ubsan passed

**Comment by MaxGraey** [comment]
Short fuzzed stats:
```
Invocations so far:
   FuzzExec: 6437
   CompareVMs: 1139
   CheckDeterminism: 585
   Wasm2JS: 662
   Asyncify: 1028

ITERATION: 7120
```

**Comment by kripken** [comment]
Great!

**Pull request merged**
