### PR TITLE
Use rpath instead of LD_LIBRARY_PATH for shared object use

### LINKED ISSUE #444: Use RPATH, not LD_LIBRARY_PATH
As discussed in https://github.com/WebAssembly/binaryen/pull/435#discussion_r62245931

### PR DESCRIPTION
**Pull request by dschuff**
Use the -rpath linker flag to locate libbinaryen-c.so instead of
injecting paths into the user's LD_LIBRARY_PATH.
Fixes #444

### CODE REVIEW

**Comment by dschuff** [comment]
I also discovered that libbinaryen-c.so depends on libasmjs and other stuff, so if it goes too late on the link line, things break. What we really should do, is link everything into on libbinaryen.so, which can export both the C and C++ APIs and can be used without also having to link all of binaryen's internal libraries manually.

**Comment by dschuff** [comment]
Fixes #444

**Comment by kripken** [comment]
lgtm. might need to coordinate with @mbebenita's #446?

**Comment by dschuff** [comment]
OK I folded something like #446 into this, and confirmed that the build works on OSX.

**Comment by kripken** [comment]
Great!

**Pull request merged**
