### PR TITLE
Memory merging fix

### PR DESCRIPTION
**Pull request by kripken**
Fixes memoryMerge. After this, we should have the same code path between interpreter and native, and interpreter works, so hopefully all is good.

We should have already unified those code paths, but the interpreter one had an "optimization" :(

### CODE REVIEW

**Comment by kripken** [comment]
Oops, this is not yet done.

**Comment by kripken** [comment]
Ok, this fixes the issues we saw with memory, @dschuff, @bnjbvr, @lukewagner.

I also uploaded an updated build of hello world to https://github.com/WebAssembly/build-suite/tree/master/emscripten/hello_world

Also a C++ hello world with iostream at https://github.com/WebAssembly/build-suite/tree/master/emscripten/hello_iostream , which is much larger.

**Comment by dschuff** [comment]
LGTM, I'll try it out with my local v8 patch and then send a PR for that.

**Comment by bnjbvr** [comment]
With that change and a small tweaks (translate text to binary + use "read" instead of "readBinary" + memory size is in number of pages and not bytes + memory must be exported with `export "memory" memory`), the hello_world demo runs under SM and prints "hello, world"!

**Pull request merged**
