### PR TITLE
Integrate the heap type fuzzer into the main fuzzer

### PR DESCRIPTION
**Pull request by kripken**
With this we generate random GC types that may be used in creating
instructions later.

We don't create many instructions yet, which will be the next step after
this.

Also add some trivial assertions in some places, that have helped
debugging in the past.

### CODE REVIEW

**Comment by kripken** [comment]
This uncovered some UB in call order in the heap fuzzer. Last two commits should fix it. This is noticeable on our CI because gcc and clang have opposite behavior in that UB.

**Review by tlively — APPROVED** [review]
Makes sense, thanks for the fix!

**Comment by kripken** [comment]
I pushed a commit to stop fuzzing TypeMerging for now due to https://github.com/WebAssembly/binaryen/issues/5556. With that things look stable, and this can land, WDYT?

**Review by tlively — APPROVED** [review]
Sounds good! I should be able to get to the TypeMerging bug today, too.

**Pull request merged**
