### PR TITLE
Fix binaryen*.js on latest emscripten

### PR DESCRIPTION
**Pull request by kripken**
Without `MODULARIZE_INSTANCE`, we have to create the instance
ourselves.

This returns us to testing on latest tip of tree builds.

Something is wrong here, though... this fails without the weird change to not use a real Promise, and instead use a little shim, see the `src/js/binaryen.js-post.js` part. I basically saw that this failed, then to debug it I started to polyfill a Promise, but then it started working...

I can debug it some more, but maybe that diff has an obvious explanation? @dcodeIO maybe you can take a quick look?

### CODE REVIEW

**Comment by dcodeIO** [comment]
Looks like something it wrong with `ready`, yeah. Going to take a look on a local branch if you don't mind :)

**Comment by dcodeIO** [comment]
Hmm, what I can tell so far is that `MODULARIZE` cannot be easily amended to behave like `MODULARIZE_INSTANCE` did before, because it already registers the non-instance `Module` with the various module loaders which isn't trivial to undo in all cases, especially AMD. Looks like we either can't use `MODULARIZE` anymore, or need to add an option to Emscripten so it doesn't register with the module loaders to allow custom code for that in extern-post (perhaps `MODULARIZE=2`?).

**Comment by kripken** [comment]
Interesting, I don't know much about this stuff...

Do we need all the module loaders? Can we perhaps just use ES6 exports (with the emcc `EXPORT_ES6` flag)?

(Btw, there is work in https://github.com/emscripten-core/emscripten/pull/10697/ to rethink the MODULARIZE option, perhaps related.)

**Comment by dcodeIO** [comment]
> Do we need all the module loaders? Can we perhaps just use ES6 exports (with the emcc EXPORT_ES6 flag)?

Last time I checked node.js and ESM was still a disaster. Not sure if this changed with node 14, but I'd expect that we still need the loaders to support earlier versions of node anyway. 

Missed the discussion about the `MODULARIZE_INSTANCE` removal unfortunately, would otherwise have raised concerns.

**Comment by dcodeIO** [comment]
Managed to [get it working](https://github.com/WebAssembly/binaryen/pull/2838) again.

Regarding ES6: Perhaps this can be simplified eventually by switching Binaryen over to ES6, as you mentioned, and let the binaryen.js package do what's necessary to support node by transpiling. Would have to investigate a bit and to set this up first, though.

**Comment by kripken** [comment]
Yeah, if we can use ES6 eventually and rely on transpilation that might be best.

Closing as the problem was fixed by @dcodeIO 's PR.

**Pull request closed without merging**
