### PR TITLE
Use local enum, and init in-line

### PR DESCRIPTION
**Pull request by jfbastien**

### CODE REVIEW

**Comment by kripken** [comment]
Why static?

**Comment by jfbastien** [comment]
It's more idiomatic when you don't have `constexpr`, and in some weird cases gives the compiler more information (though in this case it's pretty straightforward, same codegen should occur).

**Comment by kripken** [comment]
Seems risky, though? The default behavior is to place it in the data segment, globally, and you'd rely on optimizations to avoid the loads and also to get rid of allocating it? I did some searching and didn't see recommendations specifically for *function* scope for this pattern, but maybe I didn't find the right sources?

**Comment by jfbastien** [comment]
Eh, consexpr or local enum are the better thing, but non of it matters in this case. I'm happy going with whichever you'd rather have.

**Comment by kripken** [comment]
Local enum sounds better to me, I guess. But I don't feel strongly.

**Pull request merged**
