### PR TITLE
Remove "minimal" JS import/export legalization

### PR DESCRIPTION
**Pull request by sbc100**
This change removes the "minimal" mode from `LegalizeJSInterface` which was added in #1883.

The idea behind this change was to avoid legalizing most function except those we know that JS will be calling.  The idea was that for dynamic linking we always want the non-legalized version to be shared between wasm module.  These days we solve this problem in a different way with the `legalize-js-interface-export-originals` which exports the original functions alongside the legalized ones.  Emscripten then always prefers the `$orig` functions when doing dynamic linking.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
lgtm if Emscripten tests pass

**Comment by sbc100** [comment]
> lgtm if Emscripten tests pass

Everything except the one testing for this specific behaviour: https://github.com/emscripten-core/emscripten/pull/21599

**Comment by kripken** [comment]
@sbc100 This PR is cited as the reason for an Emscripten test being disabled:

https://github.com/emscripten-core/emscripten/blob/ea35c8cde53d4691504436300493d60b49ff3744/test/test_other.py#L8810-L8821

Do we still need to disable it / need that test?

**Comment by sbc100** [comment]
Yes, it looks like we can re-enable that test, but also it looks like we need to first ensure we have names for these stub functions: https://github.com/WebAssembly/binaryen/pull/6806

**Pull request merged**
