### PR TITLE
Directize: turns indirect calls into direct ones

### LINKED ISSUE #1973: Optimize call_indirect with constant index to direct call
A simple optimization to avoid `call_indirect`s seems to be to evaluate whether the function index is constant, and if that's the case, convert it to a direct call instead. For example, the following could eliminate `callee` if it did that, in turn eliminating the call, and maybe eliminating the function table if that's safe:

```wat
(module
 (type $v (func))
 (table $0 1 1 funcref)
 (elem (i32.const 0) $callee)
 (export "main" (func $caller))
 (func $callee (; 0 ;) (; has Stack IR ;) (type $v)
  (nop)
 )
 (func $caller (; 1 ;) (; has Stack IR ;) (type $v)
  (call_indirect (type $v)
   (i32.const 0)
  )
 )
)
```

Of course the signature might mismatch, which would result in a runtime error with a `call_indirect` but a validation error with a `call`, so the optimization should not be performed if that's the case to retain error semantics I guess. Also, if the table could be modified somehow, like if imported or exported, this can't be done I assume?

Binaryen.js test case for completeness:

```js
var binaryen = require("binaryen");

var mod = new binaryen.Module();

var ftype = mod.addFunctionType("v", binaryen.none, []);

mod.addFunction("callee", ftype, [], mod.block(null, [
]));
mod.setFunctionTable(1, 1, [ "callee" ]);

mod.addFunction("caller", ftype, [], mod.block(null, [
  mod.call_indirect(mod.i32.const(0), [], "v"),
]));
mod.addFunctionExport("caller", "main");

binaryen.setOptimizeLevel(4);
binaryen.setShrinkLevel(0);
binaryen.setDebugInfo(false);
mod.optimize();
if (!mod.validate())
  console.log("-> does not validate");
console.log(mod.emitText());
```

### PR DESCRIPTION
**Pull request by kripken**
Closes #1973

### CODE REVIEW

**Comment by kripken** [comment]
From the discussion in that issue, this may not help AssemblyScript immediately, but let's land this anyhow - it can help other compilers, as shown in test updates here.

**Comment by kripken** [comment]
Testing on LLVM wasm backend output, if the table were not imported or exported there, this can save a few bytes, but that's about it - a few bytes out of many thousands. So for code size this is quite minor there. But, it may be useful for speed.

**Comment by sbc100** [comment]
Presumably this will be invalid once we have `table.set` instruction.  Although I guess we could scan for that.

**Comment by binji** [comment]
Right, `table.set` and `table.fill` (from the reference types proposal) invalidate this, as well as `table.init` and `table.copy` from the bulk memory proposal.

**Comment by kripken** [comment]
Yeah, engines can do it too, good point. I was sort of hoping that there would be cascading benefits, like after its a direct call we can inline, remove dead arguments, etc., but I don't see that happening on wasm backend output at least.

**Comment by kripken** [comment]
I moved the order of calling this slightly later. It does more on wasm backend output (if the table were not imported) in that case. Verified to pass the emscripten test suite too.

**Pull request merged**
