### PR TITLE
Use wat over wast for text format filenames

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
I'm sure I've missed some uses here, but I wanted to be conservative because some uses of wast really are wast files rather than single-module wat files.

**Comment by aheejin** [comment]
What are the differences between wast and wat files now? Is it ok for wat files not in valid wat format parsable by wabt?

**Comment by sbc100** [comment]
IIUC, wat is for a single module and wast is for a file that contain any number of modules and/or assertions.

I'm not sure about the second question.   Any wat file not in valid should generate parse error in wabt (unless some special option is given such as `--no-check` perhaps?)

**Comment by aheejin** [comment]
Hmm, I had an (incorrect) impression that the s-expression format Binaryen uses is the wast format and the straight-line format Wabt uses is the wat format. But it seems Wabt also can parse s-expression format Binaryen uses (although not all of them currently).

**Pull request merged**
