### PR TITLE
Fix read out of range numbers in text mode when using Visual Studio

### PR DESCRIPTION
**Pull request by vloppin**
Currently the wast reader fails to read invalid values when using Visual Studio.

This PR changes the behaviour to match the GCC/Clang ones.

Maybe a test could be interesting ?

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

A test would be good, yeah. Can maybe add one inside `tests/unit.wast`.

However, should we not just throw a ParseError on such inputs? Or is it valid to read them as `-1`?

**Comment by vloppin** [comment]
> A test would be good, yeah. Can maybe add one inside tests/unit.wast.

Ok, I will have a look on that.

> However, should we not just throw a ParseError on such inputs? Or is it valid to read them as -1?

Hum ... I don't know. I did this modification to fix the vacuum.wast (passes) on Windows. But indeed, raising an error could be a better alternative ... (I didn't check on the spec if it gives us the right thing to do)

**Comment by vloppin** [comment]
From [WABT](https://github.com/WebAssembly/wabt/blob/master/src/literal.cc#L608)
```
  uint64_t value = 0;
  Result result = ParseUint64(s, end, &value);
  if (has_sign) {
    // abs(INT64_MIN) == INT64_MAX + 1.
    if (value > static_cast<uint64_t>(INT64_MAX) + 1) {
      return Result::Error;
    }
    value = UINT64_MAX - value + 1;
  }
```

It's sound interesting to have the same behaviour between tools, so maybe we should raise an error there.
It's imply to modify the `vacuum.wast` test.

**Comment by vloppin** [comment]
Now I throw ParseException on read error.

So I propose to add a test into `test/validator/invalid_number.wast` instead of `tests/unit.wast`, Ok ?

**Comment by kripken** [comment]
Sounds good, yes, can add a test to the validator subdir. Looks like you also need to add a line or two for it in `run_validator_tests()` in `check.py`.

**Comment by vloppin** [comment]
I add a simple test for invalid number.

But I think we should test other case for hexadecimal and floating number.

The main problem are in the parsing. Indeed, when it found an error it stops the parsing.
From my point of view, when I process a wrong text file into a tool, I rather than the tool give me all the errors (and if possible the line) than one by one.

**Comment by kripken** [comment]
Thanks @vloppin!

Yeah, more tests would be nice, if possible later.

Fair point about reporting multiple errors. So far we just throw on the first. In text maybe it's feasible to continue after an error - the main focus has been on the wasm binary format, where after any error it's likely nothing else will make sense. But if it's practical to add for text, that could be nice.

**Pull request merged**
