### PR TITLE
archive_files_windows_eol_fix

### PR DESCRIPTION
**Pull request by juj**
Fix s2wasm .a archive file open to open text files in text mode. The .a files are text content which on Windows have \r\n file endings on disk. When loaded to memory in binary mode, they would load the \r\n as-is, which would fail parsing of the file, since the loader expects \n newlines. Opening a text file with \r\n on Windows causes it to be converted to \n line endings in memory.

### CODE REVIEW

**Comment by dschuff** [comment]
I think the file format only calls for `\n` and not `\r\n` (the only useful reference I've seen is https://en.wikipedia.org/wiki/Ar_(Unix)) but in general I would think that the format of archive files should be the same on all OSes, just as the format for executables and object files is the same (both LLVM object files now, and wasm objects in the future). So maybe we should try to prevent archive files from getting created in text mode instead. Right now as far as I know the only source of archives that are actually fed to this code is `create_wasm_compiler_rt()` in emscripten's `tools/system_libs.py` which just calls llvm-ar to create the archive. Are you finding that that results in archives with `\r\n` or did you create one manually?

**Comment by juj** [comment]
These two files are text files that are passed as input to `s2wasm`, and git converts them on checkout from `\n` line endings to `\r\n` line endings (the most common repository line ending format people use with git):
   - https://github.com/WebAssembly/binaryen/blob/master/test/linker/archive/foobar.a
   - https://github.com/WebAssembly/binaryen/blob/master/test/linker/archive/barlong.a

Loading those files assert fails immediately in a memcmp trying to find `!<arch>\n` when it sees `!<arch>\r\n` instead. My understanding is that all input files to `s2wasm` are in textual format like this?

**Comment by juj** [comment]
Or hmm, perhaps that assumption is not correct, and these two are just special cases..

**Comment by dschuff** [comment]
All of the inputs should be GNU-style archive files, which should not be considered as text files, even though they happen to contain ASCII text :). So I guess the problem is that git is converting them on checkout because it thinks they are text. I think there's a way to get git to consider them as binary and not convert them.

**Comment by dschuff** [comment]
If you add a `.gitattributes` file with the following content, does that help?
`*.a -text`

**Comment by juj** [comment]
Yeah, that does work, but oddly it's a bit flaky and only works on a clean checkout. I.e.

    git clone https://github.com/WebAssembly/binaryen.git
    cd binaryen
    git checkout archive_files_windows_eol_fix

does not work if master branch doesn't have the .gitattributes set, but the archive_files_windows_eol_fix branch does.

After checking out archive_files_windows_eol_fix, deleting the .a files and git reset --harding back to archive_files_windows_eol_fix, the files do get `\n` endings. So on the long run this will work - on Windows side one will need to reclone once this reaches master.

**Comment by juj** [comment]
Yeah, the `.gitattributes` route is better than the original one. Thanks for noticing that!

**Pull request merged**
