### PR TITLE
Refactor standardizeNaN

### PR DESCRIPTION
**Pull request by MaxGraey**
In this PR `standardizeNaN` changes input type from raw value to literal which reduce usage verbosity

### CODE REVIEW

**Comment by MaxGraey** [comment]
@tlively could you take a look please?

**Review by tlively — APPROVED** [review]
LGTM, but it would be good to fuzz this to double check that the change to using `bit_cast` doesn't change anything.

**Comment by MaxGraey** [comment]
@tlively fuzzed `ITERATION: 5197`

**Comment by MaxGraey** [comment]
Thanks!

**Pull request merged**
