### PR TITLE
Make the legacy parser follow more closely the standard GC text format

### PR DESCRIPTION
**Pull request by vouillon**
For now, the previous syntax is still accepted.

### CODE REVIEW

**Comment by tlively** [comment]
Thanks for the patch! Can you add a test for the changes in test/lit? You can use `scripts/update_lit_checks.py -f path/to/test.wast` to automatically generate the checks for it if you add just a RUN line at the top of the test.

**Comment by vouillon** [comment]
I have added some tests.

I should probably change the text output and all the tests to use the standard syntax. But maybe i can do that in another PR?

**Review by tlively — APPROVED** [review]
Awesome, thanks for working on this.

**Comment by tlively** [comment]
> I should probably change the text output and all the tests to use the standard syntax. But maybe i can do that in another PR?

This would be very helpful. Doing it in a separate PR would be fine.

**Pull request merged**
