### PR TITLE
Remove assert 'atomic loads must be unsigned'

### PR DESCRIPTION
**Pull request by juj**

### CODE REVIEW

**Comment by kripken** [comment]
I believe @dschuff added that because in the [wasm spec atomics are unsigned](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#loadstore). So we should fix what is generating a signed atomic operation, do you have a testcase?

**Comment by binji** [comment]
Or perhaps just automatically convert the unsigned atomic RMW result to unsigned by using the new extend instructions. That was the intention, since there was pushback from the CG about adding so many signed atomic instructions.

**Comment by dschuff** [comment]
That's the right thing for a code generator to do, but this is the validator for Binaryen IR. I decided to mirror wasm itself in this case, since that seemed simpler. The other option would be to allow it in Binaryen and then convert to using the extend instruction when encoding wasm, but it seemed like not  enough of a convenience win to justify having Binaryen be different from wasm in this respect.

**Comment by kripken** [comment]
Yeah, I think what we have now is good. And we do have code that sign-extends as necessary - although not using the new instructions, they do it manually. So the question is in what code path do we not do that, leading to this bug - need a testcase.

**Comment by juj** [comment]
As a test case, `a.cpp`:

```c++
#include <assert.h>
int main()
{
	volatile unsigned char x = 5;
	assert(x == 5);
}
```

`em++ a.cpp -o a.html -s USE_PTHREADS=1 -s WASM=1 -O1`

Curiously the unsigned operation does not appear in an `-O0` build, only on `-O1` and higher.

**Comment by kripken** [comment]
What branches are you on? On heapu64 in binaryen and threads-hack in emscripten (+ the 2 line patch in the PR in my last comment), I don't see a failure here.

Or, maybe can you just provide the `.asm.js` that fails, + asm2wasm command?

**Comment by juj** [comment]
The issue occurs in this set of branches:
 - Emscripten: https://github.com/juj/emscripten/commits/pthreads_hack
 - Emscripten-fastcomp: https://github.com/juj/emscripten-fastcomp/commits/64bit_wasm_atomics
 - Emscripten-fastcomp-clang: current incoming, i.e. https://github.com/kripken/emscripten-fastcomp-clang/commits/incoming
 - Binaryen: https://github.com/WebAssembly/binaryen/commits/heapu64

With those, if I run the above test case and command line to build, it gives the error. My `pthreads_hack` is basically the same as Derek's `threads-hack` pull request, except that I've adapted it to work with Lars's Wasm try build; although for purposes of the compilation error, this probably would not matter.

**Comment by kripken** [comment]
If you've got that already set up, can you provide just the `.asm.js` file that shows the problem? Or if you need to set it all up from scratch, I can do it.

**Comment by kripken** [comment]
I got it set up and can reproduce, investigating now.

**Comment by kripken** [comment]
Bug was that the optimizer sometimes wants to change loads to signed (if it can remove code that way). Fix added to https://github.com/WebAssembly/binaryen/pull/1262

**Comment by juj** [comment]
Perfect!

**Comment by kripken** [comment]
Ok, let's close this then and focus on that other PR.

**Pull request closed without merging**
