### PR TITLE
[SET] Parse, build, and print shared composite types

### PR DESCRIPTION
**Pull request by tlively**
Parse the text format for shared composite types as described in the shared-everything thread proposal. Update the parser to use 'comptype' instead of 'strtype' to match the final GC spec and add the new syntactic class 'sharecomptype'.

Update the type canonicalization logic to take sharedness into account to avoid merging shared and unshared types. Make the same change in the TypeMerging pass. Ensure that shared and unshared types cannot be in a subtype relationship with each other.

Follow-up PRs will add shared abstract heap types, binary parsing and emitting for shared types, and fuzzer support for shared types.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Is SET "shared everything threads"?

**Comment by tlively** [comment]
Yes, other options include `[shared]` or `[threads]`. Do you have a preference?

**Comment by kripken** [comment]
Hmm, SET took me a while to get, so maybe one of those others. Or `[shared-everything]`? That might be a little long though. I'm ok either way.

**Comment by tlively** [comment]
I'll go with `[threads]`.

**Pull request merged**
