### PR TITLE
Check exact double literals in wasm::is{U,S}Integer64()

### LINKED ISSUE #2291: wasm::is{U,S}Integer64() doesn't work well around INT64_MAX
The latest clang points a minor bug for -Wimplicit-int-float-conversion.

On the implementation of [wasm::wasm::isUInteger64](https://github.com/WebAssembly/binaryen/blob/ab3a1f65fb9d2e4ec7e2640daca0b3953a030da6/src/support/safe_integer.cpp#L52), `std::numeric_limits<uint64_t>::max()` is implicitly converted to double.
As double has only 53 bit for digits on typical systems, and the conversion rounds the value to 0x1p64, `isUInteger64(0x1p64)` returns true, which is wrong.

We should probably use fixed double literals like 0x1p64, -0x1p63, and 0x1p63 for the boundary check here.

### PR DESCRIPTION
**Pull request by quantum5**
Fixes #2291.

### CODE REVIEW

**Comment by quantum5** [comment]
Seems like hex float literals are not actually supported widely enough...

**Comment by quantum5** [comment]
Literals like `0x1p64` are not supported with Visual Studio 2015, as seen on AppVeyor, which is rather unfortunate.

**Comment by sbc100** [comment]
This seems to fix #2313

**Comment by dschuff** [comment]
VS2017 has been out for quite a while, could we start requiring that?

**Comment by sbc100** [comment]
Superceeded by #2314

**Pull request closed without merging**
