### PR TITLE
Remove stale test output

### PR DESCRIPTION
**Pull request by sbc100**
These test output files are ignored and so contain stale output
that is neither checked during `check.py` not updated during
`auto_update_tests.py`.

There are three clases to tests here:

1. Spec tests that end in 64.wast are ignored by scripts/test/wasm2js.py
2. Spec tests that are globallyi ignoed by shared.py:SPEC_TESTS_TO_SKIP
3. hello_world.2asm.js.. I cant tell where this came remove it seems
   like an anomaly.

### CODE REVIEW

**Review by kripken — APPROVED** [review]

**Comment by kripken** [comment]
Good idea!

**Comment by sbc100** [comment]
Do you know where the hello_world output file came from?

**Comment by kripken** [comment]
I'm pretty sure it's from `hello_world.wat`.

**Comment by sbc100** [comment]
I see but hello_world.wat is not included in the test run in the wasm2js directory right?  So it was correct to remove it?  Or should we add it to the current list of `tests + spec_tests + wasm2js_tests`?

**Comment by kripken** [comment]
I think it was ok to remove it - it's not testing anything useful anyhow, it's more of an example. Not sure why there was an output for it.

**Pull request merged**
