### PR TITLE
Add a pass fuzzer script

### PR DESCRIPTION
**Pull request by kripken**
This runs random optimization passes to look for breakage, then if it finds any it reduces the list of passes to the minimal that shows the problem.

### CODE REVIEW

**Comment by dschuff** [comment]
Why not just fix `alias.s` (i.e. fix the function type vs its return value) rather than disabling all of the .s tests? (or maybe we need a mechanism to disable individual tests because clearly just disabling them all whenever one is broken is terrible).

**Comment by dschuff** [comment]
Actually, shouldn't the extra validation go in a separate PR anyway?

**Comment by kripken** [comment]
Yeah this is all quite wip, I'll split it out. For fuzzing purposes that patch is helpful so it's here, but it shouldn't be here when this is merged of course.

But regarding alias.wast: that's the first test alphabetically that it appears in. The problem is in many other tests too.

**Comment by kripken** [comment]
Actually let me close this PR, I'm seeing a bunch of errors from fuzzing so I'll open a bunch of separate PRs.

**Pull request closed without merging**
