### PR TITLE
Revert "Reduce iterations required for dead argument elimination convergence"

### PR DESCRIPTION
**Pull request by arsnyder16**
Reverts WebAssembly/binaryen#4629

### CODE REVIEW

**Comment by sbc100** [comment]
If you would prefer to fix forward rather than revert the current breakage is not actually hurting emscripten yet, its just preventing new changes from binaryen making their way to emscripten users. Just FYI.

**Comment by arsnyder16** [comment]
@sbc100 How quickly do you need the fix ? I don’t want to hold anything up

**Comment by sbc100** [comment]
I would say its worth reverting if its going to remain unfixed for more than a day or two.    Maybe safest just to land this revert if you are ok with that?

**Review by sbc100 — APPROVED** [review]

**Comment by arsnyder16** [comment]
Yea no problem

**Pull request merged**
