### PR TITLE
Update emscripten

### PR DESCRIPTION
**Pull request by kripken**
@dschuff : this should bring in a commit in emscripten that fixes that pthread_self issue, I realized there is a good solution for now ([simply move asm.js library methods into JS](https://github.com/kripken/emscripten/commit/e480c6ed0194fc72c866c9d2eef697c221d1ae2d)).

### CODE REVIEW

**Comment by kripken** [comment]
We should probably add a test for this, that checks we supply all imports. Perhaps the binaryen shell should error if so?

**Comment by kripken** [comment]
I added those asserts to wasm.js. Seems like the right thing to do. If not, we can change later, for now it seems safer to have them in.

**Comment by kripken** [comment]
Merged. @dschuff, wasm backend hello world should now work in v8 with asserting on all imports, please verify if you get a chance.

**Comment by dschuff** [comment]
Success!
Hello world works.
I also tried flipping the asm2wasm build on the waterfall to the LLVM backend and most of those tests work too. There are a bunch of new ones that fail too (that work with asm2wasm) but that's probably good news, in that the tests are hitting some corner cases we can fix. I'll have a look on Monday.

**Pull request merged**
