### PR TITLE
Fix compilation with WASM_INTERPRETER_DEBUG

### PR DESCRIPTION
**Pull request by ddcc**

### CODE REVIEW

**Comment by kripken** [comment]
Maybe take a look at https://github.com/WebAssembly/binaryen/commit/dcebddda8cdea0686e7dcf6cb938b25d79e113b9. That's in the `stack` branch which hasn't landed yet. We should do whichever is better of the two commits, or combine them.

**Comment by ddcc** [comment]
I think your patch looks more comprehensive.

**Comment by dschuff** [comment]
(I think you can still make an equivalent commit on master if you want that functionality now, before the stack branch merges)

**Comment by kripken** [comment]
Ok, maybe I'll do that. I was hoping to get all of `stack` merged sooner rather than later, but that's now how it ended up...

**Comment by dschuff** [comment]
We may want to keep stack on a branch alongside the binary_0xC branch in
the spec and the engines, so that we can transition about the same time?
Probably worth a separate discussion about that.

**Comment by kripken** [comment]
In general we've tagged versions and moved to the next version on `master`, which makes sense since we have a lot of code churn - so putting 0xc features on a side branch would mean either doing all development on 0xc, or a lot of rebasing between the two.

But so far I haven't had a need to do anything 0xc specific on master, I've landed globals, tables and memories without breaking support for 0xb. However, that will probably change soon.

**Comment by dschuff** [comment]
This is probably the wrong place to discuss it now, but might as well leave it here since it's on-thread. 

1. After some offline discussion with @kripken we decided that we could go ahead and put 0xc stuff on master since we don't expect to add anything new for 0xb. For uses that need 0xb, we can just check out the last version of Binaryen that worked with 0xb. Which brings me to...
2. The last version that works completely with all of the other tools on 0xb is e268d939b86d8639d014b8036e7664d66b6a32e9 (before the tables and memories). We discovered from the waterfall builds that apparently `sexpr-wasm` doesn't support the syntax for that yet. We could switch to `wasm-as` for those use cases, but instead, I think for the purposes we care about we can just declare that version as the last 0xb version.
3. For the waterfall build: 
Currently the waterfall build tests the following:
 1. Bare LLVM/clang with the C torture tests against v8's native wasm support (which will probably remain 0xb until the browsers have a flag day). 
 2. emscripten-integrated asm2wasm and LLVM backend support with the C torture tests against v8's native wasm support
 3. emscripten+LLVM backend with the emscripten test suite against the binaryen interpreter (`INTERPRET_BINARY` binaryen method).

I think we will use the 0xb version of `s2wasm` for (i) so we can continue to test v8 native wasm, and switch to INTERPRET_BINARY for (ii). @jgravelle-google should have a patch to the waterfall repo for that soon.

**Comment by binji** [comment]
Tables and memories aren't in binary-0xb, correct? I believe sexpr-wasm master is consistent with spec master (at least it works with testsuite master). I've been working on updating sexpr-wasm to binary-0xc of the spec repo. Pretty close with the stack stuff, but still need to do globals, tables and memories.

**Pull request closed without merging**
