### PR TITLE
fix incorrect assert in BinaryenHostGetOperand

### LINKED ISSUE #2392: getExpressionInfo on a Host node causes assertion error
An assertion is thrown when calling the js api `binaryen.getExpressionInfo` on an expression that has type `binaryen.HostId`. I have attached a simple example that fails.  Here is the assertion

`Assertion failed: expression->is<Call>(), at: binaryen/src/binaryen-c.cpp,2048,BinaryenHostGetOperand`

This is using the latest npm version 89.0.0 of binaryen.

[test.js.zip](https://github.com/WebAssembly/binaryen/files/3736271/test.js.zip)

### PR DESCRIPTION
**Pull request by brmorr**
BinaryenHostGetOperand incorrectly asserted `expression->is<Call>`.  Changes to `expression->is<Host>`.  Fixes #2392 

I added a new js test to validate the fix.

### CODE REVIEW

**Comment by brmorr** [comment]
@kripken My test is failing here because the pointers for the expression pointers in the logged ExpressionInfo are different between the test run and the captured test output.  I see in some other js tests where the info objects are pruned before logging to avoid the variability of the expression pointers.  I assume that is the correct test pattern to follow here?

**Comment by brmorr** [comment]
Now that I have dug around the code a bit more, I see that there is a js test kitchen-sink.js, which has some other simple tests of getExpressionInfo.  It seems like that is the place for this one additional getExpressionInfo test.  If that is preferred then I can make that change.

**Comment by kripken** [comment]
Thanks @brmorr, looks good!

Yeah, I think that adding to `kitchen-sink.js` is simpler, as it would be shorter and could avoid duplicating that cleanup function.

**Comment by brmorr** [comment]
I moved the test over to kitchen-sink, as discussed.  It should be good to go.

**Pull request merged**
