### PR TITLE
Initial asm.js output for binaryen-c / binaryen.js

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR adds `BinaryenModulePrintAsmjs` to binaryen-c respectively `Module#emitAsmjs` to binaryen.js.

While the basics are working, there still seem to be a couple of issues on the wasm2asm side that are not in the scope of this PR.

Also
- fixes an issue with unnamed locals (when not creating modules from a .wast) by introducing `Function::getLocalNameOrGeneric` and using it in `wasm2asm.h`
- adds `shared.bc` generated by `build-js.sh` to `.gitignore` and
- includes recompiled versions of the respective `bin/` files.

Things to note:
* wasm2asm does not properly handle a `return` as the body of a function, yet, mostly affecting programmatically created function bodies. Running the optimizer priorily fixes this (optimizes the return away making the expression the body's return value), as well as providing an expression as the body directly instead. Probably happens [around here](https://github.com/WebAssembly/binaryen/blob/master/src/wasm2asm.h#L543).

```js
// works
mod.addFunction("main", ftype, [], mod.i32.const(2));
mod.emitAsmjs();

// does not work
mod.addFunction("main", ftype, [], mod.return(mod.i32.const(2)));
mod.emitAsmjs();

// works
mod.addFunction("main", ftype, [], mod.return(mod.i32.const(2)));
mod.optimize(); 
mod.emitAsmjs();
```
* wasm2asm seems to add additional polyfill functions to the wasm module that are most likely emitted as well when calling `emitText` or similar after `emitAsmjs`. Copying the module prior to emitting or removing the functions again afterwards could fix this.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, nice.

1. Does this need to rebuild the .js builds after that infinite recursion fix?
2. Let's add a test here.
3. Let's open issues on the orthogonal wasm2asm issues, so we don't forget them.

**Comment by dcodeIO** [comment]
JS files have been compiled with 1.37.17 and should be fine (in reference of https://github.com/WebAssembly/binaryen/issues/1135). Can try to add a test - is test/binaryen.js the right place for it?

**Comment by kripken** [comment]
Yeah, test should go under `test/binaryen.js/`.

**Comment by dcodeIO** [comment]
Note, though, that this test case has been specifically crafted to show that `emitAsmjs` is *basically* working (with the getLocalNameOrGeneric change I made), while it *actually* doesn't do anything useful yet in more complex scenarios. For example

* using a `module.block` as the body with an inner `return` or an i32 result obtained via `getLocal` fails
* calling `module.validate()` afterwards fails because of the injected asm.js helpers
* ...

**Comment by kripken** [comment]
Thanks! Yeah, the test will need to be improved as the functionality here gets more useful.

**Pull request merged**
