### PR TITLE
Rename Indirect to NonDirect in CallGraphPropertyAnalysis

### PR DESCRIPTION
**Pull request by kripken**
This is in preparation for [`CallRef`](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md), which takes a reference to a function
and calls it.

CallGraphPropertyAnalysis needs to be aware of anything that is not a
direct call, and the best name I can think of that covers `CallIndirect` and
`CallRef` is "non-direct". Maybe there's a better idea though?

### CODE REVIEW

**Comment by aheejin** [comment]
In theory I think `call.ref` also can be called an indirect call, so I think that should be fine to leave it as is, but given that we have an instruction `call_indirect`, I understand why you would want a non-ambiguous name... I think either is fine, maybe modulo the asyncify flag you mentioned..?

**Review by aheejin — APPROVED** [review]
Anyway I think the name is OK either way

**Comment by kripken** [comment]
@aheejin You led me to think about another option here. Since `call_ref` is really a form of indirect call, maybe we could actually reuse the same class for both? That is, `CallIndirect` would be `call_indirect` if the target is an `int32`, and if it's a typed function reference then it would be a `call_ref`. This could almost just work, since the C++ class would be the same, anyhow. It would be a little like how `local.tee` and `local.set` are the same class.

This seems like less work and less code, and the downsides seem pretty minor. What do you think?

(And if we do that, then there's no need for this PR, but that's less important.)

**Comment by kripken** [comment]
Reading more carefully, `CallIndirect` has a function type signature, which would not be used for a reference call. So this isn't perfectly symmetrical. If we reuse the same class, that field would not be used for reference calls.

**Comment by kripken** [comment]
After experimenting a bit with both options, I think the idea to use a single class for both would save some code, but increase complexity. We'd have to add a field to identify it as which of the two it is, since we can't use the type for that (it might be unreachable), and other issues.

So I'll land this and move forward with the straightforward approach of a new `CallRef` class.

**Comment by aheejin** [comment]
Yeah I agree using separate classes for them is better.

**Pull request merged**
