### PR TITLE
Use interned Names in NoExitRuntime

### PR DESCRIPTION
**Pull request by kripken**
I'm not super-happy about having a static global vector like that, though. Is there a better C++ way?

### CODE REVIEW

**Comment by dschuff** [comment]
I guess the idea behind using `Name`s is so the compare is just an identity comparison?
Could you just use a static `std::array<Name, 4>`?

**Comment by kripken** [comment]
@dschuff yeah, when interned comparisons are just pointer comparisons.

Modified to use a `std::array`. I wish the `, 4` could be avoided, but nothing's perfect ;)

**Comment by binji** [comment]
This might add some global constructors, which may be undesirable (for example, Chromium tries to avoid them to improve startup speed). Probably not a big deal for a few names, but worth keeping in mind for things like this.

**Comment by kripken** [comment]
@binji good point, thanks, updated to avoid that. Although now it will initialize those names once per function. Probably fine, but no simple way to do something optimal here that I can see.

**Pull request merged**
