### PR TITLE
Typed continuations: nocont and cont basic heap types

### PR DESCRIPTION
**Pull request by frank-emrich**
This PR is part of a series that adds basic support for the [typed continuations/wasmfx proposal](https://github.com/wasmfx/specfx).

This particular types adds `cont` and `nocont` as top and bottom types for continuation types, completely analogous to `func` and `nofunc` for function types (also: `exn` and `noexn`).

### CODE REVIEW

**Comment by tlively** [comment]
The `isFunction` / `isSignature` distinction is definitely something I would like to make better, perhaps by removing `isFunction`, but I haven't looked into it in detail. We also don't have different versions of `isStruct` or `isArray` that include the `struct` and `array` heap types, so we're already inconsistent about the API structure. All this is to say I think it would be fine (and even preferable) to undo the renaming of `isContinuation`.

**Comment by frank-emrich** [comment]
Fair enough, I'm happy to keep the old name. I've undone the renaming and updated the PR description.

**Review by tlively — COMMENTED** [review]
LGTM, but for more test coverage it might be a good idea to add continuation types to `TestHeapTypeRelations` in test/gtest/type-builder.cpp as well.

**Comment by frank-emrich** [comment]
Good call, I actually caught a place I had forgotten to update this way!

**Review by tlively — APPROVED** [review]
Excellent!

**Comment by frank-emrich** [comment]
Just FYI, this was the last missing piece to add basic support for the core of the proposal to binaryen. Only `resume.throw` and `barrier` instructions are missing, which aren't a high priority for us at this point.

I'd therefore prioritize implementing validation for the already added instructions first. Can the new wat/wast parser now be used for spec tests, or is that going to be the case soon-ish? I'm asking because I'm hoping to re-use our existing spec tests when adding validation, rather than having to transform them into binaryen's text format.

**Comment by tlively** [comment]
No support for running spec tests with the new parser yet, but I hope to be done with that within a couple weeks.

**Comment by tlively** [comment]
@frank-emrich, the new parser is now used for top-level modules in wasm-shell, so you should try running your spec tests now. It's possible you'll run into some other limitations, but at least there should be fewer now. I plan to keep working toward being able to run the full upstream test suite.

**Comment by frank-emrich** [comment]
That's great, thanks for letting me know!

**Pull request merged**
